module.exports = {
  "Version": "FIX.4.1",
  "Header": {
    "8": "BeginString",
    "9": "BodyLength",
    "34": "MsgSeqNum",
    "35": "MsgType",
    "43": "PossDupFlag",
    "49": "SenderCompID",
    "50": "SenderSubID",
    "52": "SendingTime",
    "56": "TargetCompID",
    "57": "TargetSubID",
    "90": "SecureDataLen",
    "91": "SecureData",
    "97": "PossResend",
    "115": "OnBehalfOfCompID",
    "116": "OnBehalfOfSubID",
    "122": "OrigSendingTime",
    "128": "DeliverToCompID",
    "129": "DeliverToSubID",
    "142": "SenderLocationID",
    "143": "TargetLocationID",
    "144": "OnBehalfOfLocationID",
    "145": "DeliverToLocationID",
    "Required": ["8", "9", "35", "49", "56", "34", "52"],
    "Optional": ["115", "128", "90", "91", "50", "142", "57", "143", "116", "144", "129", "145", "43", "97", "122"]
  },
  "Trailer": {
    "10": "CheckSum",
    "89": "Signature",
    "93": "SignatureLength",
    "Required": ["10"],
    "Optional": ["93", "89"]
  },
  "Messages": {
    "0": {
      "name": "Heartbeat",
      "msgcat": "admin"
    },
    "1": {
      "name": "TestRequest",
      "msgcat": "admin"
    },
    "2": {
      "name": "ResendRequest",
      "msgcat": "admin"
    },
    "3": {
      "name": "Reject",
      "msgcat": "admin"
    },
    "4": {
      "name": "SequenceReset",
      "msgcat": "admin"
    },
    "5": {
      "name": "Logout",
      "msgcat": "admin"
    },
    "6": {
      "name": "IOI",
      "msgcat": "app"
    },
    "7": {
      "name": "Advertisement",
      "msgcat": "app"
    },
    "8": {
      "name": "ExecutionReport",
      "msgcat": "app"
    },
    "9": {
      "name": "OrderCancelReject",
      "msgcat": "app"
    },
    "A": {
      "name": "Logon",
      "msgcat": "admin"
    },
    "B": {
      "name": "News",
      "msgcat": "app"
    },
    "C": {
      "name": "Email",
      "msgcat": "app"
    },
    "D": {
      "name": "NewOrderSingle",
      "msgcat": "app"
    },
    "E": {
      "name": "NewOrderList",
      "msgcat": "app"
    },
    "F": {
      "name": "OrderCancelRequest",
      "msgcat": "app"
    },
    "G": {
      "name": "OrderCancelReplaceRequest",
      "msgcat": "app"
    },
    "H": {
      "name": "OrderStatusRequest",
      "msgcat": "app"
    },
    "J": {
      "name": "Allocation",
      "msgcat": "app"
    },
    "K": {
      "name": "ListCancelRequest",
      "msgcat": "app"
    },
    "L": {
      "name": "ListExecute",
      "msgcat": "app"
    },
    "M": {
      "name": "ListStatusRequest",
      "msgcat": "app"
    },
    "N": {
      "name": "ListStatus",
      "msgcat": "app"
    },
    "P": {
      "name": "AllocationInstructionAck",
      "msgcat": "app"
    },
    "Q": {
      "name": "DontKnowTrade",
      "msgcat": "app"
    },
    "R": {
      "name": "QuoteRequest",
      "msgcat": "app"
    },
    "S": {
      "name": "Quote",
      "msgcat": "app"
    },
    "T": {
      "name": "SettlementInstructions",
      "msgcat": "app"
    }
  },
  "Fields": {
    "1": "Account",
    "2": "AdvId",
    "3": "AdvRefID",
    "4": "AdvSide",
    "5": "AdvTransType",
    "6": "AvgPx",
    "7": "BeginSeqNo",
    "8": "BeginString",
    "9": "BodyLength",
    "10": "CheckSum",
    "11": "ClOrdID",
    "12": "Commission",
    "13": "CommType",
    "14": "CumQty",
    "15": "Currency",
    "16": "EndSeqNo",
    "17": "ExecID",
    "18": "ExecInst",
    "19": "ExecRefID",
    "20": "ExecTransType",
    "21": "HandlInst",
    "22": "IDSource",
    "23": "IOIid",
    "24": "IOIOthSvc",
    "25": "IOIQltyInd",
    "26": "IOIRefID",
    "27": "IOIShares",
    "28": "IOITransType",
    "29": "LastCapacity",
    "30": "LastMkt",
    "31": "LastPx",
    "32": "LastShares",
    "33": "LinesOfText",
    "34": "MsgSeqNum",
    "35": "MsgType",
    "36": "NewSeqNo",
    "37": "OrderID",
    "38": "OrderQty",
    "39": "OrdStatus",
    "40": "OrdType",
    "41": "OrigClOrdID",
    "42": "OrigTime",
    "43": "PossDupFlag",
    "44": "Price",
    "45": "RefSeqNum",
    "46": "RelatdSym",
    "47": "Rule80A",
    "48": "SecurityID",
    "49": "SenderCompID",
    "50": "SenderSubID",
    "52": "SendingTime",
    "53": "Shares",
    "54": "Side",
    "55": "Symbol",
    "56": "TargetCompID",
    "57": "TargetSubID",
    "58": "Text",
    "59": "TimeInForce",
    "60": "TransactTime",
    "61": "Urgency",
    "62": "ValidUntilTime",
    "63": "SettlmntTyp",
    "64": "FutSettDate",
    "65": "SymbolSfx",
    "66": "ListID",
    "67": "ListSeqNo",
    "68": "ListNoOrds",
    "69": "ListExecInst",
    "70": "AllocID",
    "71": "AllocTransType",
    "72": "RefAllocID",
    "73": "NoOrders",
    "74": "AvgPrxPrecision",
    "75": "TradeDate",
    "76": "ExecBroker",
    "77": "OpenClose",
    "78": "NoAllocs",
    "79": "AllocAccount",
    "80": "AllocShares",
    "81": "ProcessCode",
    "82": "NoRpts",
    "83": "RptSeq",
    "84": "CxlQty",
    "87": "AllocStatus",
    "88": "AllocRejCode",
    "89": "Signature",
    "90": "SecureDataLen",
    "91": "SecureData",
    "92": "BrokerOfCredit",
    "93": "SignatureLength",
    "94": "EmailType",
    "95": "RawDataLength",
    "96": "RawData",
    "97": "PossResend",
    "98": "EncryptMethod",
    "99": "StopPx",
    "100": "ExDestination",
    "102": "CxlRejReason",
    "103": "OrdRejReason",
    "104": "IOIQualifier",
    "105": "WaveNo",
    "106": "Issuer",
    "107": "SecurityDesc",
    "108": "HeartBtInt",
    "109": "ClientID",
    "110": "MinQty",
    "111": "MaxFloor",
    "112": "TestReqID",
    "113": "ReportToExch",
    "114": "LocateReqd",
    "115": "OnBehalfOfCompID",
    "116": "OnBehalfOfSubID",
    "117": "QuoteID",
    "118": "NetMoney",
    "119": "SettlCurrAmt",
    "120": "SettlCurrency",
    "121": "ForexReq",
    "122": "OrigSendingTime",
    "123": "GapFillFlag",
    "124": "NoExecs",
    "126": "ExpireTime",
    "127": "DKReason",
    "128": "DeliverToCompID",
    "129": "DeliverToSubID",
    "130": "IOINaturalFlag",
    "131": "QuoteReqID",
    "132": "BidPx",
    "133": "OfferPx",
    "134": "BidSize",
    "135": "OfferSize",
    "136": "NoMiscFees",
    "137": "MiscFeeAmt",
    "138": "MiscFeeCurr",
    "139": "MiscFeeType",
    "140": "PrevClosePx",
    "141": "ResetSeqNumFlag",
    "142": "SenderLocationID",
    "143": "TargetLocationID",
    "144": "OnBehalfOfLocationID",
    "145": "DeliverToLocationID",
    "146": "NoRelatedSym",
    "147": "Subject",
    "148": "Headline",
    "149": "URLLink",
    "150": "ExecType",
    "151": "LeavesQty",
    "152": "CashOrderQty",
    "153": "AllocAvgPx",
    "154": "AllocNetMoney",
    "155": "SettlCurrFxRate",
    "156": "SettlCurrFxRateCalc",
    "157": "NumDaysInterest",
    "158": "AccruedInterestRate",
    "159": "AccruedInterestAmt",
    "160": "SettlInstMode",
    "161": "AllocText",
    "162": "SettlInstID",
    "163": "SettlInstTransType",
    "164": "EmailThreadID",
    "165": "SettlInstSource",
    "166": "SettlLocation",
    "167": "SecurityType",
    "168": "EffectiveTime",
    "169": "StandInstDbType",
    "170": "StandInstDbName",
    "171": "StandInstDbID",
    "172": "SettlDeliveryType",
    "173": "SettlDepositoryCode",
    "174": "SettlBrkrCode",
    "175": "SettlInstCode",
    "176": "SecuritySettlAgentName",
    "177": "SecuritySettlAgentCode",
    "178": "SecuritySettlAgentAcctNum",
    "179": "SecuritySettlAgentAcctName",
    "180": "SecuritySettlAgentContactName",
    "181": "SecuritySettlAgentContactPhone",
    "182": "CashSettlAgentName",
    "183": "CashSettlAgentCode",
    "184": "CashSettlAgentAcctNum",
    "185": "CashSettlAgentAcctName",
    "186": "CashSettlAgentContactName",
    "187": "CashSettlAgentContactPhone",
    "188": "BidSpotRate",
    "189": "BidForwardPoints",
    "190": "OfferSpotRate",
    "191": "OfferForwardPoints",
    "192": "OrderQty2",
    "193": "FutSettDate2",
    "194": "LastSpotRate",
    "195": "LastForwardPoints",
    "196": "AllocLinkID",
    "197": "AllocLinkType",
    "198": "SecondaryOrderID",
    "199": "NoIOIQualifiers",
    "200": "MaturityMonthYear",
    "201": "PutOrCall",
    "202": "StrikePrice",
    "203": "CoveredOrUncovered",
    "204": "CustomerOrFirm",
    "205": "MaturityDay",
    "206": "OptAttribute",
    "207": "SecurityExchange",
    "208": "NotifyBrokerOfCredit",
    "209": "AllocHandlInst",
    "210": "MaxShow",
    "211": "PegDifference",
    "HasValue": ["4", "5", "13", "18", "20", "21", "22", "24", "25", "27", "28", "29", "35", "39", "40", "43", "47", "54", "59", "61", "63", "71", "77", "81", "87", "88", "94", "97", "98", "102", "103", "104", "113", "114", "121", "123", "127", "130", "139", "141", "150", "156", "160", "163", "165", "166", "167", "169", "197", "201", "203", "204", "208", "209"],
    "ValueDictionary": {
      "4": [{
        "B": "BUY"
      }, {
        "S": "SELL"
      }, {
        "T": "TRADE"
      }, {
        "X": "CROSS"
      }],
      "5": [{
        "C": "CANCEL"
      }, {
        "N": "NEW"
      }, {
        "R": "REPLACE"
      }],
      "13": [{
        "1": "PER_SHARE"
      }, {
        "2": "PERCENTAGE"
      }, {
        "3": "ABSOLUTE"
      }],
      "18": [{
        "0": "STAY_ON_OFFERSIDE"
      }, {
        "1": "NOT_HELD"
      }, {
        "2": "WORK"
      }, {
        "3": "GO_ALONG"
      }, {
        "4": "OVER_THE_DAY"
      }, {
        "5": "HELD"
      }, {
        "6": "PARTICIPATE_DONT_INITIATE"
      }, {
        "7": "STRICT_SCALE"
      }, {
        "8": "TRY_TO_SCALE"
      }, {
        "9": "STAY_ON_BIDSIDE"
      }, {
        "A": "NO_CROSS"
      }, {
        "B": "OK_TO_CROSS"
      }, {
        "C": "CALL_FIRST"
      }, {
        "D": "PERCENT_OF_VOLUME"
      }, {
        "E": "DO_NOT_INCREASE"
      }, {
        "F": "DO_NOT_REDUCE"
      }, {
        "G": "ALL_OR_NONE"
      }, {
        "I": "INSTITUTIONS_ONLY"
      }, {
        "L": "LAST_PEG"
      }, {
        "M": "MID_PRICE_PEG"
      }, {
        "N": "NON_NEGOTIABLE"
      }, {
        "O": "OPENING_PEG"
      }, {
        "P": "MARKET_PEG"
      }, {
        "R": "PRIMARY_PEG"
      }, {
        "S": "SUSPEND"
      }, {
        "U": "CUSTOMER_DISPLAY_INSTRUCTION"
      }, {
        "V": "NETTING"
      }],
      "20": [{
        "0": "NEW"
      }, {
        "1": "CANCEL"
      }, {
        "2": "CORRECT"
      }, {
        "3": "STATUS"
      }],
      "21": [{
        "1": "AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION"
      }, {
        "2": "AUTOMATED_EXECUTION_ORDER_PUBLIC_BROKER_INTERVENTION_OK"
      }, {
        "3": "MANUAL_ORDER_BEST_EXECUTION"
      }],
      "22": [{
        "1": "CUSIP"
      }, {
        "2": "SEDOL"
      }, {
        "3": "QUIK"
      }, {
        "4": "ISIN_NUMBER"
      }, {
        "5": "RIC_CODE"
      }, {
        "6": "ISO_CURRENCY_CODE"
      }, {
        "7": "ISO_COUNTRY_CODE"
      }],
      "24": [{
        "A": "AUTEX"
      }, {
        "B": "BRIDGE"
      }],
      "25": [{
        "H": "HIGH"
      }, {
        "L": "LOW"
      }, {
        "M": "MEDIUM"
      }],
      "27": [{
        "L": "LARGE"
      }, {
        "M": "MEDIUM"
      }, {
        "S": "SMALL"
      }],
      "28": [{
        "C": "CANCEL"
      }, {
        "N": "NEW"
      }, {
        "R": "REPLACE"
      }],
      "29": [{
        "1": "AGENT"
      }, {
        "2": "CROSS_AS_AGENT"
      }, {
        "3": "CROSS_AS_PRINCIPAL"
      }, {
        "4": "PRINCIPAL"
      }],
      "35": [{
        "0": "HEARTBEAT"
      }, {
        "1": "TEST_REQUEST"
      }, {
        "2": "RESEND_REQUEST"
      }, {
        "3": "REJECT"
      }, {
        "4": "SEQUENCE_RESET"
      }, {
        "5": "LOGOUT"
      }, {
        "6": "INDICATION_OF_INTEREST"
      }, {
        "7": "ADVERTISEMENT"
      }, {
        "8": "EXECUTION_REPORT"
      }, {
        "9": "ORDER_CANCEL_REJECT"
      }, {
        "A": "LOGON"
      }, {
        "B": "NEWS"
      }, {
        "C": "EMAIL"
      }, {
        "D": "ORDER_D"
      }, {
        "E": "ORDER_E"
      }, {
        "F": "ORDER_CANCEL_REQUEST"
      }, {
        "G": "ORDER_CANCEL_REPLACE_REQUEST"
      }, {
        "H": "ORDER_STATUS_REQUEST"
      }, {
        "J": "ALLOCATION"
      }, {
        "K": "LIST_CANCEL_REQUEST"
      }, {
        "L": "LIST_EXECUTE"
      }, {
        "M": "LIST_STATUS_REQUEST"
      }, {
        "N": "LIST_STATUS"
      }, {
        "P": "ALLOCATION_ACK"
      }, {
        "Q": "DONT_KNOW_TRADE"
      }, {
        "R": "QUOTE_REQUEST"
      }, {
        "S": "QUOTE"
      }, {
        "T": "SETTLEMENT_INSTRUCTIONS"
      }],
      "39": [{
        "0": "NEW"
      }, {
        "1": "PARTIALLY_FILLED"
      }, {
        "2": "FILLED"
      }, {
        "3": "DONE_FOR_DAY"
      }, {
        "4": "CANCELED"
      }, {
        "5": "REPLACED"
      }, {
        "6": "PENDING_CANCEL_REPLACE"
      }, {
        "7": "STOPPED"
      }, {
        "8": "REJECTED"
      }, {
        "9": "SUSPENDED"
      }, {
        "A": "PENDING_NEW"
      }, {
        "B": "CALCULATED"
      }, {
        "C": "EXPIRED"
      }],
      "40": [{
        "1": "MARKET"
      }, {
        "2": "LIMIT"
      }, {
        "3": "STOP"
      }, {
        "4": "STOP_LIMIT"
      }, {
        "5": "MARKET_ON_CLOSE"
      }, {
        "6": "WITH_OR_WITHOUT"
      }, {
        "7": "LIMIT_OR_BETTER"
      }, {
        "8": "LIMIT_WITH_OR_WITHOUT"
      }, {
        "9": "ON_BASIS"
      }, {
        "A": "ON_CLOSE"
      }, {
        "B": "LIMIT_ON_CLOSE"
      }, {
        "C": "FOREX_C"
      }, {
        "D": "PREVIOUSLY_QUOTED"
      }, {
        "E": "PREVIOUSLY_INDICATED"
      }, {
        "F": "FOREX_F"
      }, {
        "G": "FOREX_G"
      }, {
        "H": "FOREX_H"
      }, {
        "P": "PEGGED"
      }],
      "43": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "47": [{
        "A": "AGENCY_SINGLE_ORDER"
      }, {
        "B": "SHORT_EXEMPT_TRANSACTION_B"
      }, {
        "C": "PROGRAM_ORDER_NON_INDEX_ARB_FOR_MEMBER_FIRM_ORG"
      }, {
        "D": "PROGRAM_ORDER_INDEX_ARB_FOR_MEMBER_FIRM_ORG"
      }, {
        "E": "REGISTERED_EQUITY_MARKET_MAKER_TRADES"
      }, {
        "F": "SHORT_EXEMPT_TRANSACTION_F"
      }, {
        "H": "SHORT_EXEMPT_TRANSACTION_H"
      }, {
        "I": "INDIVIDUAL_INVESTOR_SINGLE_ORDER"
      }, {
        "J": "PROGRAM_ORDER_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER"
      }, {
        "K": "PROGRAM_ORDER_NON_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER"
      }, {
        "L": "SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE"
      }, {
        "M": "PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_MEMBER"
      }, {
        "N": "PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_MEMBER"
      }, {
        "O": "COMPETING_DEALER_TRADES_O"
      }, {
        "P": "PRINCIPAL"
      }, {
        "R": "COMPETING_DEALER_TRADES_R"
      }, {
        "S": "SPECIALIST_TRADES"
      }, {
        "T": "COMPETING_DEALER_TRADES_T"
      }, {
        "U": "PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_AGENCY"
      }, {
        "W": "ALL_OTHER_ORDERS_AS_AGENT_FOR_OTHER_MEMBER"
      }, {
        "X": "SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_NOT_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE"
      }, {
        "Y": "PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_AGENCY"
      }, {
        "Z": "SHORT_EXEMPT_TRANSACTION_FOR_NON_MEMBER_COMPETING_MARKET_MAKER"
      }],
      "54": [{
        "1": "BUY"
      }, {
        "2": "SELL"
      }, {
        "3": "BUY_MINUS"
      }, {
        "4": "SELL_PLUS"
      }, {
        "5": "SELL_SHORT"
      }, {
        "6": "SELL_SHORT_EXEMPT"
      }, {
        "7": "UNDISCLOSED"
      }, {
        "8": "CROSS"
      }],
      "59": [{
        "0": "DAY"
      }, {
        "1": "GOOD_TILL_CANCEL"
      }, {
        "2": "AT_THE_OPENING"
      }, {
        "3": "IMMEDIATE_OR_CANCEL"
      }, {
        "4": "FILL_OR_KILL"
      }, {
        "5": "GOOD_TILL_CROSSING"
      }, {
        "6": "GOOD_TILL_DATE"
      }],
      "61": [{
        "0": "NORMAL"
      }, {
        "1": "FLASH"
      }, {
        "2": "BACKGROUND"
      }],
      "63": [{
        "0": "REGULAR"
      }, {
        "1": "CASH"
      }, {
        "2": "NEXT_DAY"
      }, {
        "3": "T_PLUS_2"
      }, {
        "4": "T_PLUS_3"
      }, {
        "5": "T_PLUS_4"
      }, {
        "6": "FUTURE"
      }, {
        "7": "WHEN_ISSUED"
      }, {
        "8": "SELLERS_OPTION"
      }, {
        "9": "T_PLUS_5"
      }],
      "71": [{
        "0": "NEW"
      }, {
        "1": "REPLACE"
      }, {
        "2": "CANCEL"
      }, {
        "3": "PRELIMINARY"
      }, {
        "4": "CALCULATED"
      }],
      "77": [{
        "C": "CLOSE"
      }, {
        "O": "OPEN"
      }],
      "81": [{
        "0": "REGULAR"
      }, {
        "1": "SOFT_DOLLAR"
      }, {
        "2": "STEP_IN"
      }, {
        "3": "STEP_OUT"
      }, {
        "4": "SOFT_DOLLAR_STEP_IN"
      }, {
        "5": "SOFT_DOLLAR_STEP_OUT"
      }, {
        "6": "PLAN_SPONSOR"
      }],
      "87": [{
        "0": "ACCEPTED"
      }, {
        "1": "REJECTED"
      }, {
        "2": "PARTIAL_ACCEPT"
      }, {
        "3": "RECEIVED"
      }],
      "88": [{
        "0": "UNKNOWN_ACCOUNT"
      }, {
        "1": "INCORRECT_QUANTITY"
      }, {
        "2": "INCORRECT_AVERAGE_PRICE"
      }, {
        "3": "UNKNOWN_EXECUTING_BROKER_MNEMONIC"
      }, {
        "4": "COMMISSION_DIFFERENCE"
      }, {
        "5": "UNKNOWN_ORDERID"
      }, {
        "6": "UNKNOWN_LISTID"
      }, {
        "7": "OTHER"
      }],
      "94": [{
        "0": "NEW"
      }, {
        "1": "REPLY"
      }, {
        "2": "ADMIN_REPLY"
      }],
      "97": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "98": [{
        "0": "NONE"
      }, {
        "1": "PKCS"
      }, {
        "2": "DES"
      }, {
        "3": "PKCS_DES"
      }, {
        "4": "PGP_DES"
      }, {
        "5": "PGP_DES_MD5"
      }, {
        "6": "PEM_DES_MD5"
      }],
      "102": [{
        "0": "TOO_LATE_TO_CANCEL"
      }, {
        "1": "UNKNOWN_ORDER"
      }],
      "103": [{
        "0": "BROKER_OPTION"
      }, {
        "1": "UNKNOWN_SYMBOL"
      }, {
        "2": "EXCHANGE_CLOSED"
      }, {
        "3": "ORDER_EXCEEDS_LIMIT"
      }, {
        "4": "TOO_LATE_TO_ENTER"
      }, {
        "5": "UNKNOWN_ORDER"
      }, {
        "6": "DUPLICATE_ORDER"
      }],
      "104": [{
        "A": "ALL_OR_NONE"
      }, {
        "C": "AT_THE_CLOSE"
      }, {
        "I": "IN_TOUCH_WITH"
      }, {
        "L": "LIMIT"
      }, {
        "M": "MORE_BEHIND"
      }, {
        "O": "AT_THE_OPEN"
      }, {
        "P": "TAKING_A_POSITION"
      }, {
        "Q": "AT_THE_MARKET"
      }, {
        "S": "PORTFOLIO_SHOW_N"
      }, {
        "T": "THROUGH_THE_DAY"
      }, {
        "V": "VERSUS"
      }, {
        "W": "INDICATION"
      }, {
        "X": "CROSSING_OPPORTUNITY"
      }, {
        "Y": "AT_THE_MIDPOINT"
      }, {
        "Z": "PRE_OPEN"
      }],
      "113": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "114": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "121": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "123": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "127": [{
        "A": "UNKNOWN_SYMBOL"
      }, {
        "B": "WRONG_SIDE"
      }, {
        "C": "QUANTITY_EXCEEDS_ORDER"
      }, {
        "D": "NO_MATCHING_ORDER"
      }, {
        "E": "PRICE_EXCEEDS_LIMIT"
      }, {
        "Z": "OTHER"
      }],
      "130": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "139": [{
        "1": "REGULATORY"
      }, {
        "2": "TAX"
      }, {
        "3": "LOCAL_COMMISSION"
      }, {
        "4": "EXCHANGE_FEES"
      }, {
        "5": "STAMP"
      }, {
        "6": "LEVY"
      }, {
        "7": "OTHER"
      }, {
        "8": "MARKUP"
      }],
      "141": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "150": [{
        "0": "NEW"
      }, {
        "1": "PARTIAL_FILL"
      }, {
        "2": "FILL"
      }, {
        "3": "DONE_FOR_DAY"
      }, {
        "4": "CANCELLED"
      }, {
        "5": "REPLACE"
      }, {
        "6": "PENDING_CANCEL_REPLACE"
      }, {
        "7": "STOPPED"
      }, {
        "8": "REJECTED"
      }, {
        "9": "SUSPENDED"
      }, {
        "A": "PENDING_NEW"
      }, {
        "B": "CALCULATED"
      }, {
        "C": "EXPIRED"
      }],
      "156": [{
        "M": "MULTIPLY"
      }, {
        "D": "DIVIDE"
      }],
      "160": [{
        "0": "DEFAULT"
      }, {
        "1": "STANDING_INSTRUCTIONS_PROVIDED"
      }, {
        "2": "SPECIFIC_ALLOCATION_ACCOUNT_OVERRIDING"
      }, {
        "3": "SPECIFIC_ALLOCATION_ACCOUNT_STANDING"
      }],
      "163": [{
        "C": "CANCEL"
      }, {
        "N": "NEW"
      }, {
        "R": "REPLACE"
      }],
      "165": [{
        "1": "BROKERS_INSTRUCTIONS"
      }, {
        "2": "INSTITUTIONS_INSTRUCTIONS"
      }],
      "166": [{
        "CED": "CEDEL"
      }, {
        "DTC": "DEPOSITORY_TRUST_COMPANY"
      }, {
        "EUR": "EUROCLEAR"
      }, {
        "FED": "FEDERAL_BOOK_ENTRY"
      }, {
        "ISO Country Code": "LOCAL_MARKET_SETTLE_LOCATION"
      }, {
        "PNY": "PHYSICAL"
      }, {
        "PTC": "PARTICIPANT_TRUST_COMPANY"
      }],
      "167": [{
        "BA": "BANKERS_ACCEPTANCE"
      }, {
        "CD": "CERTIFICATE_OF_DEPOSIT"
      }, {
        "CMO": "COLLATERALIZE_MORTGAGE_OBLIGATION"
      }, {
        "CORP": "CORPORATE_BOND"
      }, {
        "CP": "COMMERCIAL_PAPER"
      }, {
        "CPP": "CORPORATE_PRIVATE_PLACEMENT"
      }, {
        "CS": "COMMON_STOCK"
      }, {
        "FHA": "FEDERAL_HOUSING_AUTHORITY"
      }, {
        "FHL": "FEDERAL_HOME_LOAN"
      }, {
        "FN": "FEDERAL_NATIONAL_MORTGAGE_ASSOCIATION"
      }, {
        "FOR": "FOREIGN_EXCHANGE_CONTRACT"
      }, {
        "FUT": "FUTURE"
      }, {
        "GN": "GOVERNMENT_NATIONAL_MORTGAGE_ASSOCIATION"
      }, {
        "GOVT": "TREASURIES_PLUS_AGENCY_DEBENTURE"
      }, {
        "MF": "MUTUAL_FUND"
      }, {
        "MIO": "MORTGAGE_INTEREST_ONLY"
      }, {
        "MPO": "MORTGAGE_PRINCIPLE_ONLY"
      }, {
        "MPP": "MORTGAGE_PRIVATE_PLACEMENT"
      }, {
        "MPT": "MISCELLANEOUS_PASS_THRU"
      }, {
        "MUNI": "MUNICIPAL_BOND"
      }, {
        "NONE": "NO_ISITC_SECURITY_TYPE"
      }, {
        "OPT": "OPTION"
      }, {
        "PS": "PREFERRED_STOCK"
      }, {
        "RP": "REPURCHASE_AGREEMENT"
      }, {
        "RVRP": "REVERSE_REPURCHASE_AGREEMENT"
      }, {
        "SL": "STUDENT_LOAN_MARKETING_ASSOCIATION"
      }, {
        "TD": "TIME_DEPOSIT"
      }, {
        "USTB": "US_TREASURY_BILL"
      }, {
        "WAR": "WARRANT"
      }, {
        "ZOO": "CATS_TIGERS_LIONS"
      }],
      "169": [{
        "0": "OTHER"
      }, {
        "1": "DTC_SID"
      }, {
        "2": "THOMSON_ALERT"
      }, {
        "3": "A_GLOBAL_CUSTODIAN"
      }],
      "197": [{
        "0": "F_X_NETTING"
      }, {
        "1": "F_X_SWAP"
      }],
      "201": [{
        "0": "PUT"
      }, {
        "1": "CALL"
      }],
      "203": [{
        "0": "COVERED"
      }, {
        "1": "UNCOVERED"
      }],
      "204": [{
        "0": "CUSTOMER"
      }, {
        "1": "FIRM"
      }],
      "208": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "209": [{
        "1": "MATCH"
      }, {
        "2": "FORWARD"
      }, {
        "3": "FORWARD_AND_MATCH"
      }]
    }
  }
};