module.exports = {
  "Version": "FIX.4.2",
  "Header": {
    "8": "BeginString",
    "9": "BodyLength",
    "34": "MsgSeqNum",
    "35": "MsgType",
    "43": "PossDupFlag",
    "49": "SenderCompID",
    "50": "SenderSubID",
    "52": "SendingTime",
    "56": "TargetCompID",
    "57": "TargetSubID",
    "90": "SecureDataLen",
    "91": "SecureData",
    "97": "PossResend",
    "115": "OnBehalfOfCompID",
    "116": "OnBehalfOfSubID",
    "122": "OrigSendingTime",
    "128": "DeliverToCompID",
    "129": "DeliverToSubID",
    "142": "SenderLocationID",
    "143": "TargetLocationID",
    "144": "OnBehalfOfLocationID",
    "145": "DeliverToLocationID",
    "212": "XmlDataLen",
    "213": "XmlData",
    "347": "MessageEncoding",
    "369": "LastMsgSeqNumProcessed",
    "370": "OnBehalfOfSendingTime",
    "Required": ["8", "9", "35", "49", "56", "34", "52"],
    "Optional": ["115", "128", "90", "91", "50", "142", "57", "143", "116", "144", "129", "145", "43", "97", "122", "212", "213", "347", "369", "370"]
  },
  "Trailer": {
    "10": "CheckSum",
    "89": "Signature",
    "93": "SignatureLength",
    "Required": ["10"],
    "Optional": ["93", "89"]
  },
  "Messages": {
    "0": {
      "name": "Heartbeat",
      "msgcat": "admin"
    },
    "1": {
      "name": "TestRequest",
      "msgcat": "admin"
    },
    "2": {
      "name": "ResendRequest",
      "msgcat": "admin"
    },
    "3": {
      "name": "Reject",
      "msgcat": "admin"
    },
    "4": {
      "name": "SequenceReset",
      "msgcat": "admin"
    },
    "5": {
      "name": "Logout",
      "msgcat": "admin"
    },
    "6": {
      "name": "IOI",
      "msgcat": "app"
    },
    "7": {
      "name": "Advertisement",
      "msgcat": "app"
    },
    "8": {
      "name": "ExecutionReport",
      "msgcat": "app"
    },
    "9": {
      "name": "OrderCancelReject",
      "msgcat": "app"
    },
    "A": {
      "name": "Logon",
      "msgcat": "admin"
    },
    "B": {
      "name": "News",
      "msgcat": "app"
    },
    "C": {
      "name": "Email",
      "msgcat": "app"
    },
    "D": {
      "name": "NewOrderSingle",
      "msgcat": "app"
    },
    "E": {
      "name": "NewOrderList",
      "msgcat": "app"
    },
    "F": {
      "name": "OrderCancelRequest",
      "msgcat": "app"
    },
    "G": {
      "name": "OrderCancelReplaceRequest",
      "msgcat": "app"
    },
    "H": {
      "name": "OrderStatusRequest",
      "msgcat": "app"
    },
    "J": {
      "name": "Allocation",
      "msgcat": "app"
    },
    "K": {
      "name": "ListCancelRequest",
      "msgcat": "app"
    },
    "L": {
      "name": "ListExecute",
      "msgcat": "app"
    },
    "M": {
      "name": "ListStatusRequest",
      "msgcat": "app"
    },
    "N": {
      "name": "ListStatus",
      "msgcat": "app"
    },
    "P": {
      "name": "AllocationInstructionAck",
      "msgcat": "app"
    },
    "Q": {
      "name": "DontKnowTrade",
      "msgcat": "app"
    },
    "R": {
      "name": "QuoteRequest",
      "msgcat": "app"
    },
    "S": {
      "name": "Quote",
      "msgcat": "app"
    },
    "T": {
      "name": "SettlementInstructions",
      "msgcat": "app"
    },
    "V": {
      "name": "MarketDataRequest",
      "msgcat": "app"
    },
    "W": {
      "name": "MarketDataSnapshotFullRefresh",
      "msgcat": "app"
    },
    "X": {
      "name": "MarketDataIncrementalRefresh",
      "msgcat": "app"
    },
    "Y": {
      "name": "MarketDataRequestReject",
      "msgcat": "app"
    },
    "Z": {
      "name": "QuoteCancel",
      "msgcat": "app"
    },
    "a": {
      "name": "QuoteStatusRequest",
      "msgcat": "app"
    },
    "b": {
      "name": "QuoteAcknowledgement",
      "msgcat": "app"
    },
    "c": {
      "name": "SecurityDefinitionRequest",
      "msgcat": "app"
    },
    "d": {
      "name": "SecurityDefinition",
      "msgcat": "app"
    },
    "e": {
      "name": "SecurityStatusRequest",
      "msgcat": "app"
    },
    "f": {
      "name": "SecurityStatus",
      "msgcat": "app"
    },
    "g": {
      "name": "TradingSessionStatusRequest",
      "msgcat": "app"
    },
    "h": {
      "name": "TradingSessionStatus",
      "msgcat": "app"
    },
    "i": {
      "name": "MassQuote",
      "msgcat": "app"
    },
    "j": {
      "name": "BusinessMessageReject",
      "msgcat": "app"
    },
    "k": {
      "name": "BidRequest",
      "msgcat": "app"
    },
    "l": {
      "name": "BidResponse",
      "msgcat": "app"
    },
    "m": {
      "name": "ListStrikePrice",
      "msgcat": "app"
    }
  },
  "Fields": {
    "1": "Account",
    "2": "AdvId",
    "3": "AdvRefID",
    "4": "AdvSide",
    "5": "AdvTransType",
    "6": "AvgPx",
    "7": "BeginSeqNo",
    "8": "BeginString",
    "9": "BodyLength",
    "10": "CheckSum",
    "11": "ClOrdID",
    "12": "Commission",
    "13": "CommType",
    "14": "CumQty",
    "15": "Currency",
    "16": "EndSeqNo",
    "17": "ExecID",
    "18": "ExecInst",
    "19": "ExecRefID",
    "20": "ExecTransType",
    "21": "HandlInst",
    "22": "IDSource",
    "23": "IOIid",
    "24": "IOIOthSvc",
    "25": "IOIQltyInd",
    "26": "IOIRefID",
    "27": "IOIShares",
    "28": "IOITransType",
    "29": "LastCapacity",
    "30": "LastMkt",
    "31": "LastPx",
    "32": "LastShares",
    "33": "LinesOfText",
    "34": "MsgSeqNum",
    "35": "MsgType",
    "36": "NewSeqNo",
    "37": "OrderID",
    "38": "OrderQty",
    "39": "OrdStatus",
    "40": "OrdType",
    "41": "OrigClOrdID",
    "42": "OrigTime",
    "43": "PossDupFlag",
    "44": "Price",
    "45": "RefSeqNum",
    "46": "RelatdSym",
    "47": "Rule80A",
    "48": "SecurityID",
    "49": "SenderCompID",
    "50": "SenderSubID",
    "51": "SendingDate",
    "52": "SendingTime",
    "53": "Shares",
    "54": "Side",
    "55": "Symbol",
    "56": "TargetCompID",
    "57": "TargetSubID",
    "58": "Text",
    "59": "TimeInForce",
    "60": "TransactTime",
    "61": "Urgency",
    "62": "ValidUntilTime",
    "63": "SettlmntTyp",
    "64": "FutSettDate",
    "65": "SymbolSfx",
    "66": "ListID",
    "67": "ListSeqNo",
    "68": "TotNoOrders",
    "69": "ListExecInst",
    "70": "AllocID",
    "71": "AllocTransType",
    "72": "RefAllocID",
    "73": "NoOrders",
    "74": "AvgPrxPrecision",
    "75": "TradeDate",
    "76": "ExecBroker",
    "77": "OpenClose",
    "78": "NoAllocs",
    "79": "AllocAccount",
    "80": "AllocShares",
    "81": "ProcessCode",
    "82": "NoRpts",
    "83": "RptSeq",
    "84": "CxlQty",
    "85": "NoDlvyInst",
    "86": "DlvyInst",
    "87": "AllocStatus",
    "88": "AllocRejCode",
    "89": "Signature",
    "90": "SecureDataLen",
    "91": "SecureData",
    "92": "BrokerOfCredit",
    "93": "SignatureLength",
    "94": "EmailType",
    "95": "RawDataLength",
    "96": "RawData",
    "97": "PossResend",
    "98": "EncryptMethod",
    "99": "StopPx",
    "100": "ExDestination",
    "102": "CxlRejReason",
    "103": "OrdRejReason",
    "104": "IOIQualifier",
    "105": "WaveNo",
    "106": "Issuer",
    "107": "SecurityDesc",
    "108": "HeartBtInt",
    "109": "ClientID",
    "110": "MinQty",
    "111": "MaxFloor",
    "112": "TestReqID",
    "113": "ReportToExch",
    "114": "LocateReqd",
    "115": "OnBehalfOfCompID",
    "116": "OnBehalfOfSubID",
    "117": "QuoteID",
    "118": "NetMoney",
    "119": "SettlCurrAmt",
    "120": "SettlCurrency",
    "121": "ForexReq",
    "122": "OrigSendingTime",
    "123": "GapFillFlag",
    "124": "NoExecs",
    "125": "CxlType",
    "126": "ExpireTime",
    "127": "DKReason",
    "128": "DeliverToCompID",
    "129": "DeliverToSubID",
    "130": "IOINaturalFlag",
    "131": "QuoteReqID",
    "132": "BidPx",
    "133": "OfferPx",
    "134": "BidSize",
    "135": "OfferSize",
    "136": "NoMiscFees",
    "137": "MiscFeeAmt",
    "138": "MiscFeeCurr",
    "139": "MiscFeeType",
    "140": "PrevClosePx",
    "141": "ResetSeqNumFlag",
    "142": "SenderLocationID",
    "143": "TargetLocationID",
    "144": "OnBehalfOfLocationID",
    "145": "DeliverToLocationID",
    "146": "NoRelatedSym",
    "147": "Subject",
    "148": "Headline",
    "149": "URLLink",
    "150": "ExecType",
    "151": "LeavesQty",
    "152": "CashOrderQty",
    "153": "AllocAvgPx",
    "154": "AllocNetMoney",
    "155": "SettlCurrFxRate",
    "156": "SettlCurrFxRateCalc",
    "157": "NumDaysInterest",
    "158": "AccruedInterestRate",
    "159": "AccruedInterestAmt",
    "160": "SettlInstMode",
    "161": "AllocText",
    "162": "SettlInstID",
    "163": "SettlInstTransType",
    "164": "EmailThreadID",
    "165": "SettlInstSource",
    "166": "SettlLocation",
    "167": "SecurityType",
    "168": "EffectiveTime",
    "169": "StandInstDbType",
    "170": "StandInstDbName",
    "171": "StandInstDbID",
    "172": "SettlDeliveryType",
    "173": "SettlDepositoryCode",
    "174": "SettlBrkrCode",
    "175": "SettlInstCode",
    "176": "SecuritySettlAgentName",
    "177": "SecuritySettlAgentCode",
    "178": "SecuritySettlAgentAcctNum",
    "179": "SecuritySettlAgentAcctName",
    "180": "SecuritySettlAgentContactName",
    "181": "SecuritySettlAgentContactPhone",
    "182": "CashSettlAgentName",
    "183": "CashSettlAgentCode",
    "184": "CashSettlAgentAcctNum",
    "185": "CashSettlAgentAcctName",
    "186": "CashSettlAgentContactName",
    "187": "CashSettlAgentContactPhone",
    "188": "BidSpotRate",
    "189": "BidForwardPoints",
    "190": "OfferSpotRate",
    "191": "OfferForwardPoints",
    "192": "OrderQty2",
    "193": "FutSettDate2",
    "194": "LastSpotRate",
    "195": "LastForwardPoints",
    "196": "AllocLinkID",
    "197": "AllocLinkType",
    "198": "SecondaryOrderID",
    "199": "NoIOIQualifiers",
    "200": "MaturityMonthYear",
    "201": "PutOrCall",
    "202": "StrikePrice",
    "203": "CoveredOrUncovered",
    "204": "CustomerOrFirm",
    "205": "MaturityDay",
    "206": "OptAttribute",
    "207": "SecurityExchange",
    "208": "NotifyBrokerOfCredit",
    "209": "AllocHandlInst",
    "210": "MaxShow",
    "211": "PegDifference",
    "212": "XmlDataLen",
    "213": "XmlData",
    "214": "SettlInstRefID",
    "215": "NoRoutingIDs",
    "216": "RoutingType",
    "217": "RoutingID",
    "218": "SpreadToBenchmark",
    "219": "Benchmark",
    "223": "CouponRate",
    "231": "ContractMultiplier",
    "262": "MDReqID",
    "263": "SubscriptionRequestType",
    "264": "MarketDepth",
    "265": "MDUpdateType",
    "266": "AggregatedBook",
    "267": "NoMDEntryTypes",
    "268": "NoMDEntries",
    "269": "MDEntryType",
    "270": "MDEntryPx",
    "271": "MDEntrySize",
    "272": "MDEntryDate",
    "273": "MDEntryTime",
    "274": "TickDirection",
    "275": "MDMkt",
    "276": "QuoteCondition",
    "277": "TradeCondition",
    "278": "MDEntryID",
    "279": "MDUpdateAction",
    "280": "MDEntryRefID",
    "281": "MDReqRejReason",
    "282": "MDEntryOriginator",
    "283": "LocationID",
    "284": "DeskID",
    "285": "DeleteReason",
    "286": "OpenCloseSettleFlag",
    "287": "SellerDays",
    "288": "MDEntryBuyer",
    "289": "MDEntrySeller",
    "290": "MDEntryPositionNo",
    "291": "FinancialStatus",
    "292": "CorporateAction",
    "293": "DefBidSize",
    "294": "DefOfferSize",
    "295": "NoQuoteEntries",
    "296": "NoQuoteSets",
    "297": "QuoteAckStatus",
    "298": "QuoteCancelType",
    "299": "QuoteEntryID",
    "300": "QuoteRejectReason",
    "301": "QuoteResponseLevel",
    "302": "QuoteSetID",
    "303": "QuoteRequestType",
    "304": "TotQuoteEntries",
    "305": "UnderlyingIDSource",
    "306": "UnderlyingIssuer",
    "307": "UnderlyingSecurityDesc",
    "308": "UnderlyingSecurityExchange",
    "309": "UnderlyingSecurityID",
    "310": "UnderlyingSecurityType",
    "311": "UnderlyingSymbol",
    "312": "UnderlyingSymbolSfx",
    "313": "UnderlyingMaturityMonthYear",
    "314": "UnderlyingMaturityDay",
    "315": "UnderlyingPutOrCall",
    "316": "UnderlyingStrikePrice",
    "317": "UnderlyingOptAttribute",
    "318": "UnderlyingCurrency",
    "319": "RatioQty",
    "320": "SecurityReqID",
    "321": "SecurityRequestType",
    "322": "SecurityResponseID",
    "323": "SecurityResponseType",
    "324": "SecurityStatusReqID",
    "325": "UnsolicitedIndicator",
    "326": "SecurityTradingStatus",
    "327": "HaltReasonChar",
    "328": "InViewOfCommon",
    "329": "DueToRelated",
    "330": "BuyVolume",
    "331": "SellVolume",
    "332": "HighPx",
    "333": "LowPx",
    "334": "Adjustment",
    "335": "TradSesReqID",
    "336": "TradingSessionID",
    "337": "ContraTrader",
    "338": "TradSesMethod",
    "339": "TradSesMode",
    "340": "TradSesStatus",
    "341": "TradSesStartTime",
    "342": "TradSesOpenTime",
    "343": "TradSesPreCloseTime",
    "344": "TradSesCloseTime",
    "345": "TradSesEndTime",
    "346": "NumberOfOrders",
    "347": "MessageEncoding",
    "348": "EncodedIssuerLen",
    "349": "EncodedIssuer",
    "350": "EncodedSecurityDescLen",
    "351": "EncodedSecurityDesc",
    "352": "EncodedListExecInstLen",
    "353": "EncodedListExecInst",
    "354": "EncodedTextLen",
    "355": "EncodedText",
    "356": "EncodedSubjectLen",
    "357": "EncodedSubject",
    "358": "EncodedHeadlineLen",
    "359": "EncodedHeadline",
    "360": "EncodedAllocTextLen",
    "361": "EncodedAllocText",
    "362": "EncodedUnderlyingIssuerLen",
    "363": "EncodedUnderlyingIssuer",
    "364": "EncodedUnderlyingSecurityDescLen",
    "365": "EncodedUnderlyingSecurityDesc",
    "366": "AllocPrice",
    "367": "QuoteSetValidUntilTime",
    "368": "QuoteEntryRejectReason",
    "369": "LastMsgSeqNumProcessed",
    "370": "OnBehalfOfSendingTime",
    "371": "RefTagID",
    "372": "RefMsgType",
    "373": "SessionRejectReason",
    "374": "BidRequestTransType",
    "375": "ContraBroker",
    "376": "ComplianceID",
    "377": "SolicitedFlag",
    "378": "ExecRestatementReason",
    "379": "BusinessRejectRefID",
    "380": "BusinessRejectReason",
    "381": "GrossTradeAmt",
    "382": "NoContraBrokers",
    "383": "MaxMessageSize",
    "384": "NoMsgTypes",
    "385": "MsgDirection",
    "386": "NoTradingSessions",
    "387": "TotalVolumeTraded",
    "388": "DiscretionInst",
    "389": "DiscretionOffset",
    "390": "BidID",
    "391": "ClientBidID",
    "392": "ListName",
    "393": "TotalNumSecurities",
    "394": "BidType",
    "395": "NumTickets",
    "396": "SideValue1",
    "397": "SideValue2",
    "398": "NoBidDescriptors",
    "399": "BidDescriptorType",
    "400": "BidDescriptor",
    "401": "SideValueInd",
    "402": "LiquidityPctLow",
    "403": "LiquidityPctHigh",
    "404": "LiquidityValue",
    "405": "EFPTrackingError",
    "406": "FairValue",
    "407": "OutsideIndexPct",
    "408": "ValueOfFutures",
    "409": "LiquidityIndType",
    "410": "WtAverageLiquidity",
    "411": "ExchangeForPhysical",
    "412": "OutMainCntryUIndex",
    "413": "CrossPercent",
    "414": "ProgRptReqs",
    "415": "ProgPeriodInterval",
    "416": "IncTaxInd",
    "417": "NumBidders",
    "418": "TradeType",
    "419": "BasisPxType",
    "420": "NoBidComponents",
    "421": "Country",
    "422": "TotNoStrikes",
    "423": "PriceType",
    "424": "DayOrderQty",
    "425": "DayCumQty",
    "426": "DayAvgPx",
    "427": "GTBookingInst",
    "428": "NoStrikes",
    "429": "ListStatusType",
    "430": "NetGrossInd",
    "431": "ListOrderStatus",
    "432": "ExpireDate",
    "433": "ListExecInstType",
    "434": "CxlRejResponseTo",
    "435": "UnderlyingCouponRate",
    "436": "UnderlyingContractMultiplier",
    "437": "ContraTradeQty",
    "438": "ContraTradeTime",
    "439": "ClearingFirm",
    "440": "ClearingAccount",
    "441": "LiquidityNumSecurities",
    "442": "MultiLegReportingType",
    "443": "StrikeTime",
    "444": "ListStatusText",
    "445": "EncodedListStatusTextLen",
    "446": "EncodedListStatusText",
    "HasValue": ["4", "5", "13", "18", "20", "21", "22", "25", "27", "28", "29", "35", "39", "40", "43", "47", "54", "59", "61", "63", "71", "77", "81", "87", "88", "94", "97", "98", "102", "103", "104", "113", "114", "121", "123", "127", "130", "139", "141", "150", "156", "160", "163", "165", "166", "167", "169", "197", "201", "203", "204", "208", "209", "216", "219", "263", "265", "266", "269", "274", "276", "277", "279", "281", "285", "286", "291", "292", "297", "298", "300", "301", "303", "321", "323", "325", "326", "327", "328", "329", "334", "338", "339", "340", "347", "368", "373", "374", "377", "378", "380", "385", "388", "409", "411", "414", "416", "418", "419", "423", "427", "430", "433", "434", "442"],
    "ValueDictionary": {
      "4": [{
        "B": "BUY"
      }, {
        "S": "SELL"
      }, {
        "T": "TRADE"
      }, {
        "X": "CROSS"
      }],
      "5": [{
        "C": "CANCEL"
      }, {
        "N": "NEW"
      }, {
        "R": "REPLACE"
      }],
      "13": [{
        "1": "PER_SHARE"
      }, {
        "2": "PERCENTAGE"
      }, {
        "3": "ABSOLUTE"
      }],
      "18": [{
        "0": "STAY_ON_OFFERSIDE"
      }, {
        "1": "NOT_HELD"
      }, {
        "2": "WORK"
      }, {
        "3": "GO_ALONG"
      }, {
        "4": "OVER_THE_DAY"
      }, {
        "5": "HELD"
      }, {
        "6": "PARTICIPATE_DONT_INITIATE"
      }, {
        "7": "STRICT_SCALE"
      }, {
        "8": "TRY_TO_SCALE"
      }, {
        "9": "STAY_ON_BIDSIDE"
      }, {
        "A": "NO_CROSS"
      }, {
        "B": "OK_TO_CROSS"
      }, {
        "C": "CALL_FIRST"
      }, {
        "D": "PERCENT_OF_VOLUME"
      }, {
        "E": "DO_NOT_INCREASE"
      }, {
        "F": "DO_NOT_REDUCE"
      }, {
        "G": "ALL_OR_NONE"
      }, {
        "I": "INSTITUTIONS_ONLY"
      }, {
        "L": "LAST_PEG"
      }, {
        "M": "MID_PRICE_PEG"
      }, {
        "N": "NON_NEGOTIABLE"
      }, {
        "O": "OPENING_PEG"
      }, {
        "P": "MARKET_PEG"
      }, {
        "R": "PRIMARY_PEG"
      }, {
        "S": "SUSPEND"
      }, {
        "T": "FIXED_PEG_TO_LOCAL_BEST_BID_OR_OFFER_AT_TIME_OF_ORDER"
      }, {
        "U": "CUSTOMER_DISPLAY_INSTRUCTION"
      }, {
        "V": "NETTING"
      }, {
        "W": "PEG_TO_VWAP"
      }],
      "20": [{
        "0": "NEW"
      }, {
        "1": "CANCEL"
      }, {
        "2": "CORRECT"
      }, {
        "3": "STATUS"
      }],
      "21": [{
        "1": "AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION"
      }, {
        "2": "AUTOMATED_EXECUTION_ORDER_PUBLIC_BROKER_INTERVENTION_OK"
      }, {
        "3": "MANUAL_ORDER_BEST_EXECUTION"
      }],
      "22": [{
        "1": "CUSIP"
      }, {
        "2": "SEDOL"
      }, {
        "3": "QUIK"
      }, {
        "4": "ISIN_NUMBER"
      }, {
        "5": "RIC_CODE"
      }, {
        "6": "ISO_CURRENCY_CODE"
      }, {
        "7": "ISO_COUNTRY_CODE"
      }, {
        "8": "EXCHANGE_SYMBOL"
      }, {
        "9": "CONSOLIDATED_TAPE_ASSOCIATION"
      }],
      "25": [{
        "H": "HIGH"
      }, {
        "L": "LOW"
      }, {
        "M": "MEDIUM"
      }],
      "27": [{
        "L": "LARGE"
      }, {
        "M": "MEDIUM"
      }, {
        "S": "SMALL"
      }],
      "28": [{
        "C": "CANCEL"
      }, {
        "N": "NEW"
      }, {
        "R": "REPLACE"
      }],
      "29": [{
        "1": "AGENT"
      }, {
        "2": "CROSS_AS_AGENT"
      }, {
        "3": "CROSS_AS_PRINCIPAL"
      }, {
        "4": "PRINCIPAL"
      }],
      "35": [{
        "0": "HEARTBEAT"
      }, {
        "1": "TEST_REQUEST"
      }, {
        "2": "RESEND_REQUEST"
      }, {
        "3": "REJECT"
      }, {
        "4": "SEQUENCE_RESET"
      }, {
        "5": "LOGOUT"
      }, {
        "6": "INDICATION_OF_INTEREST"
      }, {
        "7": "ADVERTISEMENT"
      }, {
        "8": "EXECUTION_REPORT"
      }, {
        "9": "ORDER_CANCEL_REJECT"
      }, {
        "a": "QUOTE_STATUS_REQUEST"
      }, {
        "A": "LOGON"
      }, {
        "B": "NEWS"
      }, {
        "b": "QUOTE_ACKNOWLEDGEMENT"
      }, {
        "C": "EMAIL"
      }, {
        "c": "SECURITY_DEFINITION_REQUEST"
      }, {
        "D": "ORDER_SINGLE"
      }, {
        "d": "SECURITY_DEFINITION"
      }, {
        "E": "ORDER_LIST"
      }, {
        "e": "SECURITY_STATUS_REQUEST"
      }, {
        "f": "SECURITY_STATUS"
      }, {
        "F": "ORDER_CANCEL_REQUEST"
      }, {
        "G": "ORDER_CANCEL_REPLACE_REQUEST"
      }, {
        "g": "TRADING_SESSION_STATUS_REQUEST"
      }, {
        "H": "ORDER_STATUS_REQUEST"
      }, {
        "h": "TRADING_SESSION_STATUS"
      }, {
        "i": "MASS_QUOTE"
      }, {
        "j": "BUSINESS_MESSAGE_REJECT"
      }, {
        "J": "ALLOCATION"
      }, {
        "K": "LIST_CANCEL_REQUEST"
      }, {
        "k": "BID_REQUEST"
      }, {
        "l": "BID_RESPONSE"
      }, {
        "L": "LIST_EXECUTE"
      }, {
        "m": "LIST_STRIKE_PRICE"
      }, {
        "M": "LIST_STATUS_REQUEST"
      }, {
        "N": "LIST_STATUS"
      }, {
        "P": "ALLOCATION_ACK"
      }, {
        "Q": "DONT_KNOW_TRADE"
      }, {
        "R": "QUOTE_REQUEST"
      }, {
        "S": "QUOTE"
      }, {
        "T": "SETTLEMENT_INSTRUCTIONS"
      }, {
        "V": "MARKET_DATA_REQUEST"
      }, {
        "W": "MARKET_DATA_SNAPSHOT_FULL_REFRESH"
      }, {
        "X": "MARKET_DATA_INCREMENTAL_REFRESH"
      }, {
        "Y": "MARKET_DATA_REQUEST_REJECT"
      }, {
        "Z": "QUOTE_CANCEL"
      }],
      "39": [{
        "0": "NEW"
      }, {
        "1": "PARTIALLY_FILLED"
      }, {
        "2": "FILLED"
      }, {
        "3": "DONE_FOR_DAY"
      }, {
        "4": "CANCELED"
      }, {
        "5": "REPLACED"
      }, {
        "6": "PENDING_CANCEL"
      }, {
        "7": "STOPPED"
      }, {
        "8": "REJECTED"
      }, {
        "9": "SUSPENDED"
      }, {
        "A": "PENDING_NEW"
      }, {
        "B": "CALCULATED"
      }, {
        "C": "EXPIRED"
      }, {
        "D": "ACCEPTED_FOR_BIDDING"
      }, {
        "E": "PENDING_REPLACE"
      }],
      "40": [{
        "1": "MARKET"
      }, {
        "2": "LIMIT"
      }, {
        "3": "STOP"
      }, {
        "4": "STOP_LIMIT"
      }, {
        "5": "MARKET_ON_CLOSE"
      }, {
        "6": "WITH_OR_WITHOUT"
      }, {
        "7": "LIMIT_OR_BETTER"
      }, {
        "8": "LIMIT_WITH_OR_WITHOUT"
      }, {
        "9": "ON_BASIS"
      }, {
        "A": "ON_CLOSE"
      }, {
        "B": "LIMIT_ON_CLOSE"
      }, {
        "C": "FOREX_C"
      }, {
        "D": "PREVIOUSLY_QUOTED"
      }, {
        "E": "PREVIOUSLY_INDICATED"
      }, {
        "F": "FOREX_F"
      }, {
        "G": "FOREX_G"
      }, {
        "H": "FOREX_H"
      }, {
        "I": "FUNARI"
      }, {
        "P": "PEGGED"
      }],
      "43": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "47": [{
        "A": "AGENCY_SINGLE_ORDER"
      }, {
        "B": "SHORT_EXEMPT_TRANSACTION_B"
      }, {
        "C": "PROGRAM_ORDER_NON_INDEX_ARB_FOR_MEMBER_FIRM_ORG"
      }, {
        "D": "PROGRAM_ORDER_INDEX_ARB_FOR_MEMBER_FIRM_ORG"
      }, {
        "E": "REGISTERED_EQUITY_MARKET_MAKER_TRADES"
      }, {
        "F": "SHORT_EXEMPT_TRANSACTION_F"
      }, {
        "H": "SHORT_EXEMPT_TRANSACTION_H"
      }, {
        "I": "INDIVIDUAL_INVESTOR_SINGLE_ORDER"
      }, {
        "J": "PROGRAM_ORDER_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER"
      }, {
        "K": "PROGRAM_ORDER_NON_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER"
      }, {
        "L": "SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE"
      }, {
        "M": "PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_MEMBER"
      }, {
        "N": "PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_MEMBER"
      }, {
        "O": "COMPETING_DEALER_TRADES_O"
      }, {
        "P": "PRINCIPAL"
      }, {
        "R": "COMPETING_DEALER_TRADES_R"
      }, {
        "S": "SPECIALIST_TRADES"
      }, {
        "T": "COMPETING_DEALER_TRADES_T"
      }, {
        "U": "PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_AGENCY"
      }, {
        "W": "ALL_OTHER_ORDERS_AS_AGENT_FOR_OTHER_MEMBER"
      }, {
        "X": "SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_NOT_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE"
      }, {
        "Y": "PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_AGENCY"
      }, {
        "Z": "SHORT_EXEMPT_TRANSACTION_FOR_NON_MEMBER_COMPETING_MARKET_MAKER"
      }],
      "54": [{
        "1": "BUY"
      }, {
        "2": "SELL"
      }, {
        "3": "BUY_MINUS"
      }, {
        "4": "SELL_PLUS"
      }, {
        "5": "SELL_SHORT"
      }, {
        "6": "SELL_SHORT_EXEMPT"
      }, {
        "7": "UNDISCLOSED"
      }, {
        "8": "CROSS"
      }, {
        "9": "CROSS_SHORT"
      }],
      "59": [{
        "0": "DAY"
      }, {
        "1": "GOOD_TILL_CANCEL"
      }, {
        "2": "AT_THE_OPENING"
      }, {
        "3": "IMMEDIATE_OR_CANCEL"
      }, {
        "4": "FILL_OR_KILL"
      }, {
        "5": "GOOD_TILL_CROSSING"
      }, {
        "6": "GOOD_TILL_DATE"
      }],
      "61": [{
        "0": "NORMAL"
      }, {
        "1": "FLASH"
      }, {
        "2": "BACKGROUND"
      }],
      "63": [{
        "0": "REGULAR"
      }, {
        "1": "CASH"
      }, {
        "2": "NEXT_DAY"
      }, {
        "3": "T_PLUS_2"
      }, {
        "4": "T_PLUS_3"
      }, {
        "5": "T_PLUS_4"
      }, {
        "6": "FUTURE"
      }, {
        "7": "WHEN_ISSUED"
      }, {
        "8": "SELLERS_OPTION"
      }, {
        "9": "T_PLUS_5"
      }],
      "71": [{
        "0": "NEW"
      }, {
        "1": "REPLACE"
      }, {
        "2": "CANCEL"
      }, {
        "3": "PRELIMINARY"
      }, {
        "4": "CALCULATED"
      }, {
        "5": "CALCULATED_WITHOUT_PRELIMINARY"
      }],
      "77": [{
        "C": "CLOSE"
      }, {
        "O": "OPEN"
      }],
      "81": [{
        "0": "REGULAR"
      }, {
        "1": "SOFT_DOLLAR"
      }, {
        "2": "STEP_IN"
      }, {
        "3": "STEP_OUT"
      }, {
        "4": "SOFT_DOLLAR_STEP_IN"
      }, {
        "5": "SOFT_DOLLAR_STEP_OUT"
      }, {
        "6": "PLAN_SPONSOR"
      }],
      "87": [{
        "0": "ACCEPTED"
      }, {
        "1": "REJECTED"
      }, {
        "2": "PARTIAL_ACCEPT"
      }, {
        "3": "RECEIVED"
      }],
      "88": [{
        "0": "UNKNOWN_ACCOUNT"
      }, {
        "1": "INCORRECT_QUANTITY"
      }, {
        "2": "INCORRECT_AVERAGE_PRICE"
      }, {
        "3": "UNKNOWN_EXECUTING_BROKER_MNEMONIC"
      }, {
        "4": "COMMISSION_DIFFERENCE"
      }, {
        "5": "UNKNOWN_ORDERID"
      }, {
        "6": "UNKNOWN_LISTID"
      }, {
        "7": "OTHER"
      }],
      "94": [{
        "0": "NEW"
      }, {
        "1": "REPLY"
      }, {
        "2": "ADMIN_REPLY"
      }],
      "97": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "98": [{
        "0": "NONE"
      }, {
        "1": "PKCS"
      }, {
        "2": "DES"
      }, {
        "3": "PKCS_DES"
      }, {
        "4": "PGP_DES"
      }, {
        "5": "PGP_DES_MD5"
      }, {
        "6": "PEM_DES_MD5"
      }],
      "102": [{
        "0": "TOO_LATE_TO_CANCEL"
      }, {
        "1": "UNKNOWN_ORDER"
      }, {
        "2": "BROKER_OPTION"
      }, {
        "3": "ORDER_ALREADY_IN_PENDING_CANCEL_OR_PENDING_REPLACE_STATUS"
      }],
      "103": [{
        "0": "BROKER_OPTION"
      }, {
        "1": "UNKNOWN_SYMBOL"
      }, {
        "2": "EXCHANGE_CLOSED"
      }, {
        "3": "ORDER_EXCEEDS_LIMIT"
      }, {
        "4": "TOO_LATE_TO_ENTER"
      }, {
        "5": "UNKNOWN_ORDER"
      }, {
        "6": "DUPLICATE_ORDER"
      }, {
        "7": "DUPLICATE_OF_A_VERBALLY_COMMUNICATED_ORDER"
      }, {
        "8": "STALE_ORDER"
      }],
      "104": [{
        "A": "ALL_OR_NONE"
      }, {
        "C": "AT_THE_CLOSE"
      }, {
        "I": "IN_TOUCH_WITH"
      }, {
        "L": "LIMIT"
      }, {
        "M": "MORE_BEHIND"
      }, {
        "O": "AT_THE_OPEN"
      }, {
        "P": "TAKING_A_POSITION"
      }, {
        "Q": "AT_THE_MARKET"
      }, {
        "R": "READY_TO_TRADE"
      }, {
        "S": "PORTFOLIO_SHOW_N"
      }, {
        "T": "THROUGH_THE_DAY"
      }, {
        "V": "VERSUS"
      }, {
        "W": "INDICATION"
      }, {
        "X": "CROSSING_OPPORTUNITY"
      }, {
        "Y": "AT_THE_MIDPOINT"
      }, {
        "Z": "PRE_OPEN"
      }],
      "113": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "114": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "121": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "123": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "127": [{
        "A": "UNKNOWN_SYMBOL"
      }, {
        "B": "WRONG_SIDE"
      }, {
        "C": "QUANTITY_EXCEEDS_ORDER"
      }, {
        "D": "NO_MATCHING_ORDER"
      }, {
        "E": "PRICE_EXCEEDS_LIMIT"
      }, {
        "Z": "OTHER"
      }],
      "130": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "139": [{
        "1": "REGULATORY"
      }, {
        "2": "TAX"
      }, {
        "3": "LOCAL_COMMISSION"
      }, {
        "4": "EXCHANGE_FEES"
      }, {
        "5": "STAMP"
      }, {
        "6": "LEVY"
      }, {
        "7": "OTHER"
      }, {
        "8": "MARKUP"
      }, {
        "9": "CONSUMPTION_TAX"
      }],
      "141": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "150": [{
        "0": "NEW"
      }, {
        "1": "PARTIAL_FILL"
      }, {
        "2": "FILL"
      }, {
        "3": "DONE_FOR_DAY"
      }, {
        "4": "CANCELED"
      }, {
        "5": "REPLACE"
      }, {
        "6": "PENDING_CANCEL"
      }, {
        "7": "STOPPED"
      }, {
        "8": "REJECTED"
      }, {
        "9": "SUSPENDED"
      }, {
        "A": "PENDING_NEW"
      }, {
        "B": "CALCULATED"
      }, {
        "C": "EXPIRED"
      }, {
        "D": "RESTATED"
      }, {
        "E": "PENDING_REPLACE"
      }],
      "156": [{
        "M": "MULTIPLY"
      }, {
        "D": "DIVIDE"
      }],
      "160": [{
        "0": "DEFAULT"
      }, {
        "1": "STANDING_INSTRUCTIONS_PROVIDED"
      }, {
        "2": "SPECIFIC_ALLOCATION_ACCOUNT_OVERRIDING"
      }, {
        "3": "SPECIFIC_ALLOCATION_ACCOUNT_STANDING"
      }],
      "163": [{
        "C": "CANCEL"
      }, {
        "N": "NEW"
      }, {
        "R": "REPLACE"
      }],
      "165": [{
        "1": "BROKERS_INSTRUCTIONS"
      }, {
        "2": "INSTITUTIONS_INSTRUCTIONS"
      }],
      "166": [{
        "CED": "CEDEL"
      }, {
        "DTC": "DEPOSITORY_TRUST_COMPANY"
      }, {
        "EUR": "EUROCLEAR"
      }, {
        "FED": "FEDERAL_BOOK_ENTRY"
      }, {
        "ISO Country Code": "LOCAL_MARKET_SETTLE_LOCATION"
      }, {
        "PNY": "PHYSICAL"
      }, {
        "PTC": "PARTICIPANT_TRUST_COMPANY"
      }],
      "167": [{
        "?": "WILDCARD_ENTRY"
      }, {
        "BA": "BANKERS_ACCEPTANCE"
      }, {
        "CB": "CONVERTIBLE_BOND"
      }, {
        "CD": "CERTIFICATE_OF_DEPOSIT"
      }, {
        "CMO": "COLLATERALIZE_MORTGAGE_OBLIGATION"
      }, {
        "CORP": "CORPORATE_BOND"
      }, {
        "CP": "COMMERCIAL_PAPER"
      }, {
        "CPP": "CORPORATE_PRIVATE_PLACEMENT"
      }, {
        "CS": "COMMON_STOCK"
      }, {
        "FHA": "FEDERAL_HOUSING_AUTHORITY"
      }, {
        "FHL": "FEDERAL_HOME_LOAN"
      }, {
        "FN": "FEDERAL_NATIONAL_MORTGAGE_ASSOCIATION"
      }, {
        "FOR": "FOREIGN_EXCHANGE_CONTRACT"
      }, {
        "FUT": "FUTURE"
      }, {
        "GN": "GOVERNMENT_NATIONAL_MORTGAGE_ASSOCIATION"
      }, {
        "GOVT": "TREASURIES_PLUS_AGENCY_DEBENTURE"
      }, {
        "IET": "MORTGAGE_IOETTE"
      }, {
        "MF": "MUTUAL_FUND"
      }, {
        "MIO": "MORTGAGE_INTEREST_ONLY"
      }, {
        "MPO": "MORTGAGE_PRINCIPAL_ONLY"
      }, {
        "MPP": "MORTGAGE_PRIVATE_PLACEMENT"
      }, {
        "MPT": "MISCELLANEOUS_PASS_THRU"
      }, {
        "MUNI": "MUNICIPAL_BOND"
      }, {
        "NONE": "NO_ISITC_SECURITY_TYPE"
      }, {
        "OPT": "OPTION"
      }, {
        "PS": "PREFERRED_STOCK"
      }, {
        "RP": "REPURCHASE_AGREEMENT"
      }, {
        "RVRP": "REVERSE_REPURCHASE_AGREEMENT"
      }, {
        "SL": "STUDENT_LOAN_MARKETING_ASSOCIATION"
      }, {
        "TD": "TIME_DEPOSIT"
      }, {
        "USTB": "US_TREASURY_BILL"
      }, {
        "WAR": "WARRANT"
      }, {
        "ZOO": "CATS_TIGERS_LIONS"
      }],
      "169": [{
        "0": "OTHER"
      }, {
        "1": "DTC_SID"
      }, {
        "2": "THOMSON_ALERT"
      }, {
        "3": "A_GLOBAL_CUSTODIAN"
      }],
      "197": [{
        "0": "F_X_NETTING"
      }, {
        "1": "F_X_SWAP"
      }],
      "201": [{
        "0": "PUT"
      }, {
        "1": "CALL"
      }],
      "203": [{
        "0": "COVERED"
      }, {
        "1": "UNCOVERED"
      }],
      "204": [{
        "0": "CUSTOMER"
      }, {
        "1": "FIRM"
      }],
      "208": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "209": [{
        "1": "MATCH"
      }, {
        "2": "FORWARD"
      }, {
        "3": "FORWARD_AND_MATCH"
      }],
      "216": [{
        "1": "TARGET_FIRM"
      }, {
        "2": "TARGET_LIST"
      }, {
        "3": "BLOCK_FIRM"
      }, {
        "4": "BLOCK_LIST"
      }],
      "219": [{
        "1": "CURVE"
      }, {
        "2": "5_YR"
      }, {
        "3": "OLD_5"
      }, {
        "4": "10_YR"
      }, {
        "5": "OLD_10"
      }, {
        "6": "30_YR"
      }, {
        "7": "OLD_30"
      }, {
        "8": "3_MO_LIBOR"
      }, {
        "9": "6_MO_LIBOR"
      }],
      "263": [{
        "0": "SNAPSHOT"
      }, {
        "1": "SNAPSHOT_PLUS_UPDATES"
      }, {
        "2": "DISABLE_PREVIOUS_SNAPSHOT_PLUS_UPDATE_REQUEST"
      }],
      "265": [{
        "0": "FULL_REFRESH"
      }, {
        "1": "INCREMENTAL_REFRESH"
      }],
      "266": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "269": [{
        "0": "BID"
      }, {
        "1": "OFFER"
      }, {
        "2": "TRADE"
      }, {
        "3": "INDEX_VALUE"
      }, {
        "4": "OPENING_PRICE"
      }, {
        "5": "CLOSING_PRICE"
      }, {
        "6": "SETTLEMENT_PRICE"
      }, {
        "7": "TRADING_SESSION_HIGH_PRICE"
      }, {
        "8": "TRADING_SESSION_LOW_PRICE"
      }, {
        "9": "TRADING_SESSION_VWAP_PRICE"
      }],
      "274": [{
        "0": "PLUS_TICK"
      }, {
        "1": "ZERO_PLUS_TICK"
      }, {
        "2": "MINUS_TICK"
      }, {
        "3": "ZERO_MINUS_TICK"
      }],
      "276": [{
        "A": "OPEN"
      }, {
        "B": "CLOSED"
      }, {
        "C": "EXCHANGE_BEST"
      }, {
        "D": "CONSOLIDATED_BEST"
      }, {
        "E": "LOCKED"
      }, {
        "F": "CROSSED"
      }, {
        "G": "DEPTH"
      }, {
        "H": "FAST_TRADING"
      }, {
        "I": "NON_FIRM"
      }],
      "277": [{
        "A": "CASH"
      }, {
        "B": "AVERAGE_PRICE_TRADE"
      }, {
        "C": "CASH_TRADE"
      }, {
        "D": "NEXT_DAY"
      }, {
        "E": "OPENING"
      }, {
        "F": "INTRADAY_TRADE_DETAIL"
      }, {
        "G": "RULE_127_TRADE"
      }, {
        "H": "RULE_155_TRADE"
      }, {
        "I": "SOLD_LAST"
      }, {
        "J": "NEXT_DAY_TRADE"
      }, {
        "K": "OPENED"
      }, {
        "L": "SELLER"
      }, {
        "M": "SOLD"
      }, {
        "N": "STOPPED_STOCK"
      }],
      "279": [{
        "0": "NEW"
      }, {
        "1": "CHANGE"
      }, {
        "2": "DELETE"
      }],
      "281": [{
        "0": "UNKNOWN_SYMBOL"
      }, {
        "1": "DUPLICATE_MDREQID"
      }, {
        "2": "INSUFFICIENT_BANDWIDTH"
      }, {
        "3": "INSUFFICIENT_PERMISSIONS"
      }, {
        "4": "UNSUPPORTED_SUBSCRIPTIONREQUESTTYPE"
      }, {
        "5": "UNSUPPORTED_MARKETDEPTH"
      }, {
        "6": "UNSUPPORTED_MDUPDATETYPE"
      }, {
        "7": "UNSUPPORTED_AGGREGATEDBOOK"
      }, {
        "8": "UNSUPPORTED_MDENTRYTYPE"
      }],
      "285": [{
        "0": "CANCELATION"
      }, {
        "1": "ERROR"
      }],
      "286": [{
        "0": "DAILY_OPEN"
      }, {
        "1": "SESSION_OPEN"
      }, {
        "2": "DELIVERY_SETTLEMENT_PRICE"
      }],
      "291": [{}, {}],
      "292": [{
        "A": "EX_DIVIDEND"
      }, {
        "B": "EX_DISTRIBUTION"
      }, {
        "C": "EX_RIGHTS"
      }, {
        "D": "NEW"
      }, {
        "E": "EX_INTEREST"
      }],
      "297": [{
        "0": "ACCEPTED"
      }, {
        "1": "CANCELED_FOR_SYMBOL"
      }, {
        "2": "CANCELED_FOR_SECURITY_TYPE"
      }, {
        "3": "CANCELED_FOR_UNDERLYING"
      }, {
        "4": "CANCELED_ALL"
      }, {
        "5": "REJECTED"
      }],
      "298": [{
        "1": "CANCEL_FOR_SYMBOL"
      }, {
        "2": "CANCEL_FOR_SECURITY_TYPE"
      }, {
        "3": "CANCEL_FOR_UNDERLYING_SYMBOL"
      }, {
        "4": "CANCEL_FOR_ALL_QUOTES"
      }],
      "300": [{
        "1": "UNKNOWN_SYMBOL"
      }, {
        "2": "EXCHANGE"
      }, {
        "3": "QUOTE_REQUEST_EXCEEDS_LIMIT"
      }, {
        "4": "TOO_LATE_TO_ENTER"
      }, {
        "5": "UNKNOWN_QUOTE"
      }, {
        "6": "DUPLICATE_QUOTE"
      }, {
        "7": "INVALID_BID_ASK_SPREAD"
      }, {
        "8": "INVALID_PRICE"
      }, {
        "9": "NOT_AUTHORIZED_TO_QUOTE_SECURITY"
      }],
      "301": [{
        "0": "NO_ACKNOWLEDGEMENT"
      }, {
        "1": "ACKNOWLEDGE_ONLY_NEGATIVE_OR_ERRONEOUS_QUOTES"
      }, {
        "2": "ACKNOWLEDGE_EACH_QUOTE_MESSAGES"
      }],
      "303": [{
        "1": "MANUAL"
      }, {
        "2": "AUTOMATIC"
      }],
      "321": [{
        "0": "REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS"
      }, {
        "1": "REQUEST_SECURITY_IDENTITY_FOR_THE_SPECIFICATIONS_PROVIDED"
      }, {
        "2": "REQUEST_LIST_SECURITY_TYPES"
      }, {
        "3": "REQUEST_LIST_SECURITIES"
      }],
      "323": [{
        "1": "ACCEPT_SECURITY_PROPOSAL_AS_IS"
      }, {
        "2": "ACCEPT_SECURITY_PROPOSAL_WITH_REVISIONS_AS_INDICATED_IN_THE_MESSAGE"
      }, {
        "3": "LIST_OF_SECURITY_TYPES_RETURNED_PER_REQUEST"
      }, {
        "4": "LIST_OF_SECURITIES_RETURNED_PER_REQUEST"
      }, {
        "5": "REJECT_SECURITY_PROPOSAL"
      }, {
        "6": "CAN_NOT_MATCH_SELECTION_CRITERIA"
      }],
      "325": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "326": [{
        "1": "OPENING_DELAY"
      }, {
        "10": "MARKET_ON_CLOSE_IMBALANCE_SELL"
      }, {
        "12": "NO_MARKET_IMBALANCE"
      }, {
        "13": "NO_MARKET_ON_CLOSE_IMBALANCE"
      }, {
        "14": "ITS_PRE_OPENING"
      }, {
        "15": "NEW_PRICE_INDICATION"
      }, {
        "16": "TRADE_DISSEMINATION_TIME"
      }, {
        "17": "READY_TO_TRADE"
      }, {
        "18": "NOT_AVAILABLE_FOR_TRADING"
      }, {
        "19": "NOT_TRADED_ON_THIS_MARKET"
      }, {
        "2": "TRADING_HALT"
      }, {
        "20": "UNKNOWN_OR_INVALID"
      }, {
        "3": "RESUME"
      }, {
        "4": "NO_OPEN_NO_RESUME"
      }, {
        "5": "PRICE_INDICATION"
      }, {
        "6": "TRADING_RANGE_INDICATION"
      }, {
        "7": "MARKET_IMBALANCE_BUY"
      }, {
        "8": "MARKET_IMBALANCE_SELL"
      }, {
        "9": "MARKET_ON_CLOSE_IMBALANCE_BUY"
      }],
      "327": [{
        "D": "NEWS_DISSEMINATION"
      }, {
        "E": "ORDER_INFLUX"
      }, {
        "I": "ORDER_IMBALANCE"
      }, {
        "M": "ADDITIONAL_INFORMATION"
      }, {
        "P": "NEWS_PENDING"
      }, {
        "X": "EQUIPMENT_CHANGEOVER"
      }],
      "328": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "329": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "334": [{
        "1": "CANCEL"
      }, {
        "2": "ERROR"
      }, {
        "3": "CORRECTION"
      }],
      "338": [{
        "1": "ELECTRONIC"
      }, {
        "2": "OPEN_OUTCRY"
      }, {
        "3": "TWO_PARTY"
      }],
      "339": [{
        "1": "TESTING"
      }, {
        "2": "SIMULATED"
      }, {
        "3": "PRODUCTION"
      }],
      "340": [{
        "1": "HALTED"
      }, {
        "2": "OPEN"
      }, {
        "3": "CLOSED"
      }, {
        "4": "PRE_OPEN"
      }, {
        "5": "PRE_CLOSE"
      }],
      "347": [{
        "EUC-JP": "EUC_JP"
      }, {
        "ISO-2022-JP": "ISO_2022_JP"
      }, {
        "SHIFT_JIS": "SHIFT_JIS"
      }, {
        "UTF-8": "UTF_8"
      }],
      "368": [{
        "1": "UNKNOWN_SYMBOL"
      }, {
        "2": "EXCHANGE"
      }, {
        "3": "QUOTE_EXCEEDS_LIMIT"
      }, {
        "4": "TOO_LATE_TO_ENTER"
      }, {
        "5": "UNKNOWN_QUOTE"
      }, {
        "6": "DUPLICATE_QUOTE"
      }, {
        "7": "INVALID_BID_ASK_SPREAD"
      }, {
        "8": "INVALID_PRICE"
      }, {
        "9": "NOT_AUTHORIZED_TO_QUOTE_SECURITY"
      }],
      "373": [{
        "0": "INVALID_TAG_NUMBER"
      }, {
        "1": "REQUIRED_TAG_MISSING"
      }, {
        "10": "SENDINGTIME_ACCURACY_PROBLEM"
      }, {
        "11": "INVALID_MSGTYPE"
      }, {
        "2": "TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE"
      }, {
        "3": "UNDEFINED_TAG"
      }, {
        "4": "TAG_SPECIFIED_WITHOUT_A_VALUE"
      }, {
        "5": "VALUE_IS_INCORRECT"
      }, {
        "6": "INCORRECT_DATA_FORMAT_FOR_VALUE"
      }, {
        "7": "DECRYPTION_PROBLEM"
      }, {
        "8": "SIGNATURE_PROBLEM"
      }, {
        "9": "COMPID_PROBLEM"
      }],
      "374": [{
        "C": "CANCEL"
      }, {
        "N": "NO"
      }],
      "377": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "378": [{
        "0": "GT_CORPORATE_ACTION"
      }, {
        "1": "GT_RENEWAL"
      }, {
        "2": "VERBAL_CHANGE"
      }, {
        "3": "REPRICING_OF_ORDER"
      }, {
        "4": "BROKER_OPTION"
      }, {
        "5": "PARTIAL_DECLINE_OF_ORDERQTY"
      }],
      "380": [{
        "0": "OTHER"
      }, {
        "1": "UNKOWN_ID"
      }, {
        "2": "UNKNOWN_SECURITY"
      }, {
        "3": "UNSUPPORTED_MESSAGE_TYPE"
      }, {
        "4": "APPLICATION_NOT_AVAILABLE"
      }, {
        "5": "CONDITIONALLY_REQUIRED_FIELD_MISSING"
      }],
      "385": [{
        "R": "RECEIVE"
      }, {
        "S": "SEND"
      }],
      "388": [{
        "0": "RELATED_TO_DISPLAYED_PRICE"
      }, {
        "1": "RELATED_TO_MARKET_PRICE"
      }, {
        "2": "RELATED_TO_PRIMARY_PRICE"
      }, {
        "3": "RELATED_TO_LOCAL_PRIMARY_PRICE"
      }, {
        "4": "RELATED_TO_MIDPOINT_PRICE"
      }, {
        "5": "RELATED_TO_LAST_TRADE_PRICE"
      }],
      "409": [{
        "1": "5_DAY_MOVING_AVERAGE"
      }, {
        "2": "20_DAY_MOVING_AVERAGE"
      }, {
        "3": "NORMAL_MARKET_SIZE"
      }, {
        "4": "OTHER"
      }],
      "411": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "414": [{
        "1": "BUYSIDE_EXPLICITLY_REQUESTS_STATUS_USING_STATUSREQUEST"
      }, {
        "2": "SELLSIDE_PERIODICALLY_SENDS_STATUS_USING_LISTSTATUS_PERIOD_OPTIONALLY_SPECIFIED_IN_PROGRESSPERIOD"
      }, {
        "3": "REAL_TIME_EXECUTION_REPORTS"
      }],
      "416": [{
        "1": "NET"
      }, {
        "2": "GROSS"
      }],
      "418": [{
        "A": "AGENCY"
      }, {
        "G": "VWAP_GUARANTEE"
      }, {
        "J": "GUARANTEED_CLOSE"
      }, {
        "R": "RISK_TRADE"
      }],
      "419": [{
        "2": "CLOSING_PRICE_AT_MORNING_SESSION"
      }, {
        "3": "CLOSING_PRICE"
      }, {
        "4": "CURRENT_PRICE"
      }, {
        "5": "SQ"
      }, {
        "6": "VWAP_THROUGH_A_DAY"
      }, {
        "7": "VWAP_THROUGH_A_MORNING_SESSION"
      }, {
        "8": "VWAP_THROUGH_AN_AFTERNOON_SESSION"
      }, {
        "9": "VWAP_THROUGH_A_DAY_EXCEPT_YORI"
      }, {
        "A": "VWAP_THROUGH_A_MORNING_SESSION_EXCEPT_YORI"
      }, {
        "B": "VWAP_THROUGH_AN_AFTERNOON_SESSION_EXCEPT_YORI"
      }, {
        "C": "STRIKE"
      }, {
        "D": "OPEN"
      }, {
        "Z": "OTHERS"
      }],
      "423": [{
        "1": "PERCENTAGE"
      }, {
        "2": "PER_SHARE"
      }, {
        "3": "FIXED_AMOUNT"
      }],
      "427": [{
        "0": "BOOK_OUT_ALL_TRADES_ON_DAY_OF_EXECUTION"
      }, {
        "1": "ACCUMULATE_EXECUTIONS_UNTIL_ORDER_IS_FILLED_OR_EXPIRES"
      }, {
        "2": "ACCUMULATE_UNTIL_VERBALLY_NOTIFIED_OTHERWISE"
      }],
      "430": [{
        "1": "NET"
      }, {
        "2": "GROSS"
      }],
      "433": [{
        "1": "IMMEDIATE"
      }, {
        "2": "WAIT_FOR_EXECUTE_INSTRUCTION"
      }],
      "434": [{
        "1": "ORDER_CANCEL_REQUEST"
      }, {
        "2": "ORDER_CANCEL_REPLACE_REQUEST"
      }],
      "442": [{
        "1": "SINGLE_SECURITY"
      }, {
        "2": "INDIVIDUAL_LEG_OF_A_MULTI_LEG_SECURITY"
      }, {
        "3": "MULTI_LEG_SECURITY"
      }]
    }
  }
};