module.exports = {
  "Version": "FIX.4.3",
  "Header": {
    "8": "BeginString",
    "9": "BodyLength",
    "34": "MsgSeqNum",
    "35": "MsgType",
    "43": "PossDupFlag",
    "49": "SenderCompID",
    "50": "SenderSubID",
    "52": "SendingTime",
    "56": "TargetCompID",
    "57": "TargetSubID",
    "90": "SecureDataLen",
    "91": "SecureData",
    "97": "PossResend",
    "115": "OnBehalfOfCompID",
    "116": "OnBehalfOfSubID",
    "122": "OrigSendingTime",
    "128": "DeliverToCompID",
    "129": "DeliverToSubID",
    "142": "SenderLocationID",
    "143": "TargetLocationID",
    "144": "OnBehalfOfLocationID",
    "145": "DeliverToLocationID",
    "212": "XmlDataLen",
    "213": "XmlData",
    "347": "MessageEncoding",
    "369": "LastMsgSeqNumProcessed",
    "370": "OnBehalfOfSendingTime",
    "Required": ["8", "9", "35", "49", "56", "34", "52"],
    "Optional": ["115", "128", "90", "91", "50", "142", "57", "143", "116", "144", "129", "145", "43", "97", "122", "212", "213", "347", "369", "370"]
  },
  "Trailer": {
    "10": "CheckSum",
    "89": "Signature",
    "93": "SignatureLength",
    "Required": ["10"],
    "Optional": ["93", "89"]
  },
  "Messages": {
    "0": {
      "name": "Heartbeat",
      "msgcat": "admin"
    },
    "1": {
      "name": "TestRequest",
      "msgcat": "admin"
    },
    "2": {
      "name": "ResendRequest",
      "msgcat": "admin"
    },
    "3": {
      "name": "Reject",
      "msgcat": "admin"
    },
    "4": {
      "name": "SequenceReset",
      "msgcat": "admin"
    },
    "5": {
      "name": "Logout",
      "msgcat": "admin"
    },
    "6": {
      "name": "IOI",
      "msgcat": "app"
    },
    "7": {
      "name": "Advertisement",
      "msgcat": "app"
    },
    "8": {
      "name": "ExecutionReport",
      "msgcat": "app"
    },
    "9": {
      "name": "OrderCancelReject",
      "msgcat": "app"
    },
    "A": {
      "name": "Logon",
      "msgcat": "admin"
    },
    "B": {
      "name": "News",
      "msgcat": "app"
    },
    "C": {
      "name": "Email",
      "msgcat": "app"
    },
    "D": {
      "name": "NewOrderSingle",
      "msgcat": "app"
    },
    "E": {
      "name": "NewOrderList",
      "msgcat": "app"
    },
    "F": {
      "name": "OrderCancelRequest",
      "msgcat": "app"
    },
    "G": {
      "name": "OrderCancelReplaceRequest",
      "msgcat": "app"
    },
    "H": {
      "name": "OrderStatusRequest",
      "msgcat": "app"
    },
    "J": {
      "name": "Allocation",
      "msgcat": "app"
    },
    "K": {
      "name": "ListCancelRequest",
      "msgcat": "app"
    },
    "L": {
      "name": "ListExecute",
      "msgcat": "app"
    },
    "M": {
      "name": "ListStatusRequest",
      "msgcat": "app"
    },
    "N": {
      "name": "ListStatus",
      "msgcat": "app"
    },
    "P": {
      "name": "AllocationAck",
      "msgcat": "app"
    },
    "Q": {
      "name": "DontKnowTrade",
      "msgcat": "app"
    },
    "R": {
      "name": "QuoteRequest",
      "msgcat": "app"
    },
    "S": {
      "name": "Quote",
      "msgcat": "app"
    },
    "T": {
      "name": "SettlementInstructions",
      "msgcat": "app"
    },
    "V": {
      "name": "MarketDataRequest",
      "msgcat": "app"
    },
    "W": {
      "name": "MarketDataSnapshotFullRefresh",
      "msgcat": "app"
    },
    "X": {
      "name": "MarketDataIncrementalRefresh",
      "msgcat": "app"
    },
    "Y": {
      "name": "MarketDataRequestReject",
      "msgcat": "app"
    },
    "Z": {
      "name": "QuoteCancel",
      "msgcat": "app"
    },
    "a": {
      "name": "QuoteStatusRequest",
      "msgcat": "app"
    },
    "b": {
      "name": "MassQuoteAcknowledgement",
      "msgcat": "app"
    },
    "c": {
      "name": "SecurityDefinitionRequest",
      "msgcat": "app"
    },
    "d": {
      "name": "SecurityDefinition",
      "msgcat": "app"
    },
    "e": {
      "name": "SecurityStatusRequest",
      "msgcat": "app"
    },
    "f": {
      "name": "SecurityStatus",
      "msgcat": "app"
    },
    "g": {
      "name": "TradingSessionStatusRequest",
      "msgcat": "app"
    },
    "h": {
      "name": "TradingSessionStatus",
      "msgcat": "app"
    },
    "i": {
      "name": "MassQuote",
      "msgcat": "app"
    },
    "j": {
      "name": "BusinessMessageReject",
      "msgcat": "app"
    },
    "k": {
      "name": "BidRequest",
      "msgcat": "app"
    },
    "l": {
      "name": "BidResponse",
      "msgcat": "app"
    },
    "m": {
      "name": "ListStrikePrice",
      "msgcat": "app"
    },
    "n": {
      "name": "XMLnonFIX",
      "msgcat": "admin"
    },
    "o": {
      "name": "RegistrationInstructions",
      "msgcat": "app"
    },
    "p": {
      "name": "RegistrationInstructionsResponse",
      "msgcat": "app"
    },
    "q": {
      "name": "OrderMassCancelRequest",
      "msgcat": "app"
    },
    "r": {
      "name": "OrderMassCancelReport",
      "msgcat": "app"
    },
    "s": {
      "name": "NewOrderCross",
      "msgcat": "app"
    },
    "u": {
      "name": "CrossOrderCancelRequest",
      "msgcat": "app"
    },
    "t": {
      "name": "CrossOrderCancelReplaceRequest",
      "msgcat": "app"
    },
    "v": {
      "name": "SecurityTypeRequest",
      "msgcat": "app"
    },
    "w": {
      "name": "SecurityTypes",
      "msgcat": "app"
    },
    "x": {
      "name": "SecurityListRequest",
      "msgcat": "app"
    },
    "y": {
      "name": "SecurityList",
      "msgcat": "app"
    },
    "z": {
      "name": "DerivativeSecurityListRequest",
      "msgcat": "app"
    },
    "AA": {
      "name": "DerivativeSecurityList",
      "msgcat": "app"
    },
    "AB": {
      "name": "NewOrderMultileg",
      "msgcat": "app"
    },
    "AC": {
      "name": "MultilegOrderCancelReplaceRequest",
      "msgcat": "app"
    },
    "AD": {
      "name": "TradeCaptureReportRequest",
      "msgcat": "app"
    },
    "AE": {
      "name": "TradeCaptureReport",
      "msgcat": "app"
    },
    "AF": {
      "name": "OrderMassStatusRequest",
      "msgcat": "app"
    },
    "AG": {
      "name": "QuoteRequestReject",
      "msgcat": "app"
    },
    "AH": {
      "name": "RFQRequest",
      "msgcat": "app"
    },
    "AI": {
      "name": "QuoteStatusReport",
      "msgcat": "app"
    }
  },
  "Fields": {
    "1": "Account",
    "2": "AdvId",
    "3": "AdvRefID",
    "4": "AdvSide",
    "5": "AdvTransType",
    "6": "AvgPx",
    "7": "BeginSeqNo",
    "8": "BeginString",
    "9": "BodyLength",
    "10": "CheckSum",
    "11": "ClOrdID",
    "12": "Commission",
    "13": "CommType",
    "14": "CumQty",
    "15": "Currency",
    "16": "EndSeqNo",
    "17": "ExecID",
    "18": "ExecInst",
    "19": "ExecRefID",
    "21": "HandlInst",
    "22": "SecurityIDSource",
    "23": "IOIid",
    "25": "IOIQltyInd",
    "26": "IOIRefID",
    "27": "IOIQty",
    "28": "IOITransType",
    "29": "LastCapacity",
    "30": "LastMkt",
    "31": "LastPx",
    "32": "LastQty",
    "33": "LinesOfText",
    "34": "MsgSeqNum",
    "35": "MsgType",
    "36": "NewSeqNo",
    "37": "OrderID",
    "38": "OrderQty",
    "39": "OrdStatus",
    "40": "OrdType",
    "41": "OrigClOrdID",
    "42": "OrigTime",
    "43": "PossDupFlag",
    "44": "Price",
    "45": "RefSeqNum",
    "47": "Rule80A",
    "48": "SecurityID",
    "49": "SenderCompID",
    "50": "SenderSubID",
    "52": "SendingTime",
    "53": "Quantity",
    "54": "Side",
    "55": "Symbol",
    "56": "TargetCompID",
    "57": "TargetSubID",
    "58": "Text",
    "59": "TimeInForce",
    "60": "TransactTime",
    "61": "Urgency",
    "62": "ValidUntilTime",
    "63": "SettlmntTyp",
    "64": "FutSettDate",
    "65": "SymbolSfx",
    "66": "ListID",
    "67": "ListSeqNo",
    "68": "TotNoOrders",
    "69": "ListExecInst",
    "70": "AllocID",
    "71": "AllocTransType",
    "72": "RefAllocID",
    "73": "NoOrders",
    "74": "AvgPrxPrecision",
    "75": "TradeDate",
    "77": "PositionEffect",
    "78": "NoAllocs",
    "79": "AllocAccount",
    "80": "AllocQty",
    "81": "ProcessCode",
    "82": "NoRpts",
    "83": "RptSeq",
    "84": "CxlQty",
    "87": "AllocStatus",
    "88": "AllocRejCode",
    "89": "Signature",
    "90": "SecureDataLen",
    "91": "SecureData",
    "93": "SignatureLength",
    "94": "EmailType",
    "95": "RawDataLength",
    "96": "RawData",
    "97": "PossResend",
    "98": "EncryptMethod",
    "99": "StopPx",
    "100": "ExDestination",
    "102": "CxlRejReason",
    "103": "OrdRejReason",
    "104": "IOIQualifier",
    "106": "Issuer",
    "107": "SecurityDesc",
    "108": "HeartBtInt",
    "110": "MinQty",
    "111": "MaxFloor",
    "112": "TestReqID",
    "113": "ReportToExch",
    "114": "LocateReqd",
    "115": "OnBehalfOfCompID",
    "116": "OnBehalfOfSubID",
    "117": "QuoteID",
    "118": "NetMoney",
    "119": "SettlCurrAmt",
    "120": "SettlCurrency",
    "121": "ForexReq",
    "122": "OrigSendingTime",
    "123": "GapFillFlag",
    "124": "NoExecs",
    "126": "ExpireTime",
    "127": "DKReason",
    "128": "DeliverToCompID",
    "129": "DeliverToSubID",
    "130": "IOINaturalFlag",
    "131": "QuoteReqID",
    "132": "BidPx",
    "133": "OfferPx",
    "134": "BidSize",
    "135": "OfferSize",
    "136": "NoMiscFees",
    "137": "MiscFeeAmt",
    "138": "MiscFeeCurr",
    "139": "MiscFeeType",
    "140": "PrevClosePx",
    "141": "ResetSeqNumFlag",
    "142": "SenderLocationID",
    "143": "TargetLocationID",
    "144": "OnBehalfOfLocationID",
    "145": "DeliverToLocationID",
    "146": "NoRelatedSym",
    "147": "Subject",
    "148": "Headline",
    "149": "URLLink",
    "150": "ExecType",
    "151": "LeavesQty",
    "152": "CashOrderQty",
    "153": "AllocAvgPx",
    "154": "AllocNetMoney",
    "155": "SettlCurrFxRate",
    "156": "SettlCurrFxRateCalc",
    "157": "NumDaysInterest",
    "158": "AccruedInterestRate",
    "159": "AccruedInterestAmt",
    "160": "SettlInstMode",
    "161": "AllocText",
    "162": "SettlInstID",
    "163": "SettlInstTransType",
    "164": "EmailThreadID",
    "165": "SettlInstSource",
    "167": "SecurityType",
    "168": "EffectiveTime",
    "169": "StandInstDbType",
    "170": "StandInstDbName",
    "171": "StandInstDbID",
    "172": "SettlDeliveryType",
    "173": "SettlDepositoryCode",
    "174": "SettlBrkrCode",
    "175": "SettlInstCode",
    "176": "SecuritySettlAgentName",
    "177": "SecuritySettlAgentCode",
    "178": "SecuritySettlAgentAcctNum",
    "179": "SecuritySettlAgentAcctName",
    "180": "SecuritySettlAgentContactName",
    "181": "SecuritySettlAgentContactPhone",
    "182": "CashSettlAgentName",
    "183": "CashSettlAgentCode",
    "184": "CashSettlAgentAcctNum",
    "185": "CashSettlAgentAcctName",
    "186": "CashSettlAgentContactName",
    "187": "CashSettlAgentContactPhone",
    "188": "BidSpotRate",
    "189": "BidForwardPoints",
    "190": "OfferSpotRate",
    "191": "OfferForwardPoints",
    "192": "OrderQty2",
    "193": "FutSettDate2",
    "194": "LastSpotRate",
    "195": "LastForwardPoints",
    "196": "AllocLinkID",
    "197": "AllocLinkType",
    "198": "SecondaryOrderID",
    "199": "NoIOIQualifiers",
    "200": "MaturityMonthYear",
    "202": "StrikePrice",
    "203": "CoveredOrUncovered",
    "206": "OptAttribute",
    "207": "SecurityExchange",
    "208": "NotifyBrokerOfCredit",
    "209": "AllocHandlInst",
    "210": "MaxShow",
    "211": "PegDifference",
    "212": "XmlDataLen",
    "213": "XmlData",
    "214": "SettlInstRefID",
    "215": "NoRoutingIDs",
    "216": "RoutingType",
    "217": "RoutingID",
    "218": "Spread",
    "219": "Benchmark",
    "220": "BenchmarkCurveCurrency",
    "221": "BenchmarkCurveName",
    "222": "BenchmarkCurvePoint",
    "223": "CouponRate",
    "224": "CouponPaymentDate",
    "225": "IssueDate",
    "226": "RepurchaseTerm",
    "227": "RepurchaseRate",
    "228": "Factor",
    "229": "TradeOriginationDate",
    "230": "ExDate",
    "231": "ContractMultiplier",
    "232": "NoStipulations",
    "233": "StipulationType",
    "234": "StipulationValue",
    "235": "YieldType",
    "236": "Yield",
    "237": "TotalTakedown",
    "238": "Concession",
    "239": "RepoCollateralSecurityType",
    "240": "RedemptionDate",
    "241": "UnderlyingCouponPaymentDate",
    "242": "UnderlyingIssueDate",
    "243": "UnderlyingRepoCollateralSecurityType",
    "244": "UnderlyingRepurchaseTerm",
    "245": "UnderlyingRepurchaseRate",
    "246": "UnderlyingFactor",
    "247": "UnderlyingRedemptionDate",
    "248": "LegCouponPaymentDate",
    "249": "LegIssueDate",
    "250": "LegRepoCollateralSecurityType",
    "251": "LegRepurchaseTerm",
    "252": "LegRepurchaseRate",
    "253": "LegFactor",
    "254": "LegRedemptionDate",
    "255": "CreditRating",
    "256": "UnderlyingCreditRating",
    "257": "LegCreditRating",
    "258": "TradedFlatSwitch",
    "259": "BasisFeatureDate",
    "260": "BasisFeaturePrice",
    "262": "MDReqID",
    "263": "SubscriptionRequestType",
    "264": "MarketDepth",
    "265": "MDUpdateType",
    "266": "AggregatedBook",
    "267": "NoMDEntryTypes",
    "268": "NoMDEntries",
    "269": "MDEntryType",
    "270": "MDEntryPx",
    "271": "MDEntrySize",
    "272": "MDEntryDate",
    "273": "MDEntryTime",
    "274": "TickDirection",
    "275": "MDMkt",
    "276": "QuoteCondition",
    "277": "TradeCondition",
    "278": "MDEntryID",
    "279": "MDUpdateAction",
    "280": "MDEntryRefID",
    "281": "MDReqRejReason",
    "282": "MDEntryOriginator",
    "283": "LocationID",
    "284": "DeskID",
    "285": "DeleteReason",
    "286": "OpenCloseSettleFlag",
    "287": "SellerDays",
    "288": "MDEntryBuyer",
    "289": "MDEntrySeller",
    "290": "MDEntryPositionNo",
    "291": "FinancialStatus",
    "292": "CorporateAction",
    "293": "DefBidSize",
    "294": "DefOfferSize",
    "295": "NoQuoteEntries",
    "296": "NoQuoteSets",
    "297": "QuoteStatus",
    "298": "QuoteCancelType",
    "299": "QuoteEntryID",
    "300": "QuoteRejectReason",
    "301": "QuoteResponseLevel",
    "302": "QuoteSetID",
    "303": "QuoteRequestType",
    "304": "TotQuoteEntries",
    "305": "UnderlyingSecurityIDSource",
    "306": "UnderlyingIssuer",
    "307": "UnderlyingSecurityDesc",
    "308": "UnderlyingSecurityExchange",
    "309": "UnderlyingSecurityID",
    "310": "UnderlyingSecurityType",
    "311": "UnderlyingSymbol",
    "312": "UnderlyingSymbolSfx",
    "313": "UnderlyingMaturityMonthYear",
    "315": "UnderlyingPutOrCall",
    "316": "UnderlyingStrikePrice",
    "317": "UnderlyingOptAttribute",
    "320": "SecurityReqID",
    "321": "SecurityRequestType",
    "322": "SecurityResponseID",
    "323": "SecurityResponseType",
    "324": "SecurityStatusReqID",
    "325": "UnsolicitedIndicator",
    "326": "SecurityTradingStatus",
    "327": "HaltReasonChar",
    "328": "InViewOfCommon",
    "329": "DueToRelated",
    "330": "BuyVolume",
    "331": "SellVolume",
    "332": "HighPx",
    "333": "LowPx",
    "334": "Adjustment",
    "335": "TradSesReqID",
    "336": "TradingSessionID",
    "337": "ContraTrader",
    "338": "TradSesMethod",
    "339": "TradSesMode",
    "340": "TradSesStatus",
    "341": "TradSesStartTime",
    "342": "TradSesOpenTime",
    "343": "TradSesPreCloseTime",
    "344": "TradSesCloseTime",
    "345": "TradSesEndTime",
    "346": "NumberOfOrders",
    "347": "MessageEncoding",
    "348": "EncodedIssuerLen",
    "349": "EncodedIssuer",
    "350": "EncodedSecurityDescLen",
    "351": "EncodedSecurityDesc",
    "352": "EncodedListExecInstLen",
    "353": "EncodedListExecInst",
    "354": "EncodedTextLen",
    "355": "EncodedText",
    "356": "EncodedSubjectLen",
    "357": "EncodedSubject",
    "358": "EncodedHeadlineLen",
    "359": "EncodedHeadline",
    "360": "EncodedAllocTextLen",
    "361": "EncodedAllocText",
    "362": "EncodedUnderlyingIssuerLen",
    "363": "EncodedUnderlyingIssuer",
    "364": "EncodedUnderlyingSecurityDescLen",
    "365": "EncodedUnderlyingSecurityDesc",
    "366": "AllocPrice",
    "367": "QuoteSetValidUntilTime",
    "368": "QuoteEntryRejectReason",
    "369": "LastMsgSeqNumProcessed",
    "370": "OnBehalfOfSendingTime",
    "371": "RefTagID",
    "372": "RefMsgType",
    "373": "SessionRejectReason",
    "374": "BidRequestTransType",
    "375": "ContraBroker",
    "376": "ComplianceID",
    "377": "SolicitedFlag",
    "378": "ExecRestatementReason",
    "379": "BusinessRejectRefID",
    "380": "BusinessRejectReason",
    "381": "GrossTradeAmt",
    "382": "NoContraBrokers",
    "383": "MaxMessageSize",
    "384": "NoMsgTypes",
    "385": "MsgDirection",
    "386": "NoTradingSessions",
    "387": "TotalVolumeTraded",
    "388": "DiscretionInst",
    "389": "DiscretionOffset",
    "390": "BidID",
    "391": "ClientBidID",
    "392": "ListName",
    "393": "TotalNumSecurities",
    "394": "BidType",
    "395": "NumTickets",
    "396": "SideValue1",
    "397": "SideValue2",
    "398": "NoBidDescriptors",
    "399": "BidDescriptorType",
    "400": "BidDescriptor",
    "401": "SideValueInd",
    "402": "LiquidityPctLow",
    "403": "LiquidityPctHigh",
    "404": "LiquidityValue",
    "405": "EFPTrackingError",
    "406": "FairValue",
    "407": "OutsideIndexPct",
    "408": "ValueOfFutures",
    "409": "LiquidityIndType",
    "410": "WtAverageLiquidity",
    "411": "ExchangeForPhysical",
    "412": "OutMainCntryUIndex",
    "413": "CrossPercent",
    "414": "ProgRptReqs",
    "415": "ProgPeriodInterval",
    "416": "IncTaxInd",
    "417": "NumBidders",
    "418": "TradeType",
    "419": "BasisPxType",
    "420": "NoBidComponents",
    "421": "Country",
    "422": "TotNoStrikes",
    "423": "PriceType",
    "424": "DayOrderQty",
    "425": "DayCumQty",
    "426": "DayAvgPx",
    "427": "GTBookingInst",
    "428": "NoStrikes",
    "429": "ListStatusType",
    "430": "NetGrossInd",
    "431": "ListOrderStatus",
    "432": "ExpireDate",
    "433": "ListExecInstType",
    "434": "CxlRejResponseTo",
    "435": "UnderlyingCouponRate",
    "436": "UnderlyingContractMultiplier",
    "437": "ContraTradeQty",
    "438": "ContraTradeTime",
    "441": "LiquidityNumSecurities",
    "442": "MultiLegReportingType",
    "443": "StrikeTime",
    "444": "ListStatusText",
    "445": "EncodedListStatusTextLen",
    "446": "EncodedListStatusText",
    "447": "PartyIDSource",
    "448": "PartyID",
    "449": "TotalVolumeTradedDate",
    "450": "TotalVolumeTradedTime",
    "451": "NetChgPrevDay",
    "452": "PartyRole",
    "453": "NoPartyIDs",
    "454": "NoSecurityAltID",
    "455": "SecurityAltID",
    "456": "SecurityAltIDSource",
    "457": "NoUnderlyingSecurityAltID",
    "458": "UnderlyingSecurityAltID",
    "459": "UnderlyingSecurityAltIDSource",
    "460": "Product",
    "461": "CFICode",
    "462": "UnderlyingProduct",
    "463": "UnderlyingCFICode",
    "464": "TestMessageIndicator",
    "465": "QuantityType",
    "466": "BookingRefID",
    "467": "IndividualAllocID",
    "468": "RoundingDirection",
    "469": "RoundingModulus",
    "470": "CountryOfIssue",
    "471": "StateOrProvinceOfIssue",
    "472": "LocaleOfIssue",
    "473": "NoRegistDtls",
    "474": "MailingDtls",
    "475": "InvestorCountryOfResidence",
    "476": "PaymentRef",
    "477": "DistribPaymentMethod",
    "478": "CashDistribCurr",
    "479": "CommCurrency",
    "480": "CancellationRights",
    "481": "MoneyLaunderingStatus",
    "482": "MailingInst",
    "483": "TransBkdTime",
    "484": "ExecPriceType",
    "485": "ExecPriceAdjustment",
    "486": "DateOfBirth",
    "487": "TradeReportTransType",
    "488": "CardHolderName",
    "489": "CardNumber",
    "490": "CardExpDate",
    "491": "CardIssNo",
    "492": "PaymentMethod",
    "493": "RegistAcctType",
    "494": "Designation",
    "495": "TaxAdvantageType",
    "496": "RegistRejReasonText",
    "497": "FundRenewWaiv",
    "498": "CashDistribAgentName",
    "499": "CashDistribAgentCode",
    "500": "CashDistribAgentAcctNumber",
    "501": "CashDistribPayRef",
    "503": "CardStartDate",
    "504": "PaymentDate",
    "505": "PaymentRemitterID",
    "506": "RegistStatus",
    "507": "RegistRejReasonCode",
    "508": "RegistRefID",
    "509": "RegistDetls",
    "510": "NoDistribInsts",
    "511": "RegistEmail",
    "512": "DistribPercentage",
    "513": "RegistID",
    "514": "RegistTransType",
    "515": "ExecValuationPoint",
    "516": "OrderPercent",
    "517": "OwnershipType",
    "518": "NoContAmts",
    "519": "ContAmtType",
    "520": "ContAmtValue",
    "521": "ContAmtCurr",
    "522": "OwnerType",
    "523": "PartySubID",
    "524": "NestedPartyID",
    "525": "NestedPartyIDSource",
    "526": "SecondaryClOrdID",
    "527": "SecondaryExecID",
    "528": "OrderCapacity",
    "529": "OrderRestrictions",
    "530": "MassCancelRequestType",
    "531": "MassCancelResponse",
    "532": "MassCancelRejectReason",
    "533": "TotalAffectedOrders",
    "534": "NoAffectedOrders",
    "535": "AffectedOrderID",
    "536": "AffectedSecondaryOrderID",
    "537": "QuoteType",
    "538": "NestedPartyRole",
    "539": "NoNestedPartyIDs",
    "540": "TotalAccruedInterestAmt",
    "541": "MaturityDate",
    "542": "UnderlyingMaturityDate",
    "543": "InstrRegistry",
    "544": "CashMargin",
    "545": "NestedPartySubID",
    "546": "Scope",
    "547": "MDImplicitDelete",
    "548": "CrossID",
    "549": "CrossType",
    "550": "CrossPrioritization",
    "551": "OrigCrossID",
    "552": "NoSides",
    "553": "Username",
    "554": "Password",
    "555": "NoLegs",
    "556": "LegCurrency",
    "557": "TotalNumSecurityTypes",
    "558": "NoSecurityTypes",
    "559": "SecurityListRequestType",
    "560": "SecurityRequestResult",
    "561": "RoundLot",
    "562": "MinTradeVol",
    "563": "MultiLegRptTypeReq",
    "564": "LegPositionEffect",
    "565": "LegCoveredOrUncovered",
    "566": "LegPrice",
    "567": "TradSesStatusRejReason",
    "568": "TradeRequestID",
    "569": "TradeRequestType",
    "570": "PreviouslyReported",
    "571": "TradeReportID",
    "572": "TradeReportRefID",
    "573": "MatchStatus",
    "574": "MatchType",
    "575": "OddLot",
    "576": "NoClearingInstructions",
    "577": "ClearingInstruction",
    "578": "TradeInputSource",
    "579": "TradeInputDevice",
    "580": "NoDates",
    "581": "AccountType",
    "582": "CustOrderCapacity",
    "583": "ClOrdLinkID",
    "584": "MassStatusReqID",
    "585": "MassStatusReqType",
    "586": "OrigOrdModTime",
    "587": "LegSettlmntTyp",
    "588": "LegFutSettDate",
    "589": "DayBookingInst",
    "590": "BookingUnit",
    "591": "PreallocMethod",
    "592": "UnderlyingCountryOfIssue",
    "593": "UnderlyingStateOrProvinceOfIssue",
    "594": "UnderlyingLocaleOfIssue",
    "595": "UnderlyingInstrRegistry",
    "596": "LegCountryOfIssue",
    "597": "LegStateOrProvinceOfIssue",
    "598": "LegLocaleOfIssue",
    "599": "LegInstrRegistry",
    "600": "LegSymbol",
    "601": "LegSymbolSfx",
    "602": "LegSecurityID",
    "603": "LegSecurityIDSource",
    "604": "NoLegSecurityAltID",
    "605": "LegSecurityAltID",
    "606": "LegSecurityAltIDSource",
    "607": "LegProduct",
    "608": "LegCFICode",
    "609": "LegSecurityType",
    "610": "LegMaturityMonthYear",
    "611": "LegMaturityDate",
    "612": "LegStrikePrice",
    "613": "LegOptAttribute",
    "614": "LegContractMultiplier",
    "615": "LegCouponRate",
    "616": "LegSecurityExchange",
    "617": "LegIssuer",
    "618": "EncodedLegIssuerLen",
    "619": "EncodedLegIssuer",
    "620": "LegSecurityDesc",
    "621": "EncodedLegSecurityDescLen",
    "622": "EncodedLegSecurityDesc",
    "623": "LegRatioQty",
    "624": "LegSide",
    "625": "TradingSessionSubID",
    "626": "AllocType",
    "627": "NoHops",
    "628": "HopCompID",
    "629": "HopSendingTime",
    "630": "HopRefID",
    "631": "MidPx",
    "632": "BidYield",
    "633": "MidYield",
    "634": "OfferYield",
    "635": "ClearingFeeIndicator",
    "636": "WorkingIndicator",
    "637": "LegLastPx",
    "638": "PriorityIndicator",
    "639": "PriceImprovement",
    "640": "Price2",
    "641": "LastForwardPoints2",
    "642": "BidForwardPoints2",
    "643": "OfferForwardPoints2",
    "644": "RFQReqID",
    "645": "MktBidPx",
    "646": "MktOfferPx",
    "647": "MinBidSize",
    "648": "MinOfferSize",
    "649": "QuoteStatusReqID",
    "650": "LegalConfirm",
    "651": "UnderlyingLastPx",
    "652": "UnderlyingLastQty",
    "654": "LegRefID",
    "655": "ContraLegRefID",
    "656": "SettlCurrBidFxRate",
    "657": "SettlCurrOfferFxRate",
    "658": "QuoteRequestRejectReason",
    "659": "SideComplianceID",
    "HasValue": ["4", "5", "13", "18", "21", "22", "25", "27", "28", "29", "35", "39", "40", "43", "47", "54", "59", "61", "63", "71", "77", "81", "87", "88", "94", "97", "98", "102", "103", "104", "113", "114", "121", "123", "127", "130", "139", "141", "150", "156", "160", "163", "165", "167", "169", "172", "197", "203", "208", "209", "216", "219", "221", "233", "235", "258", "263", "265", "266", "269", "274", "276", "277", "279", "281", "285", "286", "291", "292", "297", "298", "300", "301", "303", "321", "323", "325", "326", "327", "328", "329", "334", "338", "339", "340", "347", "373", "374", "377", "378", "380", "385", "388", "394", "399", "401", "409", "411", "414", "416", "418", "419", "423", "427", "429", "430", "431", "433", "434", "442", "447", "452", "460", "464", "465", "468", "480", "481", "484", "487", "492", "495", "497", "506", "507", "514", "519", "522", "528", "529", "530", "531", "532", "537", "544", "546", "547", "549", "550", "552", "559", "560", "567", "569", "570", "573", "574", "577", "581", "585", "589", "590", "591", "626", "635", "636", "638", "650", "658"],
    "ValueDictionary": {
      "4": [{
        "B": "BUY"
      }, {
        "S": "SELL"
      }, {
        "X": "CROSS"
      }, {
        "T": "TRADE"
      }],
      "5": [{
        "N": "NEW"
      }, {
        "C": "CANCEL"
      }, {
        "R": "REPLACE"
      }],
      "13": [{
        "6": "PER_BOND"
      }, {
        "1": "PER_SHARE"
      }, {
        "2": "PERCENTAGE"
      }, {
        "3": "ABSOLUTE"
      }, {
        "5": "5"
      }, {
        "4": "4"
      }],
      "18": [{
        "Y": "TRYTOSTOP"
      }, {
        "M": "MIDPRCPEG"
      }, {
        "P": "MARKPEG"
      }, {
        "Q": "CANCELONSYSFAIL"
      }, {
        "R": "PRIMPEG"
      }, {
        "S": "SUSPEND"
      }, {
        "U": "CUSTDISPINST"
      }, {
        "V": "NETTING"
      }, {
        "W": "PEGVWAP"
      }, {
        "X": "TRADEALONG"
      }, {
        "D": "PERCVOL"
      }, {
        "0": "STAYOFFER"
      }, {
        "2": "WORK"
      }, {
        "4": "OVERDAY"
      }, {
        "5": "HELD"
      }, {
        "6": "PARTNOTINIT"
      }, {
        "7": "STRICTSCALE"
      }, {
        "8": "TRYTOSCALE"
      }, {
        "9": "STAYBID"
      }, {
        "A": "NOCROSS"
      }, {
        "O": "OPENPEG"
      }, {
        "C": "CALLFIRST"
      }, {
        "N": "NONNEGO"
      }, {
        "E": "DNI"
      }, {
        "F": "DNR"
      }, {
        "G": "AON"
      }, {
        "H": "RESTATEONSYSFAIL"
      }, {
        "I": "INSTITONLY"
      }, {
        "J": "RESTATEONTRADINGHALT"
      }, {
        "K": "CANCELONTRADINGHALT"
      }, {
        "L": "LASTPEG"
      }, {
        "3": "GOALONG"
      }, {
        "B": "OKCROSS"
      }, {
        "1": "NOTHELD"
      }],
      "21": [{
        "1": "AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION"
      }, {
        "2": "AUTOMATED_EXECUTION_ORDER_PUBLIC_BROKER_INTERVENTION_OK"
      }, {
        "3": "MANUAL_ORDER_BEST_EXECUTION"
      }],
      "22": [{
        "E": "SICOVAM"
      }, {
        "2": "SEDOL"
      }, {
        "1": "CUSIP"
      }, {
        "3": "QUIK"
      }, {
        "F": "BELGIAN"
      }, {
        "D": "VALOREN"
      }, {
        "C": "DUTCH"
      }, {
        "B": "WERTPAPIER"
      }, {
        "A": "BLOOMBERG_SYMBOL"
      }, {
        "9": "CONSOLIDATED_TAPE_ASSOCIATION"
      }, {
        "8": "EXCHANGE_SYMBOL"
      }, {
        "7": "ISO_COUNTRY_CODE"
      }, {
        "6": "ISO_CURRENCY_CODE"
      }, {
        "5": "RIC_CODE"
      }, {
        "4": "ISIN_NUMBER"
      }, {
        "G": "COMMON"
      }],
      "25": [{
        "M": "MEDIUM"
      }, {
        "H": "HIGH"
      }, {
        "L": "LOW"
      }],
      "27": [{
        "L": "LARGE"
      }, {
        "M": "MEDIUM"
      }, {
        "S": "SMALL"
      }],
      "28": [{
        "C": "CANCEL"
      }, {
        "N": "NEW"
      }, {
        "R": "REPLACE"
      }],
      "29": [{
        "4": "PRINCIPAL"
      }, {
        "3": "CROSS_AS_PRINCIPAL"
      }, {
        "1": "AGENT"
      }, {
        "2": "CROSS_AS_AGENT"
      }],
      "35": [{
        "0": "HEARTBEAT"
      }, {
        "1": "TEST_REQUEST"
      }, {
        "2": "RESEND_REQUEST"
      }, {
        "3": "REJECT"
      }, {
        "4": "SEQUENCE_RESET"
      }, {
        "5": "LOGOUT"
      }, {
        "6": "INDICATION_OF_INTEREST"
      }, {
        "7": "ADVERTISEMENT"
      }, {
        "8": "EXECUTION_REPORT"
      }, {
        "9": "ORDER_CANCEL_REJECT"
      }, {
        "a": "QUOTE_STATUS_REQUEST"
      }, {
        "A": "LOGON"
      }, {
        "AA": "DERIVATIVE_SECURITY_LIST"
      }, {
        "AB": "NEW_ORDER_AB"
      }, {
        "AC": "MULTILEG_ORDER_CANCEL_REPLACE"
      }, {
        "AD": "TRADE_CAPTURE_REPORT_REQUEST"
      }, {
        "AE": "TRADE_CAPTURE_REPORT"
      }, {
        "AF": "ORDER_MASS_STATUS_REQUEST"
      }, {
        "AG": "QUOTE_REQUEST_REJECT"
      }, {
        "AH": "RFQ_REQUEST"
      }, {
        "AI": "QUOTE_STATUS_REPORT"
      }, {
        "b": "MASS_QUOTE_ACKNOWLEDGEMENT"
      }, {
        "B": "NEWS"
      }, {
        "c": "SECURITY_DEFINITION_REQUEST"
      }, {
        "C": "EMAIL"
      }, {
        "d": "SECURITY_DEFINITION"
      }, {
        "D": "ORDER_SINGLE"
      }, {
        "e": "SECURITY_STATUS_REQUEST"
      }, {
        "E": "ORDER_LIST"
      }, {
        "f": "SECURITY_STATUS"
      }, {
        "F": "ORDER_CANCEL_REQUEST"
      }, {
        "G": "ORDER_CANCEL_REPLACE_REQUEST"
      }, {
        "g": "TRADING_SESSION_STATUS_REQUEST"
      }, {
        "h": "TRADING_SESSION_STATUS"
      }, {
        "H": "ORDER_STATUS_REQUEST"
      }, {
        "i": "MASS_QUOTE"
      }, {
        "j": "BUSINESS_MESSAGE_REJECT"
      }, {
        "J": "ALLOCATION"
      }, {
        "K": "LIST_CANCEL_REQUEST"
      }, {
        "k": "BID_REQUEST"
      }, {
        "l": "BID_RESPONSE"
      }, {
        "L": "LIST_EXECUTE"
      }, {
        "m": "LIST_STRIKE_PRICE"
      }, {
        "M": "LIST_STATUS_REQUEST"
      }, {
        "N": "LIST_STATUS"
      }, {
        "n": "XML_MESSAGE"
      }, {
        "o": "REGISTRATION_INSTRUCTIONS"
      }, {
        "P": "ALLOCATION_ACK"
      }, {
        "p": "REGISTRATION_INSTRUCTIONS_RESPONSE"
      }, {
        "q": "ORDER_MASS_CANCEL_REQUEST"
      }, {
        "Q": "DONT_KNOW_TRADE"
      }, {
        "r": "ORDER_MASS_CANCEL_REPORT"
      }, {
        "R": "QUOTE_REQUEST"
      }, {
        "s": "NEW_ORDER_s"
      }, {
        "S": "QUOTE"
      }, {
        "t": "CROSS_ORDER_CANCEL_REPLACE_REQUEST"
      }, {
        "T": "SETTLEMENT_INSTRUCTIONS"
      }, {
        "u": "CROSS_ORDER_CANCEL_REQUEST"
      }, {
        "v": "SECURITY_TYPE_REQUEST"
      }, {
        "V": "MARKET_DATA_REQUEST"
      }, {
        "w": "SECURITY_TYPES"
      }, {
        "W": "MARKET_DATA_SNAPSHOT_FULL_REFRESH"
      }, {
        "x": "SECURITY_LIST_REQUEST"
      }, {
        "X": "MARKET_DATA_INCREMENTAL_REFRESH"
      }, {
        "y": "SECURITY_LIST"
      }, {
        "Y": "MARKET_DATA_REQUEST_REJECT"
      }, {
        "z": "DERIVATIVE_SECURITY_LIST_REQUEST"
      }, {
        "Z": "QUOTE_CANCEL"
      }],
      "39": [{
        "0": "NEW"
      }, {
        "1": "PARTIALLY_FILLED"
      }, {
        "5": "REPLACED"
      }, {
        "2": "FILLED"
      }, {
        "6": "PENDING_CANCEL"
      }, {
        "7": "STOPPED"
      }, {
        "8": "REJECTED"
      }, {
        "9": "SUSPENDED"
      }, {
        "A": "PENDING_NEW"
      }, {
        "B": "CALCULATED"
      }, {
        "C": "EXPIRED"
      }, {
        "D": "ACCEPTED_FOR_BIDDING"
      }, {
        "E": "PENDING_REPLACE"
      }, {
        "3": "DONE_FOR_DAY"
      }, {
        "4": "CANCELED"
      }],
      "40": [{
        "D": "PREVIOUSLY_QUOTED"
      }, {
        "2": "LIMIT"
      }, {
        "3": "STOP"
      }, {
        "4": "STOP_LIMIT"
      }, {
        "5": "MARKET_ON_CLOSE"
      }, {
        "6": "WITH_OR_WITHOUT"
      }, {
        "7": "LIMIT_OR_BETTER"
      }, {
        "8": "LIMIT_WITH_OR_WITHOUT"
      }, {
        "9": "ON_BASIS"
      }, {
        "A": "ON_CLOSE"
      }, {
        "1": "MARKET"
      }, {
        "C": "FOREX_C"
      }, {
        "F": "FOREX_F"
      }, {
        "E": "PREVIOUSLY_INDICATED"
      }, {
        "G": "FOREX_G"
      }, {
        "I": "FUNARI"
      }, {
        "J": "MARKET_IF_TOUCHED"
      }, {
        "K": "MARKET_WITH_LEFTOVER_AS_LIMIT"
      }, {
        "L": "PREVIOUS_FUND_VALUATION_POINT"
      }, {
        "M": "NEXT_FUND_VALUATION_POINT"
      }, {
        "P": "PEGGED"
      }, {
        "B": "LIMIT_ON_CLOSE"
      }, {
        "H": "FOREX_H"
      }],
      "43": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "47": [{
        "N": "PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_MEMBER"
      }, {
        "B": "SHORT_EXEMPT_TRANSACTION_B"
      }, {
        "D": "PROGRAM_ORDER_INDEX_ARB_FOR_MEMBER_FIRM_ORG"
      }, {
        "E": "SHORT_EXEMPT_TRANSACTION_FOR_PRINCIPAL"
      }, {
        "F": "SHORT_EXEMPT_TRANSACTION_F"
      }, {
        "H": "SHORT_EXEMPT_TRANSACTION_H"
      }, {
        "I": "INDIVIDUAL_INVESTOR_SINGLE_ORDER"
      }, {
        "J": "PROGRAM_ORDER_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER"
      }, {
        "K": "PROGRAM_ORDER_NON_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER"
      }, {
        "M": "PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_MEMBER"
      }, {
        "A": "AGENCY_SINGLE_ORDER"
      }, {
        "O": "PROPRIETARY_TRANSACTIONS_FOR_COMPETING_MARKET_MAKER_THAT_IS_AFFILIATED_WITH_THE_CLEARING_MEMBER"
      }, {
        "P": "PRINCIPAL"
      }, {
        "R": "TRANSACTIONS_FOR_THE_ACCOUNT_OF_A_NON_MEMBER_COMPETING_MARKET_MAKER"
      }, {
        "S": "SPECIALIST_TRADES"
      }, {
        "T": "TRANSACTIONS_FOR_THE_ACCOUNT_OF_AN_UNAFFILIATED_MEMBERS_COMPETING_MARKET_MAKER"
      }, {
        "U": "PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_AGENCY"
      }, {
        "W": "ALL_OTHER_ORDERS_AS_AGENT_FOR_OTHER_MEMBER"
      }, {
        "X": "SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_NOT_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE"
      }, {
        "Y": "PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_AGENCY"
      }, {
        "Z": "SHORT_EXEMPT_TRANSACTION_FOR_NON_MEMBER_COMPETING_MARKET_MAKER"
      }, {
        "L": "SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE"
      }, {
        "C": "PROGRAM_ORDER_NON_INDEX_ARB_FOR_MEMBER_FIRM_ORG"
      }],
      "54": [{
        "6": "SELL_SHORT_EXEMPT"
      }, {
        "B": "AS_DEFINED"
      }, {
        "C": "OPPOSITE"
      }, {
        "8": "CROSS"
      }, {
        "9": "CROSS_SHORT"
      }, {
        "1": "BUY"
      }, {
        "2": "SELL"
      }, {
        "3": "BUY_MINUS"
      }, {
        "4": "SELL_PLUS"
      }, {
        "A": "CROSS_SHORT_EXEMPT"
      }, {
        "5": "SELL_SHORT"
      }, {
        "7": "UNDISCLOSED"
      }],
      "59": [{
        "7": "AT_THE_CLOSE"
      }, {
        "0": "DAY"
      }, {
        "1": "GOOD_TILL_CANCEL"
      }, {
        "2": "AT_THE_OPENING"
      }, {
        "3": "IMMEDIATE_OR_CANCEL"
      }, {
        "4": "FILL_OR_KILL"
      }, {
        "5": "GOOD_TILL_CROSSING"
      }, {
        "6": "GOOD_TILL_DATE"
      }],
      "61": [{
        "1": "FLASH"
      }, {
        "2": "BACKGROUND"
      }, {
        "0": "NORMAL"
      }],
      "63": [{
        "5": "T_PLUS_4"
      }, {
        "A": "T_PLUS_1"
      }, {
        "6": "FUTURE"
      }, {
        "3": "T_PLUS_2"
      }, {
        "2": "NEXT_DAY"
      }, {
        "8": "SELLERS_OPTION"
      }, {
        "1": "CASH"
      }, {
        "7": "WHEN_AND_IF_ISSUED"
      }, {
        "0": "REGULAR"
      }, {
        "9": "T_PLUS_5"
      }, {
        "4": "T_PLUS_3"
      }],
      "71": [{
        "5": "CALCULATED_WITHOUT_PRELIMINARY"
      }, {
        "4": "CALCULATED"
      }, {
        "3": "PRELIMINARY"
      }, {
        "2": "CANCEL"
      }, {
        "1": "REPLACE"
      }, {
        "0": "NEW"
      }],
      "77": [{
        "F": "FIFO"
      }, {
        "R": "ROLLED"
      }, {
        "C": "CLOSE"
      }, {
        "O": "OPEN"
      }],
      "81": [{
        "6": "PLAN_SPONSOR"
      }, {
        "0": "REGULAR"
      }, {
        "1": "SOFT_DOLLAR"
      }, {
        "2": "STEP_IN"
      }, {
        "3": "STEP_OUT"
      }, {
        "4": "SOFT_DOLLAR_STEP_IN"
      }, {
        "5": "SOFT_DOLLAR_STEP_OUT"
      }],
      "87": [{
        "1": "REJECTED"
      }, {
        "2": "PARTIAL_ACCEPT"
      }, {
        "3": "RECEIVED"
      }, {
        "0": "ACCEPTED"
      }],
      "88": [{
        "0": "UNKNOWN_ACCOUNT"
      }, {
        "6": "UNKNOWN_LISTID"
      }, {
        "3": "UNKNOWN_EXECUTING_BROKER_MNEMONIC"
      }, {
        "5": "UNKNOWN_ORDERID"
      }, {
        "7": "OTHER"
      }, {
        "4": "COMMISSION_DIFFERENCE"
      }, {
        "1": "INCORRECT_QUANTITY"
      }, {
        "2": "INCORRECT_AVERAGE_PRICE"
      }],
      "94": [{
        "0": "NEW"
      }, {
        "1": "REPLY"
      }, {
        "2": "ADMIN_REPLY"
      }],
      "97": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "98": [{
        "2": "DES"
      }, {
        "6": "PEM_DES_MD5"
      }, {
        "5": "PGP_DES_MD5"
      }, {
        "3": "PKCS_DES"
      }, {
        "0": "NONE"
      }, {
        "1": "PKCS"
      }, {
        "4": "PGP_DES"
      }],
      "102": [{
        "1": "UNKNOWN_ORDER"
      }, {
        "0": "TOO_LATE_TO_CANCEL"
      }, {
        "6": "DUPLICATE_CLORDID_RECEIVED"
      }, {
        "5": "ORIGORDMODTIME_DID_NOT_MATCH_LAST_TRANSACTTIME_OF_ORDER"
      }, {
        "4": "UNABLE_TO_PROCESS_ORDER_MASS_CANCEL_REQUEST"
      }, {
        "3": "ORDER_ALREADY_IN_PENDING_CANCEL_OR_PENDING_REPLACE_STATUS"
      }, {
        "2": "BROKER"
      }],
      "103": [{
        "2": "EXCHANGE_CLOSED"
      }, {
        "1": "UNKNOWN_SYMBOL"
      }, {
        "3": "ORDER_EXCEEDS_LIMIT"
      }, {
        "4": "TOO_LATE_TO_ENTER"
      }, {
        "5": "UNKNOWN_ORDER"
      }, {
        "7": "DUPLICATE_OF_A_VERBALLY_COMMUNICATED_ORDER"
      }, {
        "9": "TRADE_ALONG_REQUIRED"
      }, {
        "10": "INVALID_INVESTOR_ID"
      }, {
        "6": "DUPLICATE_ORDER"
      }, {
        "11": "UNSUPPORTED_ORDER_CHARACTERISTIC"
      }, {
        "12": "SURVEILLENCE_OPTION"
      }, {
        "0": "BROKER"
      }, {
        "8": "STALE_ORDER"
      }],
      "104": [{
        "O": "AT_THE_OPEN"
      }, {
        "X": "CROSSING_OPPORTUNITY"
      }, {
        "W": "INDICATION"
      }, {
        "V": "VERSUS"
      }, {
        "T": "THROUGH_THE_DAY"
      }, {
        "S": "PORTFOLIO_SHOWN"
      }, {
        "R": "READY_TO_TRADE"
      }, {
        "A": "ALL_OR_NONE"
      }, {
        "P": "TAKING_A_POSITION"
      }, {
        "M": "MORE_BEHIND"
      }, {
        "L": "LIMIT"
      }, {
        "I": "IN_TOUCH_WITH"
      }, {
        "D": "VWAP"
      }, {
        "C": "AT_THE_CLOSE"
      }, {
        "B": "MARKET_ON_CLOSE"
      }, {
        "Q": "AT_THE_MARKET"
      }, {
        "Y": "AT_THE_MIDPOINT"
      }, {
        "Z": "PRE_OPEN"
      }],
      "113": [{
        "Y": "YES"
      }, {
        "N": "NO"
      }],
      "114": [{
        "Y": "YES"
      }, {
        "N": "NO"
      }],
      "121": [{
        "Y": "YES"
      }, {
        "N": "NO"
      }],
      "123": [{
        "Y": "YES"
      }, {
        "N": "NO"
      }],
      "127": [{
        "B": "WRONG_SIDE"
      }, {
        "C": "QUANTITY_EXCEEDS_ORDER"
      }, {
        "D": "NO_MATCHING_ORDER"
      }, {
        "E": "PRICE_EXCEEDS_LIMIT"
      }, {
        "Z": "OTHER"
      }, {
        "A": "UNKNOWN_SYMBOL"
      }],
      "130": [{
        "Y": "YES"
      }, {
        "N": "NO"
      }],
      "139": [{
        "3": "LOCAL_COMMISSION"
      }, {
        "4": "EXCHANGE_FEES"
      }, {
        "5": "STAMP"
      }, {
        "6": "LEVY"
      }, {
        "7": "OTHER"
      }, {
        "8": "MARKUP"
      }, {
        "9": "CONSUMPTION_TAX"
      }, {
        "1": "REGULATORY"
      }, {
        "2": "TAX"
      }],
      "141": [{
        "Y": "YES"
      }, {
        "N": "NO"
      }],
      "150": [{
        "6": "PENDING_CANCEL"
      }, {
        "0": "NEW"
      }, {
        "1": "PARTIAL_FILL"
      }, {
        "2": "FILL"
      }, {
        "4": "CANCELED"
      }, {
        "5": "REPLACE"
      }, {
        "8": "REJECTED"
      }, {
        "9": "SUSPENDED"
      }, {
        "A": "PENDING_NEW"
      }, {
        "B": "CALCULATED"
      }, {
        "C": "EXPIRED"
      }, {
        "D": "RESTATED"
      }, {
        "E": "PENDING_REPLACE"
      }, {
        "F": "TRADE"
      }, {
        "G": "TRADE_CORRECT"
      }, {
        "H": "TRADE_CANCEL"
      }, {
        "I": "ORDER_STATUS"
      }, {
        "3": "DONE_FOR_DAY"
      }, {
        "7": "STOPPED"
      }],
      "156": [{
        "D": "DIVIDE"
      }, {
        "M": "MULTIPLY"
      }],
      "160": [{
        "0": "DEFAULT"
      }, {
        "4": "SPECIFIC_ORDER_FOR_A_SINGLE_ACCOUNT"
      }, {
        "3": "SPECIFIC_ALLOCATION_ACCOUNT_STANDING"
      }, {
        "1": "STANDING_INSTRUCTIONS_PROVIDED"
      }, {
        "2": "SPECIFIC_ALLOCATION_ACCOUNT_OVERRIDING"
      }],
      "163": [{
        "N": "NEW"
      }, {
        "R": "REPLACE"
      }, {
        "C": "CANCEL"
      }],
      "165": [{
        "2": "INSTITUTIONS_INSTRUCTIONS"
      }, {
        "3": "INVESTOR"
      }, {
        "1": "BROKERS_INSTRUCTIONS"
      }],
      "167": [{
        "CP": "COMMERCIAL_PAPER"
      }, {
        "VRDN": "VARIABLE_RATE_DEMAND_NOTE"
      }, {
        "PZFJ": "PLAZOS_FIJOS"
      }, {
        "PN": "PROMISSORY_NOTE"
      }, {
        "ONITE": "OVERNIGHT"
      }, {
        "MTN": "MEDIUM_TERM_NOTES"
      }, {
        "TECP": "TAX_EXEMPT_COMMERCIAL_PAPER"
      }, {
        "AMENDED": "AMENDED_RESTATED"
      }, {
        "BRIDGE": "BRIDGE_LOAN"
      }, {
        "LOFC": "LETTER_OF_CREDIT"
      }, {
        "SWING": "SWING_LINE_FACILITY"
      }, {
        "DINP": "DEBTOR_IN_POSSESSION"
      }, {
        "DEFLTED": "DEFAULTED"
      }, {
        "WITHDRN": "WITHDRAWN"
      }, {
        "LQN": "LIQUIDITY_NOTE"
      }, {
        "MATURED": "MATURED"
      }, {
        "DN": "DEPOSIT_NOTES"
      }, {
        "RETIRED": "RETIRED"
      }, {
        "BA": "BANKERS_ACCEPTANCE"
      }, {
        "BN": "BANK_NOTES"
      }, {
        "BOX": "BILL_OF_EXCHANGES"
      }, {
        "CD": "CERTIFICATE_OF_DEPOSIT"
      }, {
        "CL": "CALL_LOANS"
      }, {
        "REPLACD": "REPLACED"
      }, {
        "MT": "MANDATORY_TENDER"
      }, {
        "RVLVTRM": "REVOLVER_TERM_LOAN"
      }, {
        "MPP": "MORTGAGE_PRIVATE_PLACEMENT"
      }, {
        "STN": "SHORT_TERM_LOAN_NOTE"
      }, {
        "MPT": "MISCELLANEOUS_PASS_THROUGH"
      }, {
        "TBA": "TO_BE_ANNOUNCED"
      }, {
        "AN": "OTHER_ANTICIPATION_NOTES_BAN_GAN_ETC"
      }, {
        "MIO": "MORTGAGE_INTEREST_ONLY"
      }, {
        "COFP": "CERTIFICATE_OF_PARTICIPATION"
      }, {
        "MBS": "MORTGAGE_BACKED_SECURITIES"
      }, {
        "REV": "REVENUE_BONDS"
      }, {
        "SPCLA": "SPECIAL_ASSESSMENT"
      }, {
        "SPCLO": "SPECIAL_OBLIGATION"
      }, {
        "SPCLT": "SPECIAL_TAX"
      }, {
        "TAN": "TAX_ANTICIPATION_NOTE"
      }, {
        "TAXA": "TAX_ALLOCATION"
      }, {
        "COFO": "CERTIFICATE_OF_OBLIGATION"
      }, {
        "TD": "TIME_DEPOSIT"
      }, {
        "GO": "GENERAL_OBLIGATION_BONDS"
      }, {
        "?": "WILDCARD_ENTRY"
      }, {
        "WAR": "WARRANT"
      }, {
        "MF": "MUTUAL_FUND"
      }, {
        "MLEG": "MULTI_LEG_INSTRUMENT"
      }, {
        "TRAN": "TAX_REVENUE_ANTICIPATION_NOTE"
      }, {
        "MPO": "MORTGAGE_PRINCIPAL_ONLY"
      }, {
        "RP": "REPURCHASE_AGREEMENT"
      }, {
        "NONE": "NO_SECURITY_TYPE"
      }, {
        "XCN": "EXTENDED_COMM_NOTE"
      }, {
        "POOL": "AGENCY_POOLS"
      }, {
        "ABS": "ASSET_BACKED_SECURITIES"
      }, {
        "CMBS": "CORP_MORTGAGE_BACKED_SECURITIES"
      }, {
        "CMO": "COLLATERALIZED_MORTGAGE_OBLIGATION"
      }, {
        "IET": "IOETTE_MORTGAGE"
      }, {
        "RVRP": "REVERSE_REPURCHASE_AGREEMENT"
      }, {
        "FOR": "FOREIGN_EXCHANGE_CONTRACT"
      }, {
        "RAN": "REVENUE_ANTICIPATION_NOTE"
      }, {
        "RVLV": "REVOLVER_LOAN"
      }, {
        "FAC": "FEDERAL_AGENCY_COUPON"
      }, {
        "FADN": "FEDERAL_AGENCY_DISCOUNT_NOTE"
      }, {
        "PEF": "PRIVATE_EXPORT_FUNDING"
      }, {
        "CORP": "CORPORATE_BOND"
      }, {
        "CPP": "CORPORATE_PRIVATE_PLACEMENT"
      }, {
        "CB": "CONVERTIBLE_BOND"
      }, {
        "DUAL": "DUAL_CURRENCY"
      }, {
        "XLINKD": "INDEXED_LINKED"
      }, {
        "YANK": "YANKEE_CORPORATE_BOND"
      }, {
        "CS": "COMMON_STOCK"
      }, {
        "PS": "PREFERRED_STOCK"
      }, {
        "BRADY": "BRADY_BOND"
      }, {
        "TBOND": "US_TREASURY_BOND"
      }, {
        "TINT": "INTEREST_STRIP_FROM_ANY_BOND_OR_NOTE"
      }, {
        "TIPS": "TREASURY_INFLATION_PROTECTED_SECURITIES"
      }, {
        "TCAL": "PRINCIPAL_STRIP_OF_A_CALLABLE_BOND_OR_NOTE"
      }, {
        "TPRN": "PRINCIPAL_STRIP_FROM_A_NON_CALLABLE_BOND_OR_NOTE"
      }, {
        "UST": "US_TREASURY_NOTE_BOND"
      }, {
        "USTB": "US_TREASURY_BILL"
      }, {
        "TERM": "TERM_LOAN"
      }, {
        "STRUCT": "STRUCTURED_NOTES"
      }],
      "169": [{
        "0": "OTHER"
      }, {
        "1": "DTC_SID"
      }, {
        "3": "A_GLOBAL_CUSTODIAN"
      }, {
        "2": "THOMSON_ALERT"
      }],
      "172": [{
        "1": "FREE"
      }, {
        "0": "VERSUS_PAYMENT"
      }],
      "197": [{
        "0": "F_X_NETTING"
      }, {
        "1": "F_X_SWAP"
      }],
      "203": [{
        "1": "UNCOVERED"
      }, {
        "0": "COVERED"
      }],
      "208": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "209": [{
        "3": "FORWARD_AND_MATCH"
      }, {
        "2": "FORWARD"
      }, {
        "1": "MATCH"
      }],
      "216": [{
        "1": "TARGET_FIRM"
      }, {
        "2": "TARGET_LIST"
      }, {
        "3": "BLOCK_FIRM"
      }, {
        "4": "BLOCK_LIST"
      }],
      "219": [{
        "5": "OLD_10"
      }, {
        "1": "CURVE"
      }, {
        "2": "5_YR"
      }, {
        "4": "10_YR"
      }, {
        "6": "30_YR"
      }, {
        "7": "OLD_30"
      }, {
        "8": "3_MO_LIBOR"
      }, {
        "9": "6_MO_LIBOR"
      }, {
        "3": "OLD_5"
      }],
      "221": [{
        "SWAP": "SWAP"
      }, {
        "LIBID": "LIBID"
      }, {
        "OTHER": "OTHER"
      }, {
        "Treasury": "TREASURY"
      }, {
        "Euribor": "EURIBOR"
      }, {
        "Pfandbriefe": "PFANDBRIEFE"
      }, {
        "FutureSWAP": "FUTURESWAP"
      }, {
        "MuniAAA": "MUNIAAA"
      }, {
        "LIBOR": "LIBOR"
      }],
      "233": [{
        "ABS": "ABSOLUTE_PREPAYMENT_SPEED"
      }, {
        "WALA": "WEIGHTED_AVERAGE_LOAN_AGE"
      }, {
        "WAM": "WEIGHTED_AVERAGE_MATURITY"
      }, {
        "CPR": "CONSTANT_PREPAYMENT_RATE"
      }, {
        "HEP": "FINAL_CPR_OF_HOME_EQUITY_PREPAYMENT_CURVE"
      }, {
        "WAL": "WEIGHTED_AVERAGE_LIFE"
      }, {
        "MHP": "OF_MANUFACTURED_HOUSING_PREPAYMENT_CURVE"
      }, {
        "SMM": "SINGLE_MONTHLY_MORTALITY"
      }, {
        "MPR": "MONTHLY_PREPAYMENT_RATE"
      }, {
        "PSA": "OF_BMA_PREPAYMENT_CURVE"
      }, {
        "PPC": "OF_PROSPECTUS_PREPAYMENT_CURVE"
      }, {
        "CPP": "CONSTANT_PREPAYMENT_PENALTY"
      }, {
        "LOTVAR": "LOT_VARIANCE"
      }, {
        "CPY": "CONSTANT_PREPAYMENT_YIELD"
      }, {
        "WAC": "WEIGHTED_AVERAGE_COUPON"
      }, {
        "ISSUE": "YEAR_OF_ISSUE"
      }, {
        "MAT": "MATURITY_YEAR"
      }, {
        "PIECES": "NUMBER_OF_PIECES"
      }, {
        "PMAX": "POOLS_MAXIMUM"
      }, {
        "PPM": "POOLS_PER_MILLION"
      }, {
        "PPL": "POOLS_PER_LOT"
      }, {
        "PPT": "POOLS_PER_TRADE"
      }, {
        "PROD": "PRODUCTION_YEAR"
      }, {
        "TRDVAR": "TRADE_VARIANCE"
      }, {
        "GEOG": "GEOGRAPHICS"
      }],
      "235": [{
        "TRUE": "TRUE_YIELD_THE_YIELD_CALCULATED_WITH_COUPON_DATES_MOVED_FROM_A_WEEKEND_OR_HOLIDAY_TO_THE_NEXT_VALID_SETTLEMENT_DATE"
      }, {
        "PREVCLOSE": "PREVIOUS_CLOSE_YIELD_THE_YIELD_OF_A_BOND_BASED_ON_THE_CLOSING_PRICE_1_DAY_AGO"
      }, {
        "LONGEST": "YIELD_TO_LONGEST_AVERAGE"
      }, {
        "LONGAVGLIFE": "YIELD_TO_LONGEST_AVERAGE_LIFE_THE_YIELD_ASSUMING_ONLY_MANDATORY_SINKS_ARE_TAKEN_THIS_RESULTS_IN_A_LOWER_PAYDOWN_OF_DEBT_THE_YIELD_IS_THEN_CALCULATED_TO_THE_FINAL_PAYMENT_DATE"
      }, {
        "MATURITY": "YIELD_TO_MATURITY_THE_YIELD_OF_A_BOND_TO_ITS_MATURITY_DATE"
      }, {
        "MARK": "MARK_TO_MARKET_YIELD_AN_ADJUSTMENT_IN_THE_VALUATION_OF_A_SECURITIES_PORTFOLIO_TO_REFLECT_THE_CURRENT_MARKET_VALUES_OF_THE_RESPECTIVE_SECURITIES_IN_THE_PORTFOLIO"
      }, {
        "OPENAVG": "OPEN_AVERAGE_YIELD_THE_AVERAGE_YIELD_OF_THE_RESPECTIVE_SECURITIES_IN_THE_PORTFOLIO"
      }, {
        "PUT": "YIELD_TO_NEXT_PUT_THE_YIELD_TO_THE_DATE_AT_WHICH_THE_BOND_HOLDER_CAN_NEXT_PUT_THE_BOND_TO_THE_ISSUER"
      }, {
        "PROCEEDS": "PROCEEDS_YIELD_THE_CD_EQUIVALENT_YIELD_WHEN_THE_REMAINING_TIME_TO_MATURITY_IS_LESS_THAN_TWO_YEARS"
      }, {
        "SEMIANNUAL": "SEMI_ANNUAL_YIELD_THE_YIELD_OF_A_BOND_WHOSE_COUPON_PAYMENTS_ARE_REINVESTED_SEMI_ANNUALLY"
      }, {
        "SHORTAVGLIFE": "YIELD_TO_SHORTEST_AVERAGE_LIFE_SAME_AS_AVGLIFE_ABOVE"
      }, {
        "SHORTEST": "YIELD_TO_SHORTEST_AVERAGE"
      }, {
        "SIMPLE": "SIMPLE_YIELD_THE_YIELD_OF_A_BOND_ASSUMING_NO_REINVESTMENT_OF_COUPON_PAYMENTS"
      }, {
        "TENDER": "YIELD_TO_TENDER_DATE_THE_YIELD_ON_A_MUNICIPAL_BOND_TO_ITS_MANDATORY_TENDER_DATE"
      }, {
        "VALUE1/32": "YIELD_VALUE_OF_1_32_THE_AMOUNT_THAT_THE_YIELD_WILL_CHANGE_FOR_A_1_32ND_CHANGE_IN_PRICE"
      }, {
        "WORST": "YIELD_TO_WORST_CONVENTION_THE_LOWEST_YIELD_TO_ALL_POSSIBLE_REDEMPTION_DATE_SCENARIOS"
      }, {
        "TAXEQUIV": "TAX_EQUIVALENT_YIELD_THE_AFTER_TAX_YIELD_GROSSED_UP_BY_THE_MAXIMUM_FEDERAL_TAX_RATE_OF_396_FOR_COMPARISON_TO_TAXABLE_YIELDS"
      }, {
        "ANNUAL": "ANNUAL_YIELD_THE_ANNUAL_INTEREST_OR_DIVIDEND_INCOME_AN_INVESTMENT_EARNS_EXPRESSED_AS_A_PERCENTAGE_OF_THE_INVESTMENTS_TOTAL_VALUE"
      }, {
        "LASTYEAR": "CLOSING_YIELD_MOST_RECENT_YEAR_THE_YIELD_OF_A_BOND_BASED_ON_THE_CLOSING_PRICE_AS_OF_THE_MOST_RECENT_YEARS_END"
      }, {
        "NEXTREFUND": "YIELD_TO_NEXT_REFUND"
      }, {
        "AFTERTAX": "AFTER_TAX_YIELD"
      }, {
        "ATISSUE": "YIELD_AT_ISSUE"
      }, {
        "AVGLIFE": "YIELD_TO_AVERAGE_LIFE_THE_YIELD_ASSUMING_THAT_ALL_SINKS"
      }, {
        "AVGMATURITY": "YIELD_TO_AVERAGE_MATURITY_THE_YIELD_ACHIEVED_BY_SUBSTITUTING_A_BONDS_AVERAGE_MATURITY_FOR_THE_ISSUES_FINAL_MATURITY_DATE"
      }, {
        "BOOK": "BOOK_YIELD_THE_YIELD_OF_A_SECURITY_CALCULATED_BY_USING_ITS_BOOK_VALUE_INSTEAD_OF_THE_CURRENT_MARKET_PRICE_THIS_TERM_IS_TYPICALLY_USED_IN_THE_US_DOMESTIC_MARKET"
      }, {
        "CALL": "YIELD_TO_NEXT_CALL_THE_YIELD_OF_A_BOND_TO_THE_NEXT_POSSIBLE_CALL_DATE"
      }, {
        "CHANGE": "YIELD_CHANGE_SINCE_CLOSE_THE_CHANGE_IN_THE_YIELD_SINCE_THE_PREVIOUS_DAYS_CLOSING_YIELD"
      }, {
        "COMPOUND": "COMPOUND_YIELD_THE_YIELD_OF_CERTAIN_JAPANESE_BONDS_BASED_ON_ITS_PRICE_CERTAIN_JAPANESE_BONDS_HAVE_IRREGULAR_FIRST_OR_LAST_COUPONS_AND_THE_YIELD_IS_CALCULATED_COMPOUND_FOR_THESE_IRREGULAR_PERIODS"
      }, {
        "CURRENT": "CURRENT_YIELD_ANNUAL_INTEREST_ON_A_BOND_DIVIDED_BY_THE_MARKET_VALUE_THE_ACTUAL_INCOME_RATE_OF_RETURN_AS_OPPOSED_TO_THE_COUPON_RATE_EXPRESSED_AS_A_PERCENTAGE"
      }, {
        "GROSS": "TRUE_GROSS_YIELD_YIELD_CALCULATED_USING_THE_PRICE_INCLUDING_ACCRUED_INTEREST_WHERE_COUPON_DATES_ARE_MOVED_FROM_HOLIDAYS_AND_WEEKENDS_TO_THE_NEXT_TRADING_DAY"
      }, {
        "GOVTEQUIV": "GOVERNMENT_EQUIVALENT_YIELD_ASK_YIELD_BASED_ON_SEMI_ANNUAL_COUPONS_COMPOUNDING_IN_ALL_PERIODS_AND_ACTUAL_ACTUAL_CALENDAR"
      }, {
        "INFLATION": "YIELD_WITH_INFLATION_ASSUMPTION_BASED_ON_PRICE_THE_RETURN_AN_INVESTOR_WOULD_REQUIRE_ON_A_NORMAL_BOND_THAT_WOULD_MAKE_THE_REAL_RETURN_EQUAL_TO_THAT_OF_THE_INFLATION_INDEXED_BOND_ASSUMING_A_CONSTANT_INFLATION_RATE"
      }, {
        "INVERSEFLOATER": "INVERSE_FLOATER_BOND_YIELD_INVERSE_FLOATER_SEMI_ANNUAL_BOND_EQUIVALENT_RATE"
      }, {
        "LASTQUARTER": "CLOSING_YIELD_MOST_RECENT_QUARTER_THE_YIELD_OF_A_BOND_BASED_ON_THE_CLOSING_PRICE_AS_OF_THE_MOST_RECENT_QUARTERS_END"
      }, {
        "LASTCLOSE": "MOST_RECENT_CLOSING_YIELD_THE_LAST_AVAILABLE_YIELD_STORED_IN_HISTORY_COMPUTED_USING_PRICE"
      }, {
        "LASTMONTH": "CLOSING_YIELD_MOST_RECENT_MONTH_THE_YIELD_OF_A_BOND_BASED_ON_THE_CLOSING_PRICE_AS_OF_THE_MOST_RECENT_MONTHS_END"
      }, {
        "CLOSE": "CLOSING_YIELD_THE_YIELD_OF_A_BOND_BASED_ON_THE_CLOSING_PRICE"
      }],
      "258": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "263": [{
        "1": "SNAPSHOT_PLUS_UPDATES"
      }, {
        "2": "DISABLE_PREVIOUS_SNAPSHOT_PLUS_UPDATE_REQUEST"
      }, {
        "0": "SNAPSHOT"
      }],
      "265": [{
        "0": "FULL_REFRESH"
      }, {
        "1": "INCREMENTAL_REFRESH"
      }],
      "266": [{
        "Y": "YES"
      }, {
        "N": "NO"
      }],
      "269": [{
        "7": "TRADING_SESSION_HIGH_PRICE"
      }, {
        "1": "OFFER"
      }, {
        "A": "IMBALANCE"
      }, {
        "9": "TRADING_SESSION_VWAP_PRICE"
      }, {
        "8": "TRADING_SESSION_LOW_PRICE"
      }, {
        "5": "CLOSING_PRICE"
      }, {
        "4": "OPENING_PRICE"
      }, {
        "0": "BID"
      }, {
        "2": "TRADE"
      }, {
        "3": "INDEX_VALUE"
      }, {
        "6": "SETTLEMENT_PRICE"
      }],
      "274": [{
        "0": "PLUS_TICK"
      }, {
        "1": "ZERO_PLUS_TICK"
      }, {
        "2": "MINUS_TICK"
      }, {
        "3": "ZERO_MINUS_TICK"
      }],
      "276": [{
        "E": "LOCKED"
      }, {
        "I": "NON_FIRM"
      }, {
        "H": "FAST_TRADING"
      }, {
        "F": "CROSSED"
      }, {
        "D": "CONSOLIDATED_BEST"
      }, {
        "C": "EXCHANGE_BEST"
      }, {
        "B": "CLOSED"
      }, {
        "A": "OPEN"
      }, {
        "G": "DEPTH"
      }],
      "277": [{
        "J": "NEXT_DAY_TRADE"
      }, {
        "K": "OPENED"
      }, {
        "L": "SELLER"
      }, {
        "B": "AVERAGE_PRICE_TRADE"
      }, {
        "M": "SOLD"
      }, {
        "H": "RULE_155_TRADE"
      }, {
        "N": "STOPPED_STOCK"
      }, {
        "P": "IMBALANCE_MORE_BUYERS"
      }, {
        "Q": "IMBALANCE_MORE_SELLERS"
      }, {
        "R": "OPENING_PRICE"
      }, {
        "I": "SOLD_LAST"
      }, {
        "A": "CASH"
      }, {
        "C": "CASH_TRADE"
      }, {
        "E": "OPENING"
      }, {
        "F": "INTRADAY_TRADE_DETAIL"
      }, {
        "G": "RULE_127_TRADE"
      }, {
        "D": "NEXT_DAY"
      }],
      "279": [{
        "0": "NEW"
      }, {
        "1": "CHANGE"
      }, {
        "2": "DELETE"
      }],
      "281": [{
        "7": "UNSUPPORTED_AGGREGATEDBOOK"
      }, {
        "1": "DUPLICATE_MDREQID"
      }, {
        "C": "UNSUPPORTED_MDIMPLICITDELETE"
      }, {
        "B": "UNSUPPORTED_OPENCLOSESETTLEFLAG"
      }, {
        "A": "UNSUPPORTED_SCOPE"
      }, {
        "9": "UNSUPPORTED_TRADINGSESSIONID"
      }, {
        "8": "UNSUPPORTED_MDENTRYTYPE"
      }, {
        "6": "UNSUPPORTED_MDUPDATETYPE"
      }, {
        "5": "UNSUPPORTED_MARKETDEPTH"
      }, {
        "4": "UNSUPPORTED_SUBSCRIPTIONREQUESTTYPE"
      }, {
        "2": "INSUFFICIENT_BANDWIDTH"
      }, {
        "0": "UNKNOWN_SYMBOL"
      }, {
        "3": "INSUFFICIENT_PERMISSIONS"
      }],
      "285": [{
        "0": "CANCELATION"
      }, {
        "1": "ERROR"
      }],
      "286": [{
        "1": "SESSION_OPEN"
      }, {
        "2": "DELIVERY_SETTLEMENT_PRICE"
      }, {
        "3": "EXPECTED_PRICE"
      }, {
        "4": "PRICE_FROM_PREVIOUS_BUSINESS_DAY"
      }, {
        "0": "DAILY_OPEN"
      }],
      "291": [{
        "1": "BANKRUPT"
      }, {
        "2": "PENDING_DELISTING"
      }],
      "292": [{
        "B": "EX_DISTRIBUTION"
      }, {
        "E": "EX_INTEREST"
      }, {
        "C": "EX_RIGHTS"
      }, {
        "A": "EX_DIVIDEND"
      }, {
        "D": "NEW"
      }],
      "297": [{
        "6": "REMOVED_FROM_MARKET"
      }, {
        "1": "CANCELED_FOR_SYMBOL"
      }, {
        "10": "PENDING"
      }, {
        "9": "QUOTE_NOT_FOUND"
      }, {
        "8": "QUERY"
      }, {
        "7": "EXPIRED"
      }, {
        "5": "REJECTED"
      }, {
        "4": "CANCELED_ALL"
      }, {
        "3": "CANCELED_FOR_UNDERLYING"
      }, {
        "2": "CANCELED_FOR_SECURITY_TYPE"
      }, {
        "0": "ACCEPTED"
      }],
      "298": [{
        "4": "CANCEL_ALL_QUOTES"
      }, {
        "2": "CANCEL_FOR_SECURITY_TYPE"
      }, {
        "1": "CANCEL_FOR_SYMBOL"
      }, {
        "3": "CANCEL_FOR_UNDERLYING_SYMBOL"
      }],
      "300": [{
        "9": "NOT_AUTHORIZED_TO_QUOTE_SECURITY"
      }, {
        "1": "UNKNOWN_SYMBOL"
      }, {
        "2": "EXCHANGE"
      }, {
        "3": "QUOTE_REQUEST_EXCEEDS_LIMIT"
      }, {
        "4": "TOO_LATE_TO_ENTER"
      }, {
        "5": "UNKNOWN_QUOTE"
      }, {
        "6": "DUPLICATE_QUOTE"
      }, {
        "7": "INVALID_BID_ASK_SPREAD"
      }, {
        "8": "INVALID_PRICE"
      }],
      "301": [{
        "1": "ACKNOWLEDGE_ONLY_NEGATIVE_OR_ERRONEOUS_QUOTES"
      }, {
        "0": "NO_ACKNOWLEDGEMENT"
      }, {
        "2": "ACKNOWLEDGE_EACH_QUOTE_MESSAGES"
      }],
      "303": [{
        "2": "AUTOMATIC"
      }, {
        "1": "MANUAL"
      }],
      "321": [{
        "0": "REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS"
      }, {
        "1": "REQUEST_SECURITY_IDENTITY_FOR_THE_SPECIFICATIONS_PROVIDED"
      }, {
        "2": "REQUEST_LIST_SECURITY_TYPES"
      }, {
        "3": "REQUEST_LIST_SECURITIES"
      }],
      "323": [{
        "5": "REJECT_SECURITY_PROPOSAL"
      }, {
        "1": "ACCEPT_SECURITY_PROPOSAL_AS_IS"
      }, {
        "6": "CAN_NOT_MATCH_SELECTION_CRITERIA"
      }, {
        "2": "ACCEPT_SECURITY_PROPOSAL_WITH_REVISIONS_AS_INDICATED_IN_THE_MESSAGE"
      }, {
        "4": "LIST_OF_SECURITIES_RETURNED_PER_REQUEST"
      }, {
        "3": "LIST_OF_SECURITY_TYPES_RETURNED_PER_REQUEST"
      }],
      "325": [{
        "Y": "YES"
      }, {
        "N": "NO"
      }],
      "326": [{
        "20": "UNKNOWN_OR_INVALID"
      }, {
        "13": "NO_MARKET_ON_CLOSE_IMBALANCE"
      }, {
        "14": "ITS_PRE_OPENING"
      }, {
        "15": "NEW_PRICE_INDICATION"
      }, {
        "16": "TRADE_DISSEMINATION_TIME"
      }, {
        "17": "READY_TO_TRADE"
      }, {
        "19": "NOT_TRADED_ON_THIS_MARKET"
      }, {
        "22": "OPENING_ROTATION"
      }, {
        "21": "PRE_OPEN"
      }, {
        "12": "NO_MARKET_IMBALANCE"
      }, {
        "18": "NOT_AVAILABLE_FOR_TRADING"
      }, {
        "10": "MARKET_ON_CLOSE_IMBALANCE_SELL"
      }, {
        "9": "MARKET_ON_CLOSE_IMBALANCE_BUY"
      }, {
        "8": "MARKET_IMBALANCE_SELL"
      }, {
        "7": "MARKET_IMBALANCE_BUY"
      }, {
        "6": "TRADING_RANGE_INDICATION"
      }, {
        "5": "PRICE_INDICATION"
      }, {
        "4": "NO_OPEN_NO_RESUME"
      }, {
        "3": "RESUME"
      }, {
        "1": "OPENING_DELAY"
      }, {
        "2": "TRADING_HALT"
      }, {
        "23": "FAST_MARKET"
      }],
      "327": [{
        "X": "EQUIPMENT_CHANGEOVER"
      }, {
        "M": "ADDITIONAL_INFORMATION"
      }, {
        "E": "ORDER_INFLUX"
      }, {
        "P": "NEWS_PENDING"
      }, {
        "I": "ORDER_IMBALANCE"
      }, {
        "D": "NEWS_DISSEMINATION"
      }],
      "328": [{
        "Y": "YES"
      }, {
        "N": "NO"
      }],
      "329": [{
        "Y": "YES"
      }, {
        "N": "NO"
      }],
      "334": [{
        "1": "CANCEL"
      }, {
        "2": "ERROR"
      }, {
        "3": "CORRECTION"
      }],
      "338": [{
        "3": "TWO_PARTY"
      }, {
        "1": "ELECTRONIC"
      }, {
        "2": "OPEN_OUTCRY"
      }],
      "339": [{
        "3": "PRODUCTION"
      }, {
        "1": "TESTING"
      }, {
        "2": "SIMULATED"
      }],
      "340": [{
        "5": "PRE_CLOSE"
      }, {
        "6": "REQUEST_REJECTED"
      }, {
        "4": "PRE_OPEN"
      }, {
        "3": "CLOSED"
      }, {
        "2": "OPEN"
      }, {
        "1": "HALTED"
      }, {
        "0": "UNKNOWN"
      }],
      "347": [{
        "UTF-8": "UTF_8"
      }, {
        "ISO-2022-JP": "ISO_2022_JP"
      }, {
        "EUC-JP": "EUC_JP"
      }, {
        "SHIFT_JIS": "SHIFT_JIS"
      }],
      "373": [{
        "12": "XML_VALIDATION_ERROR"
      }, {
        "17": "NON_DATA_VALUE_INCLUDES_FIELD_DELIMITER"
      }, {
        "16": "INCORRECT_NUMINGROUP_COUNT_FOR_REPEATING_GROUP"
      }, {
        "15": "REPEATING_GROUP_FIELDS_OUT_OF_ORDER"
      }, {
        "14": "TAG_SPECIFIED_OUT_OF_REQUIRED_ORDER"
      }, {
        "11": "INVALID_MSGTYPE"
      }, {
        "0": "INVALID_TAG_NUMBER"
      }, {
        "9": "COMPID_PROBLEM"
      }, {
        "8": "SIGNATURE_PROBLEM"
      }, {
        "7": "DECRYPTION_PROBLEM"
      }, {
        "6": "INCORRECT_DATA_FORMAT_FOR_VALUE"
      }, {
        "5": "VALUE_IS_INCORRECT"
      }, {
        "4": "TAG_SPECIFIED_WITHOUT_A_VALUE"
      }, {
        "3": "UNDEFINED_TAG"
      }, {
        "10": "SENDINGTIME_ACCURACY_PROBLEM"
      }, {
        "13": "TAG_APPEARS_MORE_THAN_ONCE"
      }, {
        "2": "TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE"
      }, {
        "1": "REQUIRED_TAG_MISSING"
      }],
      "374": [{
        "N": "NEW"
      }, {
        "C": "CANCEL"
      }],
      "377": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "378": [{
        "7": "CANCEL_ON_SYSTEM_FAILURE"
      }, {
        "0": "GT_CORPORATE_ACTION"
      }, {
        "8": "MARKET"
      }, {
        "6": "CANCEL_ON_TRADING_HALT"
      }, {
        "5": "PARTIAL_DECLINE_OF_ORDERQTY"
      }, {
        "4": "BROKER_OPTION"
      }, {
        "3": "REPRICING_OF_ORDER"
      }, {
        "1": "GT_RENEWAL"
      }, {
        "2": "VERBAL_CHANGE"
      }],
      "380": [{
        "3": "UNSUPPORTED_MESSAGE_TYPE"
      }, {
        "7": "DELIVERTO_FIRM_NOT_AVAILABLE_AT_THIS_TIME"
      }, {
        "4": "APPLICATION_NOT_AVAILABLE"
      }, {
        "6": "NOT_AUTHORIZED"
      }, {
        "0": "OTHER"
      }, {
        "5": "CONDITIONALLY_REQUIRED_FIELD_MISSING"
      }, {
        "1": "UNKOWN_ID"
      }, {
        "2": "UNKNOWN_SECURITY"
      }],
      "385": [{
        "S": "SEND"
      }, {
        "R": "RECEIVE"
      }],
      "388": [{
        "0": "RELATED_TO_DISPLAYED_PRICE"
      }, {
        "1": "RELATED_TO_MARKET_PRICE"
      }, {
        "2": "RELATED_TO_PRIMARY_PRICE"
      }, {
        "3": "RELATED_TO_LOCAL_PRIMARY_PRICE"
      }, {
        "4": "RELATED_TO_MIDPOINT_PRICE"
      }, {
        "5": "RELATED_TO_LAST_TRADE_PRICE"
      }],
      "394": [{
        "1": "NON_DISCLOSED_STYLE"
      }, {
        "2": "DISCLOSED_STYLE"
      }, {
        "3": "NO_BIDDING_PROCESS"
      }],
      "399": [{
        "3": "INDEX"
      }, {
        "2": "COUNTRY"
      }, {
        "1": "SECTOR"
      }],
      "401": [{
        "1": "SIDEVALUE1"
      }, {
        "2": "SIDEVALUE_2"
      }],
      "409": [{
        "3": "NORMAL_MARKET_SIZE"
      }, {
        "4": "OTHER"
      }, {
        "2": "20_DAY_MOVING_AVERAGE"
      }, {
        "1": "5DAY_MOVING_AVERAGE"
      }],
      "411": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "414": [{
        "3": "REAL_TIME_EXECUTION_REPORTS"
      }, {
        "2": "SELLSIDE_PERIODICALLY_SENDS_STATUS_USING_LISTSTATUS_PERIOD_OPTIONALLY_SPECIFIED_IN_PROGRESSPERIOD"
      }, {
        "1": "BUYSIDE_EXPLICITLY_REQUESTS_STATUS_USING_STATUSREQUEST"
      }],
      "416": [{
        "2": "GROSS"
      }, {
        "1": "NET"
      }],
      "418": [{
        "G": "VWAP_GUARANTEE"
      }, {
        "A": "AGENCY"
      }, {
        "J": "GUARANTEED_CLOSE"
      }, {
        "R": "RISK_TRADE"
      }],
      "419": [{
        "8": "VWAP_THROUGH_AN_AFTERNOON_SESSION"
      }, {
        "D": "OPEN"
      }, {
        "Z": "OTHERS"
      }, {
        "C": "STRIKE"
      }, {
        "B": "VWAP_THROUGH_AN_AFTERNOON_SESSION_EXCEPT_YORI"
      }, {
        "9": "VWAP_THROUGH_A_DAY_EXCEPT_YORI"
      }, {
        "7": "VWAP_THROUGH_A_MORNING_SESSION"
      }, {
        "6": "VWAP_THROUGH_A_DAY"
      }, {
        "5": "SQ"
      }, {
        "4": "CURRENT_PRICE"
      }, {
        "3": "CLOSING_PRICE"
      }, {
        "2": "CLOSING_PRICE_AT_MORNING_SESSION"
      }, {
        "A": "VWAP_THROUGH_A_MORNING_SESSION_EXCEPT_YORI"
      }],
      "423": [{
        "3": "FIXED_AMOUNT"
      }, {
        "1": "PERCENTAGE"
      }, {
        "4": "DISCOUNT"
      }, {
        "6": "BASIS_POINTS_RELATIVE_TO_BENCHMARK"
      }, {
        "7": "TED_PRICE"
      }, {
        "8": "TED_YIELD"
      }, {
        "5": "PREMIUM"
      }, {
        "2": "PER_SHARE"
      }],
      "427": [{
        "0": "BOOK_OUT_ALL_TRADES_ON_DAY_OF_EXECUTION"
      }, {
        "2": "ACCUMULATE_UNTIL_VERBALLY_NOTIFIED_OTHERWISE"
      }, {
        "1": "ACCUMULATE_EXECUTIONS_UNTIL_ORDER_IS_FILLED_OR_EXPIRES"
      }],
      "429": [{
        "6": "ALERT"
      }, {
        "4": "EXECSTARTED"
      }, {
        "3": "TIMED"
      }, {
        "2": "RESPONSE"
      }, {
        "1": "ACK"
      }, {
        "5": "ALLDONE"
      }],
      "430": [{
        "1": "NET"
      }, {
        "2": "GROSS"
      }],
      "431": [{
        "4": "CANCELING"
      }, {
        "3": "EXECUTING"
      }, {
        "7": "REJECT"
      }, {
        "6": "ALL_DONE"
      }, {
        "5": "ALERT"
      }, {
        "2": "RECEIVEDFOREXECUTION"
      }, {
        "1": "INBIDDINGPROCESS"
      }],
      "433": [{
        "5": "EXCHANGE_SWITCH_CIV_ORDER_BUY_DRIVEN_CASH_WITHDRAW"
      }, {
        "4": "EXCHANGE_SWITCH_CIV_ORDER_BUY_DRIVEN_CASH_TOP_UP"
      }, {
        "2": "WAIT_FOR_EXECUTE_INSTRUCTION"
      }, {
        "1": "IMMEDIATE"
      }, {
        "3": "EXCHANGE_SWITCH_CIV_ORDER_SELL_DRIVEN"
      }],
      "434": [{
        "2": "ORDER_CANCEL_REPLACE_REQUEST"
      }, {
        "1": "ORDER_CANCEL_REQUEST"
      }],
      "442": [{
        "1": "SINGLE_SECURITY"
      }, {
        "2": "INDIVIDUAL_LEG_OF_A_MULTI_LEG_SECURITY"
      }, {
        "3": "MULTI_LEG_SECURITY"
      }],
      "447": [{
        "5": "CHINESE_B_SHARE"
      }, {
        "8": "US_EMPLOYER_IDENTIFICATION_NUMBER"
      }, {
        "A": "AUSTRALIAN_TAX_FILE_NUMBER"
      }, {
        "9": "AUSTRALIAN_BUSINESS_NUMBER"
      }, {
        "E": "ISO_COUNTRY_CODE"
      }, {
        "B": "BIC"
      }, {
        "7": "US_SOCIAL_SECURITY_NUMBER"
      }, {
        "D": "PROPRIETARY_CUSTOM_CODE"
      }, {
        "F": "SETTLEMENT_ENTITY_LOCATION"
      }, {
        "1": "KOREAN_INVESTOR_ID"
      }, {
        "2": "TAIWANESE_QUALIFIED_FOREIGN_INVESTOR_ID_QFII"
      }, {
        "3": "TAIWANESE_TRADING_ACCOUNT"
      }, {
        "4": "MALAYSIAN_CENTRAL_DEPOSITORY"
      }, {
        "6": "UK_NATIONAL_INSURANCE_OR_PENSION_NUMBER"
      }, {
        "C": "GENERALLY_ACCEPTED_MARKET_PARTICIPANT_IDENTIFIER"
      }],
      "452": [{
        "15": "CORRESPONDANT_CLEARING_FIRM"
      }, {
        "3": "CLIENT_ID"
      }, {
        "20": "UNDERLYING_CONTRA_FIRM"
      }, {
        "19": "SPONSORING_FIRM"
      }, {
        "18": "CONTRA_CLEARING_FIRM"
      }, {
        "17": "CONTRA_FIRM"
      }, {
        "16": "EXECUTING_SYSTEM"
      }, {
        "7": "ENTERING_FIRM"
      }, {
        "1": "EXECUTING_FIRM"
      }, {
        "2": "BROKER_OF_CREDIT"
      }, {
        "5": "INVESTOR_ID"
      }, {
        "6": "INTRODUCING_FIRM"
      }, {
        "14": "GIVEUP_CLEARING_FIRM"
      }, {
        "8": "LOCATE_LENDING_FIRM"
      }, {
        "9": "FUND_MANAGER_CLIENT_ID"
      }, {
        "10": "SETTLEMENT_LOCATION"
      }, {
        "11": "ORDER_ORIGINATION_TRADER"
      }, {
        "12": "EXECUTING_TRADER"
      }, {
        "13": "ORDER_ORIGINATION_FIRM"
      }, {
        "4": "CLEARING_FIRM"
      }],
      "460": [{
        "8": "LOAN"
      }, {
        "12": "OTHER"
      }, {
        "11": "MUNICIPAL"
      }, {
        "1": "AGENCY"
      }, {
        "3": "CORPORATE"
      }, {
        "4": "CURRENCY"
      }, {
        "2": "COMMODITY"
      }, {
        "6": "GOVERNMENT"
      }, {
        "10": "MORTGAGE"
      }, {
        "7": "INDEX"
      }, {
        "9": "MONEYMARKET"
      }, {
        "5": "EQUITY"
      }],
      "464": [{
        "Y": "YES"
      }, {
        "N": "NO"
      }],
      "465": [{
        "6": "CONTRACTS"
      }, {
        "7": "OTHER"
      }, {
        "5": "CURRENCY"
      }, {
        "4": "ORIGINALFACE"
      }, {
        "3": "CURRENTFACE"
      }, {
        "2": "BONDS"
      }, {
        "1": "SHARES"
      }, {
        "8": "PAR"
      }],
      "468": [{
        "0": "ROUND_TO_NEAREST"
      }, {
        "1": "ROUND_DOWN"
      }, {
        "2": "ROUND_UP"
      }],
      "480": [{
        "M": "NO_WAIVER_AGREEMENT"
      }, {
        "N": "NO_EXECUTION_ONLY"
      }, {
        "Y": "YES"
      }, {
        "O": "NO_INSTITUTIONAL"
      }],
      "481": [{
        "3": "EXEMPT_AUTHORISED_CREDIT_OR_FINANCIAL_INSTITUTION"
      }, {
        "2": "EXEMPT_CLIENT_MONEY_TYPE_EXEMPTION"
      }, {
        "1": "EXEMPT_BELOW_THE_LIMIT"
      }, {
        "Y": "PASSED"
      }, {
        "N": "NOT_CHECKED"
      }],
      "484": [{
        "S": "SINGLE_PRICE"
      }, {
        "Q": "OFFER_PRICE_MINUS_ADJUSTMENT_AMOUNT"
      }, {
        "P": "OFFER_PRICE_MINUS_ADJUSTMENT"
      }, {
        "O": "OFFER_PRICE"
      }, {
        "E": "CREATION_PRICE_PLUS_ADJUSTMENT_AMOUNT"
      }, {
        "D": "CREATION_PRICE_PLUS_ADJUSTMENT"
      }, {
        "C": "CREATION_PRICE"
      }, {
        "B": "BID_PRICE"
      }],
      "487": [{
        "N": "NEW"
      }, {
        "R": "REPLACE"
      }, {
        "C": "CANCEL"
      }],
      "492": [{
        "14": "BPAY"
      }, {
        "13": "ACH_CREDIT"
      }, {
        "12": "ACH_DEBIT"
      }, {
        "11": "CREDIT_CARD"
      }, {
        "10": "DIRECT_CREDIT"
      }, {
        "9": "DIRECT_DEBIT"
      }, {
        "8": "DEBIT_CARD"
      }, {
        "7": "FEDWIRE"
      }, {
        "15": "HIGH_VALUE_CLEARING_SYSTEM"
      }, {
        "3": "EUROCLEAR"
      }, {
        "6": "TELEGRAPHIC_TRANSFER"
      }, {
        "4": "CLEARSTREAM"
      }, {
        "1": "CREST"
      }, {
        "2": "NSCC"
      }, {
        "5": "CHEQUE"
      }],
      "495": [{
        "19": "PROFIT_SHARING_PLAN"
      }, {
        "11": "EMPLOYER"
      }, {
        "12": "EMPLOYER_CURRENT_YEAR"
      }, {
        "13": "NON_FUND_PROTOTYPE_IRA"
      }, {
        "14": "NON_FUND_QUALIFIED_PLAN"
      }, {
        "15": "DEFINED_CONTRIBUTION_PLAN"
      }, {
        "10": "EMPLOYEE_CURRENT_YEAR"
      }, {
        "17": "INDIVIDUAL_RETIREMENT_ACCOUNT_ROLLOVER"
      }, {
        "5": "MINI_INSURANCE_ISA"
      }, {
        "16": "INDIVIDUAL_RETIREMENT_ACCOUNT"
      }, {
        "9": "EMPLOYEE"
      }, {
        "8": "ASSET_TRANSFER"
      }, {
        "21": "SELF_DIRECTED_IRA"
      }, {
        "6": "CURRENT_YEAR_PAYMENT"
      }, {
        "20": "401K"
      }, {
        "4": "MINI_STOCKS_AND_SHARES_ISA"
      }, {
        "3": "MINI_CASH_ISA"
      }, {
        "2": "TESSA"
      }, {
        "1": "MAXI_ISA"
      }, {
        "0": "NONE_NOT_APPLICABLE"
      }, {
        "7": "PRIOR_YEAR_PAYMENT"
      }, {
        "23": "457"
      }, {
        "24": "ROTH_IRA_24"
      }, {
        "25": "ROTH_IRA_25"
      }, {
        "26": "ROTH_CONVERSION_IRA_26"
      }, {
        "27": "ROTH_CONVERSION_IRA_27"
      }, {
        "28": "EDUCATION_IRA_28"
      }, {
        "29": "EDUCATION_IRA_29"
      }, {
        "18": "KEOGH"
      }, {
        "22": "403"
      }],
      "497": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "506": [{
        "A": "ACCEPT"
      }, {
        "N": "REMINDER"
      }, {
        "R": "REJECT"
      }, {
        "H": "HELD"
      }],
      "507": [{
        "13": "INVALID_UNACCEPTABLE_NODISTRIBINSTNS"
      }, {
        "17": "INVALID_UNACCEPTABLE_CASH_DISTRIB_AGENT_CODE"
      }, {
        "16": "INVALID_UNACCEPTABLE_CASH_DISTRIB_AGENT_ACCT_NAME"
      }, {
        "4": "INVALID_UNACCEPTABLE_NO_REG_DETLS"
      }, {
        "15": "INVALID_UNACCEPTABLE_DISTRIB_PAYMENT_METHOD"
      }, {
        "14": "INVALID_UNACCEPTABLE_DISTRIB_PERCENTAGE"
      }, {
        "3": "INVALID_UNACCEPTABLE_OWNERSHIP_TYPE"
      }, {
        "2": "INVALID_UNACCEPTABLE_TAX_EXEMPT_TYPE"
      }, {
        "12": "INVALID_UNACCEPTABLE_INVESTOR_COUNTRY_OF_RESIDENCE"
      }, {
        "11": "INVALID_UNACCEPTABLE_DATE_OF_BIRTH"
      }, {
        "10": "INVALID_UNACCEPTABLE_INVESTOR_ID_SOURCE"
      }, {
        "9": "INVALID_UNACCEPTABLE_INVESTOR_ID"
      }, {
        "8": "INVALID_UNACCEPTABLE_MAILING_INST"
      }, {
        "7": "INVALID_UNACCEPTABLE_MAILING_DTLS"
      }, {
        "5": "INVALID_UNACCEPTABLE_REG_SEQ_NO"
      }, {
        "1": "INVALID_UNACCEPTABLE_ACCOUNT_TYPE"
      }, {
        "18": "INVALID_UNACCEPTABLE_CASH_DISTRIB_AGENT_ACCT_NUM"
      }, {
        "6": "INVALID_UNACCEPTABLE_REG_DTLS"
      }],
      "514": [{
        "2": "CANCEL"
      }, {
        "0": "NEW"
      }, {
        "1": "REPLACE"
      }],
      "519": [{
        "15": "NET_SETTLEMENT_AMOUNT"
      }, {
        "1": "COMMISSION_AMOUNT"
      }, {
        "2": "COMMISSION"
      }, {
        "3": "INITIAL_CHARGE_AMOUNT"
      }, {
        "4": "INITIAL_CHARGE"
      }, {
        "5": "DISCOUNT_AMOUNT"
      }, {
        "6": "DISCOUNT"
      }, {
        "7": "DILUTION_LEVY_AMOUNT"
      }, {
        "8": "DILUTION_LEVY"
      }, {
        "9": "EXIT_CHARGE_AMOUNT"
      }, {
        "10": "EXIT_CHARGE"
      }, {
        "11": "FUND_BASED_RENEWAL_COMMISSION"
      }, {
        "12": "PROJECTED_FUND_VALUE"
      }, {
        "14": "FUND_BASED_RENEWAL_COMMISSION_AMOUNT_14"
      }, {
        "13": "FUND_BASED_RENEWAL_COMMISSION_AMOUNT_13"
      }],
      "522": [{
        "5": "COMPANY_TRUSTEE"
      }, {
        "13": "NOMINEE"
      }, {
        "12": "CORPORATE_BODY"
      }, {
        "11": "NON_PROFIT_ORGANIZATION"
      }, {
        "10": "NETWORKING_SUB_ACCOUNT"
      }, {
        "9": "FIDUCIARIES"
      }, {
        "8": "TRUSTS"
      }, {
        "6": "PENSION_PLAN"
      }, {
        "4": "INDIVIDUAL_TRUSTEE"
      }, {
        "2": "PUBLIC_COMPANY"
      }, {
        "3": "PRIVATE_COMPANY"
      }, {
        "1": "INDIVIDUAL_INVESTOR"
      }, {
        "7": "CUSTODIAN_UNDER_GIFTS_TO_MINORS_ACT"
      }],
      "528": [{
        "R": "RISKLESS_PRINCIPAL"
      }, {
        "I": "INDIVIDUAL"
      }, {
        "P": "PRINCIPAL"
      }, {
        "W": "AGENT_FOR_OTHER_MEMBER"
      }, {
        "A": "AGENCY"
      }, {
        "G": "PROPRIETARY"
      }],
      "529": [{
        "7": "FOREIGN_ENTITY"
      }, {
        "A": "RISKLESS_ARBITRAGE"
      }, {
        "1": "PROGRAM_TRADE"
      }, {
        "8": "EXTERNAL_MARKET_PARTICIPANT"
      }, {
        "6": "ACTING_AS_MARKET_MAKER_OR_SPECIALIST_IN_THE_UNDERLYING_SECURITY_OF_A_DERIVATIVE_SECURITY"
      }, {
        "5": "ACTING_AS_MARKET_MAKER_OR_SPECIALIST_IN_THE_SECURITY"
      }, {
        "3": "NON_INDEX_ARBITRAGE"
      }, {
        "2": "INDEX_ARBITRAGE"
      }, {
        "4": "COMPETING_MARKET_MAKER"
      }, {
        "9": "EXTERNAL_INTER_CONNECTED_MARKET_LINKAGE"
      }],
      "530": [{
        "1": "CANCEL_ORDERS_FOR_A_SECURITY"
      }, {
        "7": "CANCEL_ALL_ORDERS"
      }, {
        "6": "CANCEL_ORDERS_FOR_A_TRADING_SESSION"
      }, {
        "5": "CANCEL_ORDERS_FOR_A_SECURITYTYPE"
      }, {
        "4": "CANCEL_ORDERS_FOR_A_CFICODE"
      }, {
        "2": "CANCEL_ORDERS_FOR_AN_UNDERLYING_SECURITY"
      }, {
        "3": "CANCEL_ORDERS_FOR_A_PRODUCT"
      }],
      "531": [{
        "6": "CANCEL_ORDERS_FOR_A_TRADING_SESSION"
      }, {
        "0": "CANCEL_REQUEST_REJECTED"
      }, {
        "7": "CANCEL_ALL_ORDERS"
      }, {
        "3": "CANCEL_ORDERS_FOR_A_PRODUCT"
      }, {
        "5": "CANCEL_ORDERS_FOR_A_SECURITYTYPE"
      }, {
        "4": "CANCEL_ORDERS_FOR_A_CFICODE"
      }, {
        "1": "CANCEL_ORDERS_FOR_A_SECURITY"
      }, {
        "2": "CANCEL_ORDERS_FOR_AN_UNDERLYING_SECURITY"
      }],
      "532": [{
        "2": "INVALID_OR_UNKNOWN_UNDERLYING"
      }, {
        "6": "INVALID_OR_UNKNOWN_TRADING_SESSION"
      }, {
        "5": "INVALID_OR_UNKNOWN_SECURITY_TYPE"
      }, {
        "3": "INVALID_OR_UNKNOWN_PRODUCT"
      }, {
        "1": "INVALID_OR_UNKNOWN_SECURITY"
      }, {
        "0": "MASS_CANCEL_NOT_SUPPORTED"
      }, {
        "4": "INVALID_OR_UNKNOWN_CFICODE"
      }],
      "537": [{
        "0": "INDICATIVE"
      }, {
        "1": "TRADEABLE"
      }, {
        "2": "RESTRICTED_TRADEABLE"
      }],
      "544": [{
        "2": "MARGIN_OPEN"
      }, {
        "3": "MARGIN_CLOSE"
      }, {
        "1": "CASH"
      }],
      "546": [{
        "1": "LOCAL"
      }, {
        "2": "NATIONAL"
      }, {
        "3": "GLOBAL"
      }],
      "547": [{
        "Y": "YES"
      }, {
        "N": "NO"
      }],
      "549": [{
        "1": "CROSS_TRADE_WHICH_IS_EXECUTED_COMPLETELY_OR_NOT_BOTH_SIDES_ARE_TREATED_IN_THE_SAME_MANNER_THIS_IS_EQUIVALENT_TO_AN_ALL_OR_NONE"
      }, {
        "2": "CROSS_TRADE_WHICH_IS_EXECUTED_PARTIALLY_AND_THE_REST_IS_CANCELLED_ONE_SIDE_IS_FULLY_EXECUTED_THE_OTHER_SIDE_IS_PARTIALLY_EXECUTED_WITH_THE_REMAINDER_BEING_CANCELLED_THIS_IS_EQUIVALENT_TO_AN_IMMEDIATE_OR_CANCEL_ON_THE_OTHER_SIDE"
      }, {
        "3": "CROSS_TRADE_WHICH_IS_PARTIALLY_EXECUTED_WITH_THE_UNFILLED_PORTIONS_REMAINING_ACTIVE_ONE_SIDE_OF_THE_CROSS_IS_FULLY_EXECUTED"
      }, {
        "4": "CROSS_TRADE_IS_EXECUTED_WITH_EXISTING_ORDERS_WITH_THE_SAME_PRICE"
      }],
      "550": [{
        "2": "SELLSIDE_PRIORITIZED"
      }, {
        "0": "NONE"
      }, {
        "1": "BUYSIDE_PRIORITIZED"
      }],
      "552": [{
        "1": "ONE_SIDE"
      }, {
        "2": "BOTH_SIDES"
      }],
      "559": [{
        "1": "SECURITYTYPE_AND_OR_CFICODE"
      }, {
        "2": "PRODUCT"
      }, {
        "3": "TRADINGSESSIONID"
      }, {
        "4": "ALL_SECURITIES"
      }, {
        "0": "SYMBOL"
      }],
      "560": [{
        "4": "INSTRUMENT_DATA_TEMPORARILY_UNAVAILABLE"
      }, {
        "0": "VALID_REQUEST"
      }, {
        "1": "INVALID_OR_UNSUPPORTED_REQUEST"
      }, {
        "5": "REQUEST_FOR_INSTRUMENT_DATA_NOT_SUPPORTED"
      }, {
        "3": "NOT_AUTHORIZED_TO_RETRIEVE_INSTRUMENT_DATA"
      }, {
        "2": "NO_INSTRUMENTS_FOUND_THAT_MATCH_SELECTION_CRITERIA"
      }],
      "567": [{}, {}],
      "569": [{
        "4": "ADVISORIES_THAT_MATCH_CRITERIA"
      }, {
        "3": "UNREPORTED_TRADES_THAT_MATCH_CRITERIA"
      }, {
        "2": "UNMATCHED_TRADES_THAT_MATCH_CRITERIA"
      }, {
        "1": "MATCHED_TRADES_MATCHING_CRITERIA_PROVIDED_ON_REQUEST"
      }, {
        "0": "ALL_TRADES"
      }],
      "570": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "573": [{
        "0": "COMPARED_MATCHED_OR_AFFIRMED"
      }, {
        "1": "UNCOMPARED_UNMATCHED_OR_UNAFFIRMED"
      }, {
        "2": "ADVISORY_OR_ALERT"
      }],
      "574": [{
        "S5": "SUMMARIZED_MATCH_USING_A1_TO_A5_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED_S5"
      }, {
        "M1": "ACT_M1_MATCH"
      }, {
        "M6": "ACT_M6_MATCH"
      }, {
        "M5": "ACT_DEFAULT_AFTER_M2"
      }, {
        "M3": "ACT_ACCEPTED_TRADE"
      }, {
        "S2": "SUMMARIZED_MATCH_USING_A1_TO_A5_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED_S2"
      }, {
        "S3": "SUMMARIZED_MATCH_USING_A1_TO_A5_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED_S3"
      }, {
        "S4": "SUMMARIZED_MATCH_USING_A1_TO_A5_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED_S4"
      }, {
        "M2": "ACT_M2_MATCH"
      }, {
        "A2": "EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_FOUR_BADGES"
      }, {
        "A3": "EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_TWO_BADGES_AND_EXECUTION_TIME"
      }, {
        "A4": "EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND"
      }, {
        "AQ": "COMPARED_RECORDS_RESULTING_FROM_STAMPED_ADVISORIES_OR_SPECIALIST"
      }, {
        "MT": "NON_ACT"
      }, {
        "M4": "ACT_DEFAULT_TRADE"
      }, {
        "A1": "EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_FOUR_BADGES_AND_EXECUTION_TIME"
      }, {
        "S1": "SUMMARIZED_MATCH_USING_A1_TO_A5_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED_S1"
      }, {
        "A5": "EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_EXECUTION_TIME"
      }],
      "577": [{
        "8": "MANUAL_MODE"
      }, {
        "5": "MULTILATERAL_NETTING"
      }, {
        "9": "AUTOMATIC_POSTING_MODE"
      }, {
        "2": "BILATERAL_NETTING_ONLY"
      }, {
        "6": "CLEAR_AGAINST_CENTRAL_COUNTERPARTY"
      }, {
        "10": "AUTOMATIC_GIVE_UP_MODE"
      }, {
        "4": "SPECIAL_TRADE"
      }, {
        "3": "EX_CLEARING"
      }, {
        "0": "PROCESS_NORMALLY"
      }, {
        "7": "EXCLUDE_FROM_CENTRAL_COUNTERPARTY"
      }, {
        "1": "EXCLUDE_FROM_ALL_NETTING"
      }],
      "581": [{
        "3": "HOUSE_TRADER"
      }, {
        "7": "ACCOUNT_IS_HOUSE_TRADER_AND_IS_CROSS_MARGINED"
      }, {
        "6": "ACCOUNT_IS_CARRIED_ON_NON_CUSTOMER_SIDE_OF_BOOKS_AND_IS_CROSS_MARGINED"
      }, {
        "4": "FLOOR_TRADER"
      }, {
        "2": "ACCOUNT_IS_CARRIED_ON_NON_CUSTOMER_SIDE_OF_BOOKS"
      }, {
        "1": "ACCOUNT_IS_CARRIED_ON_CUSTOMER_SIDE_OF_BOOKS"
      }, {
        "8": "JOINT_BACKOFFICE_ACCOUNT"
      }],
      "585": [{
        "1": "STATUS_FOR_ORDERS_FOR_A_SECURITY"
      }, {
        "2": "STATUS_FOR_ORDERS_FOR_AN_UNDERLYING_SECURITY"
      }, {
        "3": "STATUS_FOR_ORDERS_FOR_A_PRODUCT"
      }, {
        "4": "STATUS_FOR_ORDERS_FOR_A_CFICODE"
      }, {
        "5": "STATUS_FOR_ORDERS_FOR_A_SECURITYTYPE"
      }, {
        "6": "STATUS_FOR_ORDERS_FOR_A_TRADING_SESSION"
      }, {
        "8": "STATUS_FOR_ORDERS_FOR_A_PARTYID"
      }, {
        "7": "STATUS_FOR_ALL_ORDERS"
      }],
      "589": [{
        "0": "CAN_TRIGGER_BOOKING_WITHOUT_REFERENCE_TO_THE_ORDER_INITIATOR"
      }, {
        "1": "SPEAK_WITH_ORDER_INITIATOR_BEFORE_BOOKING"
      }],
      "590": [{
        "1": "AGGREGATE_PARTIAL_EXECUTIONS_ON_THIS_ORDER_AND_BOOK_ONE_TRADE_PER_ORDER"
      }, {
        "2": "AGGREGATE_EXECUTIONS_FOR_THIS_SYMBOL_SIDE_AND_SETTLEMENT_DATE"
      }, {
        "0": "EACH_PARTIAL_EXECUTION_IS_A_BOOKABLE_UNIT"
      }],
      "591": [{
        "0": "PRO_RATA"
      }, {
        "1": "DO_NOT_PRO_RATA_DISCUSS_FIRST"
      }],
      "626": [{
        "6": "BUYSIDE_READY_TO_BOOK_6"
      }, {
        "2": "BUYSIDE_PRELIMINARY"
      }, {
        "3": "SELLSIDE_CALCULATED_USING_PRELIMINARY"
      }, {
        "5": "BUYSIDE_READY_TO_BOOK_5"
      }, {
        "1": "BUYSIDE_CALCULATED"
      }, {
        "4": "SELLSIDE_CALCULATED_WITHOUT_PRELIMINARY"
      }],
      "635": [{
        "H": "106H_AND_106J_FIRMS"
      }, {
        "5": "5TH_YEAR_DELEGATE_TRADING_FOR_HIS_OWN_ACCOUNT"
      }, {
        "4": "4TH_YEAR_DELEGATE_TRADING_FOR_HIS_OWN_ACCOUNT"
      }, {
        "3": "3RD_YEAR_DELEGATE_TRADING_FOR_HIS_OWN_ACCOUNT"
      }, {
        "2": "2ND_YEAR_DELEGATE_TRADING_FOR_HIS_OWN_ACCOUNT"
      }, {
        "1": "1ST_YEAR_DELEGATE_TRADING_FOR_HIS_OWN_ACCOUNT"
      }, {
        "M": "ALL_OTHER_OWNERSHIP_TYPES"
      }, {
        "I": "GIM_IDEM_AND_COM_MEMBERSHIP_INTEREST_HOLDERS"
      }, {
        "9": "6TH_YEAR_AND_BEYOND_DELEGATE_TRADING_FOR_HIS_OWN_ACCOUNT"
      }, {
        "F": "FULL_AND_ASSOCIATE_MEMBER_TRADING_FOR_OWN_ACCOUNT_AND_AS_FLOOR"
      }, {
        "E": "EQUITY_MEMBER_AND_CLEARING_MEMBER"
      }, {
        "C": "NON_MEMBER_AND_CUSTOMER"
      }, {
        "B": "CBOE_MEMBER"
      }, {
        "L": "LESSEE_AND_106F_EMPLOYEES"
      }],
      "636": [{
        "N": "NO"
      }, {
        "Y": "YES"
      }],
      "638": [{
        "0": "PRIORITY_UNCHANGED"
      }, {
        "1": "LOST_PRIORITY_AS_RESULT_OF_ORDER_CHANGE"
      }],
      "650": [{
        "Y": "YES"
      }, {
        "N": "NO"
      }],
      "658": [{
        "1": "UNKNOWN_SYMBOL"
      }, {
        "2": "EXCHANGE"
      }, {
        "3": "QUOTE_REQUEST_EXCEEDS_LIMIT"
      }, {
        "4": "TOO_LATE_TO_ENTER"
      }, {
        "5": "INVALID_PRICE"
      }, {
        "6": "NOT_AUTHORIZED_TO_REQUEST_QUOTE"
      }]
    }
  }
};