module.exports = {
  "version": "FIX.4.1",
  "header": {
    "field": [{
      "name": "BeginString",
      "required": "Y"
    }, {
      "name": "BodyLength",
      "required": "Y"
    }, {
      "name": "MsgType",
      "required": "Y"
    }, {
      "name": "SenderCompID",
      "required": "Y"
    }, {
      "name": "TargetCompID",
      "required": "Y"
    }, {
      "name": "OnBehalfOfCompID",
      "required": "N"
    }, {
      "name": "DeliverToCompID",
      "required": "N"
    }, {
      "name": "SecureDataLen",
      "required": "N"
    }, {
      "name": "SecureData",
      "required": "N"
    }, {
      "name": "MsgSeqNum",
      "required": "Y"
    }, {
      "name": "SenderSubID",
      "required": "N"
    }, {
      "name": "SenderLocationID",
      "required": "N"
    }, {
      "name": "TargetSubID",
      "required": "N"
    }, {
      "name": "TargetLocationID",
      "required": "N"
    }, {
      "name": "OnBehalfOfSubID",
      "required": "N"
    }, {
      "name": "OnBehalfOfLocationID",
      "required": "N"
    }, {
      "name": "DeliverToSubID",
      "required": "N"
    }, {
      "name": "DeliverToLocationID",
      "required": "N"
    }, {
      "name": "PossDupFlag",
      "required": "N"
    }, {
      "name": "PossResend",
      "required": "N"
    }, {
      "name": "SendingTime",
      "required": "Y"
    }, {
      "name": "OrigSendingTime",
      "required": "N"
    }]
  },
  "messages": {
    "message": [{
      "field": {
        "name": "TestReqID",
        "required": "N"
      },
      "name": "Heartbeat",
      "msgtype": "0",
      "msgcat": "admin"
    }, {
      "field": {
        "name": "TestReqID",
        "required": "Y"
      },
      "name": "TestRequest",
      "msgtype": "1",
      "msgcat": "admin"
    }, {
      "field": [{
        "name": "BeginSeqNo",
        "required": "Y"
      }, {
        "name": "EndSeqNo",
        "required": "Y"
      }],
      "name": "ResendRequest",
      "msgtype": "2",
      "msgcat": "admin"
    }, {
      "field": [{
        "name": "RefSeqNum",
        "required": "Y"
      }, {
        "name": "Text",
        "required": "N"
      }],
      "name": "Reject",
      "msgtype": "3",
      "msgcat": "admin"
    }, {
      "field": [{
        "name": "GapFillFlag",
        "required": "N"
      }, {
        "name": "NewSeqNo",
        "required": "Y"
      }],
      "name": "SequenceReset",
      "msgtype": "4",
      "msgcat": "admin"
    }, {
      "field": {
        "name": "Text",
        "required": "N"
      },
      "name": "Logout",
      "msgtype": "5",
      "msgcat": "admin"
    }, {
      "field": [{
        "name": "IOIid",
        "required": "Y"
      }, {
        "name": "IOITransType",
        "required": "Y"
      }, {
        "name": "IOIRefID",
        "required": "N"
      }, {
        "name": "Symbol",
        "required": "Y"
      }, {
        "name": "SymbolSfx",
        "required": "N"
      }, {
        "name": "SecurityID",
        "required": "N"
      }, {
        "name": "IDSource",
        "required": "N"
      }, {
        "name": "SecurityType",
        "required": "N"
      }, {
        "name": "MaturityMonthYear",
        "required": "N"
      }, {
        "name": "MaturityDay",
        "required": "N"
      }, {
        "name": "PutOrCall",
        "required": "N"
      }, {
        "name": "StrikePrice",
        "required": "N"
      }, {
        "name": "OptAttribute",
        "required": "N"
      }, {
        "name": "SecurityExchange",
        "required": "N"
      }, {
        "name": "Issuer",
        "required": "N"
      }, {
        "name": "SecurityDesc",
        "required": "N"
      }, {
        "name": "Side",
        "required": "Y"
      }, {
        "name": "IOIShares",
        "required": "Y"
      }, {
        "name": "Price",
        "required": "N"
      }, {
        "name": "Currency",
        "required": "N"
      }, {
        "name": "ValidUntilTime",
        "required": "N"
      }, {
        "name": "IOIQltyInd",
        "required": "N"
      }, {
        "name": "IOIOthSvc",
        "required": "N"
      }, {
        "name": "IOINaturalFlag",
        "required": "N"
      }, {
        "name": "Text",
        "required": "N"
      }, {
        "name": "TransactTime",
        "required": "N"
      }, {
        "name": "URLLink",
        "required": "N"
      }],
      "group": {
        "field": {
          "name": "IOIQualifier",
          "required": "N"
        },
        "name": "NoIOIQualifiers",
        "required": "N"
      },
      "name": "IOI",
      "msgtype": "6",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "AdvId",
        "required": "Y"
      }, {
        "name": "AdvTransType",
        "required": "Y"
      }, {
        "name": "AdvRefID",
        "required": "N"
      }, {
        "name": "Symbol",
        "required": "Y"
      }, {
        "name": "SymbolSfx",
        "required": "N"
      }, {
        "name": "SecurityID",
        "required": "N"
      }, {
        "name": "IDSource",
        "required": "N"
      }, {
        "name": "SecurityType",
        "required": "N"
      }, {
        "name": "MaturityMonthYear",
        "required": "N"
      }, {
        "name": "MaturityDay",
        "required": "N"
      }, {
        "name": "PutOrCall",
        "required": "N"
      }, {
        "name": "StrikePrice",
        "required": "N"
      }, {
        "name": "OptAttribute",
        "required": "N"
      }, {
        "name": "SecurityExchange",
        "required": "N"
      }, {
        "name": "Issuer",
        "required": "N"
      }, {
        "name": "SecurityDesc",
        "required": "N"
      }, {
        "name": "AdvSide",
        "required": "Y"
      }, {
        "name": "Shares",
        "required": "Y"
      }, {
        "name": "Price",
        "required": "N"
      }, {
        "name": "Currency",
        "required": "N"
      }, {
        "name": "TradeDate",
        "required": "N"
      }, {
        "name": "TransactTime",
        "required": "N"
      }, {
        "name": "Text",
        "required": "N"
      }, {
        "name": "URLLink",
        "required": "N"
      }, {
        "name": "LastMkt",
        "required": "N"
      }],
      "name": "Advertisement",
      "msgtype": "7",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "OrderID",
        "required": "Y"
      }, {
        "name": "SecondaryOrderID",
        "required": "N"
      }, {
        "name": "ClOrdID",
        "required": "N"
      }, {
        "name": "OrigClOrdID",
        "required": "N"
      }, {
        "name": "ClientID",
        "required": "N"
      }, {
        "name": "ExecBroker",
        "required": "N"
      }, {
        "name": "ListID",
        "required": "N"
      }, {
        "name": "ExecID",
        "required": "Y"
      }, {
        "name": "ExecTransType",
        "required": "Y"
      }, {
        "name": "ExecRefID",
        "required": "N"
      }, {
        "name": "ExecType",
        "required": "Y"
      }, {
        "name": "OrdStatus",
        "required": "Y"
      }, {
        "name": "OrdRejReason",
        "required": "N"
      }, {
        "name": "Account",
        "required": "N"
      }, {
        "name": "SettlmntTyp",
        "required": "N"
      }, {
        "name": "FutSettDate",
        "required": "N"
      }, {
        "name": "Symbol",
        "required": "Y"
      }, {
        "name": "SymbolSfx",
        "required": "N"
      }, {
        "name": "SecurityID",
        "required": "N"
      }, {
        "name": "IDSource",
        "required": "N"
      }, {
        "name": "SecurityType",
        "required": "N"
      }, {
        "name": "MaturityMonthYear",
        "required": "N"
      }, {
        "name": "MaturityDay",
        "required": "N"
      }, {
        "name": "PutOrCall",
        "required": "N"
      }, {
        "name": "StrikePrice",
        "required": "N"
      }, {
        "name": "OptAttribute",
        "required": "N"
      }, {
        "name": "SecurityExchange",
        "required": "N"
      }, {
        "name": "Issuer",
        "required": "N"
      }, {
        "name": "SecurityDesc",
        "required": "N"
      }, {
        "name": "Side",
        "required": "Y"
      }, {
        "name": "OrderQty",
        "required": "Y"
      }, {
        "name": "OrdType",
        "required": "N"
      }, {
        "name": "Price",
        "required": "N"
      }, {
        "name": "StopPx",
        "required": "N"
      }, {
        "name": "PegDifference",
        "required": "N"
      }, {
        "name": "Currency",
        "required": "N"
      }, {
        "name": "TimeInForce",
        "required": "N"
      }, {
        "name": "ExpireTime",
        "required": "N"
      }, {
        "name": "ExecInst",
        "required": "N"
      }, {
        "name": "Rule80A",
        "required": "N"
      }, {
        "name": "LastShares",
        "required": "Y"
      }, {
        "name": "LastPx",
        "required": "Y"
      }, {
        "name": "LastSpotRate",
        "required": "N"
      }, {
        "name": "LastForwardPoints",
        "required": "N"
      }, {
        "name": "LastMkt",
        "required": "N"
      }, {
        "name": "LastCapacity",
        "required": "N"
      }, {
        "name": "LeavesQty",
        "required": "Y"
      }, {
        "name": "CumQty",
        "required": "Y"
      }, {
        "name": "AvgPx",
        "required": "Y"
      }, {
        "name": "TradeDate",
        "required": "N"
      }, {
        "name": "TransactTime",
        "required": "N"
      }, {
        "name": "ReportToExch",
        "required": "N"
      }, {
        "name": "Commission",
        "required": "N"
      }, {
        "name": "CommType",
        "required": "N"
      }, {
        "name": "SettlCurrAmt",
        "required": "N"
      }, {
        "name": "SettlCurrency",
        "required": "N"
      }, {
        "name": "SettlCurrFxRate",
        "required": "N"
      }, {
        "name": "SettlCurrFxRateCalc",
        "required": "N"
      }, {
        "name": "Text",
        "required": "N"
      }],
      "name": "ExecutionReport",
      "msgtype": "8",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "OrderID",
        "required": "Y"
      }, {
        "name": "SecondaryOrderID",
        "required": "N"
      }, {
        "name": "ClOrdID",
        "required": "Y"
      }, {
        "name": "OrigClOrdID",
        "required": "Y"
      }, {
        "name": "OrdStatus",
        "required": "Y"
      }, {
        "name": "ClientID",
        "required": "N"
      }, {
        "name": "ExecBroker",
        "required": "N"
      }, {
        "name": "ListID",
        "required": "N"
      }, {
        "name": "CxlRejReason",
        "required": "N"
      }, {
        "name": "Text",
        "required": "N"
      }],
      "name": "OrderCancelReject",
      "msgtype": "9",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "EncryptMethod",
        "required": "Y"
      }, {
        "name": "HeartBtInt",
        "required": "Y"
      }, {
        "name": "RawDataLength",
        "required": "N"
      }, {
        "name": "RawData",
        "required": "N"
      }, {
        "name": "ResetSeqNumFlag",
        "required": "N"
      }],
      "name": "Logon",
      "msgtype": "A",
      "msgcat": "admin"
    }, {
      "field": [{
        "name": "OrigTime",
        "required": "N"
      }, {
        "name": "Urgency",
        "required": "N"
      }, {
        "name": "Headline",
        "required": "Y"
      }, {
        "name": "URLLink",
        "required": "N"
      }, {
        "name": "RawDataLength",
        "required": "N"
      }, {
        "name": "RawData",
        "required": "N"
      }],
      "group": [{
        "field": [{
          "name": "RelatdSym",
          "required": "N"
        }, {
          "name": "SymbolSfx",
          "required": "N"
        }, {
          "name": "SecurityID",
          "required": "N"
        }, {
          "name": "IDSource",
          "required": "N"
        }, {
          "name": "SecurityType",
          "required": "N"
        }, {
          "name": "MaturityMonthYear",
          "required": "N"
        }, {
          "name": "MaturityDay",
          "required": "N"
        }, {
          "name": "PutOrCall",
          "required": "N"
        }, {
          "name": "StrikePrice",
          "required": "N"
        }, {
          "name": "OptAttribute",
          "required": "N"
        }, {
          "name": "SecurityExchange",
          "required": "N"
        }, {
          "name": "Issuer",
          "required": "N"
        }, {
          "name": "SecurityDesc",
          "required": "N"
        }],
        "name": "NoRelatedSym",
        "required": "N"
      }, {
        "field": {
          "name": "Text",
          "required": "Y"
        },
        "name": "LinesOfText",
        "required": "Y"
      }],
      "name": "News",
      "msgtype": "B",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "EmailThreadID",
        "required": "Y"
      }, {
        "name": "EmailType",
        "required": "Y"
      }, {
        "name": "OrigTime",
        "required": "N"
      }, {
        "name": "Subject",
        "required": "Y"
      }, {
        "name": "OrderID",
        "required": "N"
      }, {
        "name": "ClOrdID",
        "required": "N"
      }, {
        "name": "RawDataLength",
        "required": "N"
      }, {
        "name": "RawData",
        "required": "N"
      }],
      "group": [{
        "field": [{
          "name": "RelatdSym",
          "required": "N"
        }, {
          "name": "SymbolSfx",
          "required": "N"
        }, {
          "name": "SecurityID",
          "required": "N"
        }, {
          "name": "IDSource",
          "required": "N"
        }, {
          "name": "SecurityType",
          "required": "N"
        }, {
          "name": "MaturityMonthYear",
          "required": "N"
        }, {
          "name": "MaturityDay",
          "required": "N"
        }, {
          "name": "PutOrCall",
          "required": "N"
        }, {
          "name": "StrikePrice",
          "required": "N"
        }, {
          "name": "OptAttribute",
          "required": "N"
        }, {
          "name": "SecurityExchange",
          "required": "N"
        }, {
          "name": "Issuer",
          "required": "N"
        }, {
          "name": "SecurityDesc",
          "required": "N"
        }],
        "name": "NoRelatedSym",
        "required": "N"
      }, {
        "field": {
          "name": "Text",
          "required": "Y"
        },
        "name": "LinesOfText",
        "required": "Y"
      }],
      "name": "Email",
      "msgtype": "C",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "ClOrdID",
        "required": "Y"
      }, {
        "name": "ClientID",
        "required": "N"
      }, {
        "name": "ExecBroker",
        "required": "N"
      }, {
        "name": "Account",
        "required": "N"
      }, {
        "name": "SettlmntTyp",
        "required": "N"
      }, {
        "name": "FutSettDate",
        "required": "N"
      }, {
        "name": "HandlInst",
        "required": "Y"
      }, {
        "name": "ExecInst",
        "required": "N"
      }, {
        "name": "MinQty",
        "required": "N"
      }, {
        "name": "MaxFloor",
        "required": "N"
      }, {
        "name": "ExDestination",
        "required": "N"
      }, {
        "name": "ProcessCode",
        "required": "N"
      }, {
        "name": "Symbol",
        "required": "Y"
      }, {
        "name": "SymbolSfx",
        "required": "N"
      }, {
        "name": "SecurityID",
        "required": "N"
      }, {
        "name": "IDSource",
        "required": "N"
      }, {
        "name": "SecurityType",
        "required": "N"
      }, {
        "name": "MaturityMonthYear",
        "required": "N"
      }, {
        "name": "MaturityDay",
        "required": "N"
      }, {
        "name": "PutOrCall",
        "required": "N"
      }, {
        "name": "StrikePrice",
        "required": "N"
      }, {
        "name": "OptAttribute",
        "required": "N"
      }, {
        "name": "SecurityExchange",
        "required": "N"
      }, {
        "name": "Issuer",
        "required": "N"
      }, {
        "name": "SecurityDesc",
        "required": "N"
      }, {
        "name": "PrevClosePx",
        "required": "N"
      }, {
        "name": "Side",
        "required": "Y"
      }, {
        "name": "LocateReqd",
        "required": "N"
      }, {
        "name": "OrderQty",
        "required": "N"
      }, {
        "name": "CashOrderQty",
        "required": "N"
      }, {
        "name": "OrdType",
        "required": "Y"
      }, {
        "name": "Price",
        "required": "N"
      }, {
        "name": "StopPx",
        "required": "N"
      }, {
        "name": "Currency",
        "required": "N"
      }, {
        "name": "IOIid",
        "required": "N"
      }, {
        "name": "QuoteID",
        "required": "N"
      }, {
        "name": "TimeInForce",
        "required": "N"
      }, {
        "name": "ExpireTime",
        "required": "N"
      }, {
        "name": "Commission",
        "required": "N"
      }, {
        "name": "CommType",
        "required": "N"
      }, {
        "name": "Rule80A",
        "required": "N"
      }, {
        "name": "ForexReq",
        "required": "N"
      }, {
        "name": "SettlCurrency",
        "required": "N"
      }, {
        "name": "Text",
        "required": "N"
      }, {
        "name": "FutSettDate2",
        "required": "N"
      }, {
        "name": "OrderQty2",
        "required": "N"
      }, {
        "name": "OpenClose",
        "required": "N"
      }, {
        "name": "CoveredOrUncovered",
        "required": "N"
      }, {
        "name": "CustomerOrFirm",
        "required": "N"
      }, {
        "name": "MaxShow",
        "required": "N"
      }, {
        "name": "PegDifference",
        "required": "N"
      }],
      "name": "NewOrderSingle",
      "msgtype": "D",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "ListID",
        "required": "Y"
      }, {
        "name": "WaveNo",
        "required": "N"
      }, {
        "name": "ListSeqNo",
        "required": "Y"
      }, {
        "name": "ListNoOrds",
        "required": "Y"
      }, {
        "name": "ListExecInst",
        "required": "N"
      }, {
        "name": "ClOrdID",
        "required": "Y"
      }, {
        "name": "ClientID",
        "required": "N"
      }, {
        "name": "ExecBroker",
        "required": "N"
      }, {
        "name": "Account",
        "required": "N"
      }, {
        "name": "SettlmntTyp",
        "required": "N"
      }, {
        "name": "FutSettDate",
        "required": "N"
      }, {
        "name": "HandlInst",
        "required": "Y"
      }, {
        "name": "ExecInst",
        "required": "N"
      }, {
        "name": "MinQty",
        "required": "N"
      }, {
        "name": "MaxFloor",
        "required": "N"
      }, {
        "name": "ExDestination",
        "required": "N"
      }, {
        "name": "ProcessCode",
        "required": "N"
      }, {
        "name": "Symbol",
        "required": "Y"
      }, {
        "name": "SymbolSfx",
        "required": "N"
      }, {
        "name": "SecurityID",
        "required": "N"
      }, {
        "name": "IDSource",
        "required": "N"
      }, {
        "name": "SecurityType",
        "required": "N"
      }, {
        "name": "MaturityMonthYear",
        "required": "N"
      }, {
        "name": "MaturityDay",
        "required": "N"
      }, {
        "name": "PutOrCall",
        "required": "N"
      }, {
        "name": "StrikePrice",
        "required": "N"
      }, {
        "name": "OptAttribute",
        "required": "N"
      }, {
        "name": "SecurityExchange",
        "required": "N"
      }, {
        "name": "Issuer",
        "required": "N"
      }, {
        "name": "SecurityDesc",
        "required": "N"
      }, {
        "name": "PrevClosePx",
        "required": "N"
      }, {
        "name": "Side",
        "required": "Y"
      }, {
        "name": "LocateReqd",
        "required": "N"
      }, {
        "name": "OrderQty",
        "required": "Y"
      }, {
        "name": "OrdType",
        "required": "Y"
      }, {
        "name": "Price",
        "required": "N"
      }, {
        "name": "StopPx",
        "required": "N"
      }, {
        "name": "PegDifference",
        "required": "N"
      }, {
        "name": "Currency",
        "required": "N"
      }, {
        "name": "TimeInForce",
        "required": "N"
      }, {
        "name": "ExpireTime",
        "required": "N"
      }, {
        "name": "Commission",
        "required": "N"
      }, {
        "name": "CommType",
        "required": "N"
      }, {
        "name": "Rule80A",
        "required": "N"
      }, {
        "name": "ForexReq",
        "required": "N"
      }, {
        "name": "SettlCurrency",
        "required": "N"
      }, {
        "name": "Text",
        "required": "N"
      }, {
        "name": "FutSettDate2",
        "required": "N"
      }, {
        "name": "OrderQty2",
        "required": "N"
      }, {
        "name": "OpenClose",
        "required": "N"
      }, {
        "name": "CoveredOrUncovered",
        "required": "N"
      }, {
        "name": "CustomerOrFirm",
        "required": "N"
      }, {
        "name": "MaxShow",
        "required": "N"
      }],
      "name": "NewOrderList",
      "msgtype": "E",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "OrigClOrdID",
        "required": "Y"
      }, {
        "name": "OrderID",
        "required": "N"
      }, {
        "name": "ClOrdID",
        "required": "Y"
      }, {
        "name": "ListID",
        "required": "N"
      }, {
        "name": "ClientID",
        "required": "N"
      }, {
        "name": "ExecBroker",
        "required": "N"
      }, {
        "name": "Symbol",
        "required": "Y"
      }, {
        "name": "SymbolSfx",
        "required": "N"
      }, {
        "name": "SecurityID",
        "required": "N"
      }, {
        "name": "IDSource",
        "required": "N"
      }, {
        "name": "SecurityType",
        "required": "N"
      }, {
        "name": "MaturityMonthYear",
        "required": "N"
      }, {
        "name": "MaturityDay",
        "required": "N"
      }, {
        "name": "PutOrCall",
        "required": "N"
      }, {
        "name": "StrikePrice",
        "required": "N"
      }, {
        "name": "OptAttribute",
        "required": "N"
      }, {
        "name": "SecurityExchange",
        "required": "N"
      }, {
        "name": "Issuer",
        "required": "N"
      }, {
        "name": "SecurityDesc",
        "required": "N"
      }, {
        "name": "Side",
        "required": "Y"
      }, {
        "name": "OrderQty",
        "required": "N"
      }, {
        "name": "CashOrderQty",
        "required": "N"
      }, {
        "name": "Text",
        "required": "N"
      }],
      "name": "OrderCancelRequest",
      "msgtype": "F",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "OrderID",
        "required": "N"
      }, {
        "name": "ClientID",
        "required": "N"
      }, {
        "name": "ExecBroker",
        "required": "N"
      }, {
        "name": "OrigClOrdID",
        "required": "Y"
      }, {
        "name": "ClOrdID",
        "required": "Y"
      }, {
        "name": "ListID",
        "required": "N"
      }, {
        "name": "Account",
        "required": "N"
      }, {
        "name": "SettlmntTyp",
        "required": "N"
      }, {
        "name": "FutSettDate",
        "required": "N"
      }, {
        "name": "HandlInst",
        "required": "Y"
      }, {
        "name": "ExecInst",
        "required": "N"
      }, {
        "name": "MinQty",
        "required": "N"
      }, {
        "name": "MaxFloor",
        "required": "N"
      }, {
        "name": "ExDestination",
        "required": "N"
      }, {
        "name": "Symbol",
        "required": "Y"
      }, {
        "name": "SymbolSfx",
        "required": "N"
      }, {
        "name": "SecurityID",
        "required": "N"
      }, {
        "name": "IDSource",
        "required": "N"
      }, {
        "name": "SecurityType",
        "required": "N"
      }, {
        "name": "MaturityMonthYear",
        "required": "N"
      }, {
        "name": "MaturityDay",
        "required": "N"
      }, {
        "name": "PutOrCall",
        "required": "N"
      }, {
        "name": "StrikePrice",
        "required": "N"
      }, {
        "name": "OptAttribute",
        "required": "N"
      }, {
        "name": "SecurityExchange",
        "required": "N"
      }, {
        "name": "Issuer",
        "required": "N"
      }, {
        "name": "SecurityDesc",
        "required": "N"
      }, {
        "name": "Side",
        "required": "Y"
      }, {
        "name": "OrderQty",
        "required": "N"
      }, {
        "name": "CashOrderQty",
        "required": "N"
      }, {
        "name": "OrdType",
        "required": "Y"
      }, {
        "name": "Price",
        "required": "N"
      }, {
        "name": "StopPx",
        "required": "N"
      }, {
        "name": "PegDifference",
        "required": "N"
      }, {
        "name": "Currency",
        "required": "N"
      }, {
        "name": "TimeInForce",
        "required": "N"
      }, {
        "name": "ExpireTime",
        "required": "N"
      }, {
        "name": "Commission",
        "required": "N"
      }, {
        "name": "CommType",
        "required": "N"
      }, {
        "name": "Rule80A",
        "required": "N"
      }, {
        "name": "ForexReq",
        "required": "N"
      }, {
        "name": "SettlCurrency",
        "required": "N"
      }, {
        "name": "Text",
        "required": "N"
      }, {
        "name": "FutSettDate2",
        "required": "N"
      }, {
        "name": "OrderQty2",
        "required": "N"
      }, {
        "name": "OpenClose",
        "required": "N"
      }, {
        "name": "CoveredOrUncovered",
        "required": "N"
      }, {
        "name": "CustomerOrFirm",
        "required": "N"
      }, {
        "name": "MaxShow",
        "required": "N"
      }, {
        "name": "LocateReqd",
        "required": "N"
      }],
      "name": "OrderCancelReplaceRequest",
      "msgtype": "G",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "OrderID",
        "required": "N"
      }, {
        "name": "ClOrdID",
        "required": "Y"
      }, {
        "name": "ClientID",
        "required": "N"
      }, {
        "name": "ExecBroker",
        "required": "N"
      }, {
        "name": "Symbol",
        "required": "Y"
      }, {
        "name": "SymbolSfx",
        "required": "N"
      }, {
        "name": "SecurityID",
        "required": "N"
      }, {
        "name": "IDSource",
        "required": "N"
      }, {
        "name": "SecurityType",
        "required": "N"
      }, {
        "name": "MaturityMonthYear",
        "required": "N"
      }, {
        "name": "MaturityDay",
        "required": "N"
      }, {
        "name": "PutOrCall",
        "required": "N"
      }, {
        "name": "StrikePrice",
        "required": "N"
      }, {
        "name": "OptAttribute",
        "required": "N"
      }, {
        "name": "SecurityExchange",
        "required": "N"
      }, {
        "name": "Issuer",
        "required": "N"
      }, {
        "name": "SecurityDesc",
        "required": "N"
      }, {
        "name": "Side",
        "required": "Y"
      }],
      "name": "OrderStatusRequest",
      "msgtype": "H",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "AllocID",
        "required": "Y"
      }, {
        "name": "AllocTransType",
        "required": "Y"
      }, {
        "name": "RefAllocID",
        "required": "N"
      }, {
        "name": "AllocLinkID",
        "required": "N"
      }, {
        "name": "AllocLinkType",
        "required": "N"
      }, {
        "name": "Side",
        "required": "Y"
      }, {
        "name": "Symbol",
        "required": "Y"
      }, {
        "name": "SymbolSfx",
        "required": "N"
      }, {
        "name": "SecurityID",
        "required": "N"
      }, {
        "name": "IDSource",
        "required": "N"
      }, {
        "name": "SecurityType",
        "required": "N"
      }, {
        "name": "MaturityMonthYear",
        "required": "N"
      }, {
        "name": "MaturityDay",
        "required": "N"
      }, {
        "name": "PutOrCall",
        "required": "N"
      }, {
        "name": "StrikePrice",
        "required": "N"
      }, {
        "name": "OptAttribute",
        "required": "N"
      }, {
        "name": "SecurityExchange",
        "required": "N"
      }, {
        "name": "Issuer",
        "required": "N"
      }, {
        "name": "SecurityDesc",
        "required": "N"
      }, {
        "name": "Shares",
        "required": "Y"
      }, {
        "name": "LastMkt",
        "required": "N"
      }, {
        "name": "AvgPx",
        "required": "Y"
      }, {
        "name": "Currency",
        "required": "N"
      }, {
        "name": "AvgPrxPrecision",
        "required": "N"
      }, {
        "name": "TradeDate",
        "required": "Y"
      }, {
        "name": "TransactTime",
        "required": "N"
      }, {
        "name": "SettlmntTyp",
        "required": "N"
      }, {
        "name": "FutSettDate",
        "required": "N"
      }, {
        "name": "NetMoney",
        "required": "N"
      }, {
        "name": "OpenClose",
        "required": "N"
      }, {
        "name": "Text",
        "required": "N"
      }, {
        "name": "NumDaysInterest",
        "required": "N"
      }, {
        "name": "AccruedInterestRate",
        "required": "N"
      }],
      "group": [{
        "field": [{
          "name": "ClOrdID",
          "required": "N"
        }, {
          "name": "OrderID",
          "required": "N"
        }, {
          "name": "SecondaryOrderID",
          "required": "N"
        }, {
          "name": "ListID",
          "required": "N"
        }, {
          "name": "WaveNo",
          "required": "N"
        }],
        "name": "NoOrders",
        "required": "N"
      }, {
        "field": [{
          "name": "LastShares",
          "required": "N"
        }, {
          "name": "ExecID",
          "required": "N"
        }, {
          "name": "LastPx",
          "required": "N"
        }, {
          "name": "LastCapacity",
          "required": "N"
        }],
        "name": "NoExecs",
        "required": "N"
      }, {
        "field": [{
          "name": "AllocAccount",
          "required": "N"
        }, {
          "name": "AllocShares",
          "required": "Y"
        }, {
          "name": "ProcessCode",
          "required": "N"
        }, {
          "name": "BrokerOfCredit",
          "required": "N"
        }, {
          "name": "NotifyBrokerOfCredit",
          "required": "N"
        }, {
          "name": "AllocHandlInst",
          "required": "N"
        }, {
          "name": "AllocText",
          "required": "N"
        }, {
          "name": "ExecBroker",
          "required": "N"
        }, {
          "name": "ClientID",
          "required": "N"
        }, {
          "name": "Commission",
          "required": "N"
        }, {
          "name": "CommType",
          "required": "N"
        }, {
          "name": "AllocAvgPx",
          "required": "N"
        }, {
          "name": "AllocNetMoney",
          "required": "N"
        }, {
          "name": "SettlCurrAmt",
          "required": "N"
        }, {
          "name": "SettlCurrency",
          "required": "N"
        }, {
          "name": "SettlCurrFxRate",
          "required": "N"
        }, {
          "name": "SettlCurrFxRateCalc",
          "required": "N"
        }, {
          "name": "AccruedInterestAmt",
          "required": "N"
        }, {
          "name": "SettlInstMode",
          "required": "N"
        }],
        "group": {
          "field": [{
            "name": "MiscFeeAmt",
            "required": "N"
          }, {
            "name": "MiscFeeCurr",
            "required": "N"
          }, {
            "name": "MiscFeeType",
            "required": "N"
          }],
          "name": "NoMiscFees",
          "required": "N"
        },
        "name": "NoAllocs",
        "required": "N"
      }],
      "name": "Allocation",
      "msgtype": "J",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "ListID",
        "required": "Y"
      }, {
        "name": "WaveNo",
        "required": "N"
      }, {
        "name": "Text",
        "required": "N"
      }],
      "name": "ListCancelRequest",
      "msgtype": "K",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "ListID",
        "required": "Y"
      }, {
        "name": "WaveNo",
        "required": "N"
      }, {
        "name": "Text",
        "required": "N"
      }],
      "name": "ListExecute",
      "msgtype": "L",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "ListID",
        "required": "Y"
      }, {
        "name": "WaveNo",
        "required": "N"
      }, {
        "name": "Text",
        "required": "N"
      }],
      "name": "ListStatusRequest",
      "msgtype": "M",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "ListID",
        "required": "Y"
      }, {
        "name": "WaveNo",
        "required": "N"
      }, {
        "name": "NoRpts",
        "required": "Y"
      }, {
        "name": "RptSeq",
        "required": "Y"
      }],
      "group": {
        "field": [{
          "name": "ClOrdID",
          "required": "Y"
        }, {
          "name": "CumQty",
          "required": "Y"
        }, {
          "name": "LeavesQty",
          "required": "Y"
        }, {
          "name": "CxlQty",
          "required": "Y"
        }, {
          "name": "AvgPx",
          "required": "Y"
        }],
        "name": "NoOrders",
        "required": "Y"
      },
      "name": "ListStatus",
      "msgtype": "N",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "ClientID",
        "required": "N"
      }, {
        "name": "ExecBroker",
        "required": "N"
      }, {
        "name": "AllocID",
        "required": "Y"
      }, {
        "name": "TradeDate",
        "required": "Y"
      }, {
        "name": "TransactTime",
        "required": "N"
      }, {
        "name": "AllocStatus",
        "required": "Y"
      }, {
        "name": "AllocRejCode",
        "required": "N"
      }, {
        "name": "Text",
        "required": "N"
      }],
      "name": "AllocationInstructionAck",
      "msgtype": "P",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "OrderID",
        "required": "N"
      }, {
        "name": "ExecID",
        "required": "N"
      }, {
        "name": "DKReason",
        "required": "Y"
      }, {
        "name": "Symbol",
        "required": "Y"
      }, {
        "name": "SymbolSfx",
        "required": "N"
      }, {
        "name": "SecurityID",
        "required": "N"
      }, {
        "name": "IDSource",
        "required": "N"
      }, {
        "name": "SecurityType",
        "required": "N"
      }, {
        "name": "MaturityMonthYear",
        "required": "N"
      }, {
        "name": "MaturityDay",
        "required": "N"
      }, {
        "name": "PutOrCall",
        "required": "N"
      }, {
        "name": "StrikePrice",
        "required": "N"
      }, {
        "name": "OptAttribute",
        "required": "N"
      }, {
        "name": "SecurityExchange",
        "required": "N"
      }, {
        "name": "Issuer",
        "required": "N"
      }, {
        "name": "SecurityDesc",
        "required": "N"
      }, {
        "name": "Side",
        "required": "Y"
      }, {
        "name": "OrderQty",
        "required": "N"
      }, {
        "name": "CashOrderQty",
        "required": "N"
      }, {
        "name": "LastShares",
        "required": "N"
      }, {
        "name": "LastPx",
        "required": "N"
      }, {
        "name": "Text",
        "required": "N"
      }],
      "name": "DontKnowTrade",
      "msgtype": "Q",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "QuoteReqID",
        "required": "Y"
      }, {
        "name": "Symbol",
        "required": "Y"
      }, {
        "name": "SymbolSfx",
        "required": "N"
      }, {
        "name": "SecurityID",
        "required": "N"
      }, {
        "name": "IDSource",
        "required": "N"
      }, {
        "name": "SecurityType",
        "required": "N"
      }, {
        "name": "MaturityMonthYear",
        "required": "N"
      }, {
        "name": "MaturityDay",
        "required": "N"
      }, {
        "name": "PutOrCall",
        "required": "N"
      }, {
        "name": "StrikePrice",
        "required": "N"
      }, {
        "name": "OptAttribute",
        "required": "N"
      }, {
        "name": "SecurityExchange",
        "required": "N"
      }, {
        "name": "Issuer",
        "required": "N"
      }, {
        "name": "SecurityDesc",
        "required": "N"
      }, {
        "name": "PrevClosePx",
        "required": "N"
      }, {
        "name": "Side",
        "required": "N"
      }, {
        "name": "OrderQty",
        "required": "N"
      }, {
        "name": "FutSettDate",
        "required": "N"
      }, {
        "name": "OrdType",
        "required": "N"
      }, {
        "name": "FutSettDate2",
        "required": "N"
      }, {
        "name": "OrderQty2",
        "required": "N"
      }],
      "name": "QuoteRequest",
      "msgtype": "R",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "QuoteReqID",
        "required": "N"
      }, {
        "name": "QuoteID",
        "required": "Y"
      }, {
        "name": "Symbol",
        "required": "Y"
      }, {
        "name": "SymbolSfx",
        "required": "N"
      }, {
        "name": "SecurityID",
        "required": "N"
      }, {
        "name": "IDSource",
        "required": "N"
      }, {
        "name": "SecurityType",
        "required": "N"
      }, {
        "name": "MaturityMonthYear",
        "required": "N"
      }, {
        "name": "MaturityDay",
        "required": "N"
      }, {
        "name": "PutOrCall",
        "required": "N"
      }, {
        "name": "StrikePrice",
        "required": "N"
      }, {
        "name": "OptAttribute",
        "required": "N"
      }, {
        "name": "SecurityExchange",
        "required": "N"
      }, {
        "name": "Issuer",
        "required": "N"
      }, {
        "name": "SecurityDesc",
        "required": "N"
      }, {
        "name": "BidPx",
        "required": "N"
      }, {
        "name": "OfferPx",
        "required": "N"
      }, {
        "name": "BidSize",
        "required": "N"
      }, {
        "name": "OfferSize",
        "required": "N"
      }, {
        "name": "ValidUntilTime",
        "required": "N"
      }, {
        "name": "BidSpotRate",
        "required": "N"
      }, {
        "name": "OfferSpotRate",
        "required": "N"
      }, {
        "name": "BidForwardPoints",
        "required": "N"
      }, {
        "name": "OfferForwardPoints",
        "required": "N"
      }, {
        "name": "TransactTime",
        "required": "N"
      }, {
        "name": "FutSettDate",
        "required": "N"
      }, {
        "name": "OrdType",
        "required": "N"
      }, {
        "name": "FutSettDate2",
        "required": "N"
      }, {
        "name": "OrderQty2",
        "required": "N"
      }],
      "name": "Quote",
      "msgtype": "S",
      "msgcat": "app"
    }, {
      "field": [{
        "name": "SettlInstID",
        "required": "Y"
      }, {
        "name": "SettlInstTransType",
        "required": "Y"
      }, {
        "name": "SettlInstMode",
        "required": "Y"
      }, {
        "name": "SettlInstSource",
        "required": "Y"
      }, {
        "name": "AllocAccount",
        "required": "Y"
      }, {
        "name": "SettlLocation",
        "required": "N"
      }, {
        "name": "TradeDate",
        "required": "N"
      }, {
        "name": "AllocID",
        "required": "N"
      }, {
        "name": "LastMkt",
        "required": "N"
      }, {
        "name": "Side",
        "required": "N"
      }, {
        "name": "SecurityType",
        "required": "N"
      }, {
        "name": "EffectiveTime",
        "required": "N"
      }, {
        "name": "TransactTime",
        "required": "Y"
      }, {
        "name": "ClientID",
        "required": "N"
      }, {
        "name": "ExecBroker",
        "required": "N"
      }, {
        "name": "StandInstDbType",
        "required": "N"
      }, {
        "name": "StandInstDbName",
        "required": "N"
      }, {
        "name": "StandInstDbID",
        "required": "N"
      }, {
        "name": "SettlDeliveryType",
        "required": "N"
      }, {
        "name": "SettlDepositoryCode",
        "required": "N"
      }, {
        "name": "SettlBrkrCode",
        "required": "N"
      }, {
        "name": "SettlInstCode",
        "required": "N"
      }, {
        "name": "SecuritySettlAgentName",
        "required": "N"
      }, {
        "name": "SecuritySettlAgentCode",
        "required": "N"
      }, {
        "name": "SecuritySettlAgentAcctNum",
        "required": "N"
      }, {
        "name": "SecuritySettlAgentAcctName",
        "required": "N"
      }, {
        "name": "SecuritySettlAgentContactName",
        "required": "N"
      }, {
        "name": "SecuritySettlAgentContactPhone",
        "required": "N"
      }, {
        "name": "CashSettlAgentName",
        "required": "N"
      }, {
        "name": "CashSettlAgentCode",
        "required": "N"
      }, {
        "name": "CashSettlAgentAcctNum",
        "required": "N"
      }, {
        "name": "CashSettlAgentAcctName",
        "required": "N"
      }, {
        "name": "CashSettlAgentContactName",
        "required": "N"
      }, {
        "name": "CashSettlAgentContactPhone",
        "required": "N"
      }],
      "name": "SettlementInstructions",
      "msgtype": "T",
      "msgcat": "app"
    }]
  },
  "trailer": {
    "field": [{
      "name": "SignatureLength",
      "required": "N"
    }, {
      "name": "Signature",
      "required": "N"
    }, {
      "name": "CheckSum",
      "required": "Y"
    }]
  },
  "components": "",
  "fields": {
    "field": [{
      "number": "1",
      "name": "Account",
      "type": "CHAR"
    }, {
      "number": "2",
      "name": "AdvId",
      "type": "CHAR"
    }, {
      "number": "3",
      "name": "AdvRefID",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "B",
        "description": "BUY"
      }, {
        "enum": "S",
        "description": "SELL"
      }, {
        "enum": "T",
        "description": "TRADE"
      }, {
        "enum": "X",
        "description": "CROSS"
      }],
      "number": "4",
      "name": "AdvSide",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "C",
        "description": "CANCEL"
      }, {
        "enum": "N",
        "description": "NEW"
      }, {
        "enum": "R",
        "description": "REPLACE"
      }],
      "number": "5",
      "name": "AdvTransType",
      "type": "CHAR"
    }, {
      "number": "6",
      "name": "AvgPx",
      "type": "FLOAT"
    }, {
      "number": "7",
      "name": "BeginSeqNo",
      "type": "INT"
    }, {
      "number": "8",
      "name": "BeginString",
      "type": "CHAR"
    }, {
      "number": "9",
      "name": "BodyLength",
      "type": "INT"
    }, {
      "number": "10",
      "name": "CheckSum",
      "type": "CHAR"
    }, {
      "number": "11",
      "name": "ClOrdID",
      "type": "CHAR"
    }, {
      "number": "12",
      "name": "Commission",
      "type": "FLOAT"
    }, {
      "value": [{
        "enum": "1",
        "description": "PER_SHARE"
      }, {
        "enum": "2",
        "description": "PERCENTAGE"
      }, {
        "enum": "3",
        "description": "ABSOLUTE"
      }],
      "number": "13",
      "name": "CommType",
      "type": "CHAR"
    }, {
      "number": "14",
      "name": "CumQty",
      "type": "INT"
    }, {
      "number": "15",
      "name": "Currency",
      "type": "CHAR"
    }, {
      "number": "16",
      "name": "EndSeqNo",
      "type": "INT"
    }, {
      "number": "17",
      "name": "ExecID",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "0",
        "description": "STAY_ON_OFFERSIDE"
      }, {
        "enum": "1",
        "description": "NOT_HELD"
      }, {
        "enum": "2",
        "description": "WORK"
      }, {
        "enum": "3",
        "description": "GO_ALONG"
      }, {
        "enum": "4",
        "description": "OVER_THE_DAY"
      }, {
        "enum": "5",
        "description": "HELD"
      }, {
        "enum": "6",
        "description": "PARTICIPATE_DONT_INITIATE"
      }, {
        "enum": "7",
        "description": "STRICT_SCALE"
      }, {
        "enum": "8",
        "description": "TRY_TO_SCALE"
      }, {
        "enum": "9",
        "description": "STAY_ON_BIDSIDE"
      }, {
        "enum": "A",
        "description": "NO_CROSS"
      }, {
        "enum": "B",
        "description": "OK_TO_CROSS"
      }, {
        "enum": "C",
        "description": "CALL_FIRST"
      }, {
        "enum": "D",
        "description": "PERCENT_OF_VOLUME"
      }, {
        "enum": "E",
        "description": "DO_NOT_INCREASE"
      }, {
        "enum": "F",
        "description": "DO_NOT_REDUCE"
      }, {
        "enum": "G",
        "description": "ALL_OR_NONE"
      }, {
        "enum": "I",
        "description": "INSTITUTIONS_ONLY"
      }, {
        "enum": "L",
        "description": "LAST_PEG"
      }, {
        "enum": "M",
        "description": "MID_PRICE_PEG"
      }, {
        "enum": "N",
        "description": "NON_NEGOTIABLE"
      }, {
        "enum": "O",
        "description": "OPENING_PEG"
      }, {
        "enum": "P",
        "description": "MARKET_PEG"
      }, {
        "enum": "R",
        "description": "PRIMARY_PEG"
      }, {
        "enum": "S",
        "description": "SUSPEND"
      }, {
        "enum": "U",
        "description": "CUSTOMER_DISPLAY_INSTRUCTION"
      }, {
        "enum": "V",
        "description": "NETTING"
      }],
      "number": "18",
      "name": "ExecInst",
      "type": "CHAR"
    }, {
      "number": "19",
      "name": "ExecRefID",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "0",
        "description": "NEW"
      }, {
        "enum": "1",
        "description": "CANCEL"
      }, {
        "enum": "2",
        "description": "CORRECT"
      }, {
        "enum": "3",
        "description": "STATUS"
      }],
      "number": "20",
      "name": "ExecTransType",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "1",
        "description": "AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION"
      }, {
        "enum": "2",
        "description": "AUTOMATED_EXECUTION_ORDER_PUBLIC_BROKER_INTERVENTION_OK"
      }, {
        "enum": "3",
        "description": "MANUAL_ORDER_BEST_EXECUTION"
      }],
      "number": "21",
      "name": "HandlInst",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "1",
        "description": "CUSIP"
      }, {
        "enum": "2",
        "description": "SEDOL"
      }, {
        "enum": "3",
        "description": "QUIK"
      }, {
        "enum": "4",
        "description": "ISIN_NUMBER"
      }, {
        "enum": "5",
        "description": "RIC_CODE"
      }, {
        "enum": "6",
        "description": "ISO_CURRENCY_CODE"
      }, {
        "enum": "7",
        "description": "ISO_COUNTRY_CODE"
      }],
      "number": "22",
      "name": "IDSource",
      "type": "CHAR"
    }, {
      "number": "23",
      "name": "IOIid",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "A",
        "description": "AUTEX"
      }, {
        "enum": "B",
        "description": "BRIDGE"
      }],
      "number": "24",
      "name": "IOIOthSvc",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "H",
        "description": "HIGH"
      }, {
        "enum": "L",
        "description": "LOW"
      }, {
        "enum": "M",
        "description": "MEDIUM"
      }],
      "number": "25",
      "name": "IOIQltyInd",
      "type": "CHAR"
    }, {
      "number": "26",
      "name": "IOIRefID",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "L",
        "description": "LARGE"
      }, {
        "enum": "M",
        "description": "MEDIUM"
      }, {
        "enum": "S",
        "description": "SMALL"
      }],
      "number": "27",
      "name": "IOIShares",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "C",
        "description": "CANCEL"
      }, {
        "enum": "N",
        "description": "NEW"
      }, {
        "enum": "R",
        "description": "REPLACE"
      }],
      "number": "28",
      "name": "IOITransType",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "1",
        "description": "AGENT"
      }, {
        "enum": "2",
        "description": "CROSS_AS_AGENT"
      }, {
        "enum": "3",
        "description": "CROSS_AS_PRINCIPAL"
      }, {
        "enum": "4",
        "description": "PRINCIPAL"
      }],
      "number": "29",
      "name": "LastCapacity",
      "type": "CHAR"
    }, {
      "number": "30",
      "name": "LastMkt",
      "type": "CHAR"
    }, {
      "number": "31",
      "name": "LastPx",
      "type": "FLOAT"
    }, {
      "number": "32",
      "name": "LastShares",
      "type": "INT"
    }, {
      "number": "33",
      "name": "LinesOfText",
      "type": "INT"
    }, {
      "number": "34",
      "name": "MsgSeqNum",
      "type": "INT"
    }, {
      "value": [{
        "enum": "0",
        "description": "HEARTBEAT"
      }, {
        "enum": "1",
        "description": "TEST_REQUEST"
      }, {
        "enum": "2",
        "description": "RESEND_REQUEST"
      }, {
        "enum": "3",
        "description": "REJECT"
      }, {
        "enum": "4",
        "description": "SEQUENCE_RESET"
      }, {
        "enum": "5",
        "description": "LOGOUT"
      }, {
        "enum": "6",
        "description": "INDICATION_OF_INTEREST"
      }, {
        "enum": "7",
        "description": "ADVERTISEMENT"
      }, {
        "enum": "8",
        "description": "EXECUTION_REPORT"
      }, {
        "enum": "9",
        "description": "ORDER_CANCEL_REJECT"
      }, {
        "enum": "A",
        "description": "LOGON"
      }, {
        "enum": "B",
        "description": "NEWS"
      }, {
        "enum": "C",
        "description": "EMAIL"
      }, {
        "enum": "D",
        "description": "ORDER_D"
      }, {
        "enum": "E",
        "description": "ORDER_E"
      }, {
        "enum": "F",
        "description": "ORDER_CANCEL_REQUEST"
      }, {
        "enum": "G",
        "description": "ORDER_CANCEL_REPLACE_REQUEST"
      }, {
        "enum": "H",
        "description": "ORDER_STATUS_REQUEST"
      }, {
        "enum": "J",
        "description": "ALLOCATION"
      }, {
        "enum": "K",
        "description": "LIST_CANCEL_REQUEST"
      }, {
        "enum": "L",
        "description": "LIST_EXECUTE"
      }, {
        "enum": "M",
        "description": "LIST_STATUS_REQUEST"
      }, {
        "enum": "N",
        "description": "LIST_STATUS"
      }, {
        "enum": "P",
        "description": "ALLOCATION_ACK"
      }, {
        "enum": "Q",
        "description": "DONT_KNOW_TRADE"
      }, {
        "enum": "R",
        "description": "QUOTE_REQUEST"
      }, {
        "enum": "S",
        "description": "QUOTE"
      }, {
        "enum": "T",
        "description": "SETTLEMENT_INSTRUCTIONS"
      }],
      "number": "35",
      "name": "MsgType",
      "type": "CHAR"
    }, {
      "number": "36",
      "name": "NewSeqNo",
      "type": "INT"
    }, {
      "number": "37",
      "name": "OrderID",
      "type": "CHAR"
    }, {
      "number": "38",
      "name": "OrderQty",
      "type": "INT"
    }, {
      "value": [{
        "enum": "0",
        "description": "NEW"
      }, {
        "enum": "1",
        "description": "PARTIALLY_FILLED"
      }, {
        "enum": "2",
        "description": "FILLED"
      }, {
        "enum": "3",
        "description": "DONE_FOR_DAY"
      }, {
        "enum": "4",
        "description": "CANCELED"
      }, {
        "enum": "5",
        "description": "REPLACED"
      }, {
        "enum": "6",
        "description": "PENDING_CANCEL_REPLACE"
      }, {
        "enum": "7",
        "description": "STOPPED"
      }, {
        "enum": "8",
        "description": "REJECTED"
      }, {
        "enum": "9",
        "description": "SUSPENDED"
      }, {
        "enum": "A",
        "description": "PENDING_NEW"
      }, {
        "enum": "B",
        "description": "CALCULATED"
      }, {
        "enum": "C",
        "description": "EXPIRED"
      }],
      "number": "39",
      "name": "OrdStatus",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "1",
        "description": "MARKET"
      }, {
        "enum": "2",
        "description": "LIMIT"
      }, {
        "enum": "3",
        "description": "STOP"
      }, {
        "enum": "4",
        "description": "STOP_LIMIT"
      }, {
        "enum": "5",
        "description": "MARKET_ON_CLOSE"
      }, {
        "enum": "6",
        "description": "WITH_OR_WITHOUT"
      }, {
        "enum": "7",
        "description": "LIMIT_OR_BETTER"
      }, {
        "enum": "8",
        "description": "LIMIT_WITH_OR_WITHOUT"
      }, {
        "enum": "9",
        "description": "ON_BASIS"
      }, {
        "enum": "A",
        "description": "ON_CLOSE"
      }, {
        "enum": "B",
        "description": "LIMIT_ON_CLOSE"
      }, {
        "enum": "C",
        "description": "FOREX_C"
      }, {
        "enum": "D",
        "description": "PREVIOUSLY_QUOTED"
      }, {
        "enum": "E",
        "description": "PREVIOUSLY_INDICATED"
      }, {
        "enum": "F",
        "description": "FOREX_F"
      }, {
        "enum": "G",
        "description": "FOREX_G"
      }, {
        "enum": "H",
        "description": "FOREX_H"
      }, {
        "enum": "P",
        "description": "PEGGED"
      }],
      "number": "40",
      "name": "OrdType",
      "type": "CHAR"
    }, {
      "number": "41",
      "name": "OrigClOrdID",
      "type": "CHAR"
    }, {
      "number": "42",
      "name": "OrigTime",
      "type": "TIME"
    }, {
      "value": [{
        "enum": "N",
        "description": "NO"
      }, {
        "enum": "Y",
        "description": "YES"
      }],
      "number": "43",
      "name": "PossDupFlag",
      "type": "CHAR"
    }, {
      "number": "44",
      "name": "Price",
      "type": "FLOAT"
    }, {
      "number": "45",
      "name": "RefSeqNum",
      "type": "INT"
    }, {
      "number": "46",
      "name": "RelatdSym",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "A",
        "description": "AGENCY_SINGLE_ORDER"
      }, {
        "enum": "B",
        "description": "SHORT_EXEMPT_TRANSACTION_B"
      }, {
        "enum": "C",
        "description": "PROGRAM_ORDER_NON_INDEX_ARB_FOR_MEMBER_FIRM_ORG"
      }, {
        "enum": "D",
        "description": "PROGRAM_ORDER_INDEX_ARB_FOR_MEMBER_FIRM_ORG"
      }, {
        "enum": "E",
        "description": "REGISTERED_EQUITY_MARKET_MAKER_TRADES"
      }, {
        "enum": "F",
        "description": "SHORT_EXEMPT_TRANSACTION_F"
      }, {
        "enum": "H",
        "description": "SHORT_EXEMPT_TRANSACTION_H"
      }, {
        "enum": "I",
        "description": "INDIVIDUAL_INVESTOR_SINGLE_ORDER"
      }, {
        "enum": "J",
        "description": "PROGRAM_ORDER_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER"
      }, {
        "enum": "K",
        "description": "PROGRAM_ORDER_NON_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER"
      }, {
        "enum": "L",
        "description": "SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE"
      }, {
        "enum": "M",
        "description": "PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_MEMBER"
      }, {
        "enum": "N",
        "description": "PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_MEMBER"
      }, {
        "enum": "O",
        "description": "COMPETING_DEALER_TRADES_O"
      }, {
        "enum": "P",
        "description": "PRINCIPAL"
      }, {
        "enum": "R",
        "description": "COMPETING_DEALER_TRADES_R"
      }, {
        "enum": "S",
        "description": "SPECIALIST_TRADES"
      }, {
        "enum": "T",
        "description": "COMPETING_DEALER_TRADES_T"
      }, {
        "enum": "U",
        "description": "PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_AGENCY"
      }, {
        "enum": "W",
        "description": "ALL_OTHER_ORDERS_AS_AGENT_FOR_OTHER_MEMBER"
      }, {
        "enum": "X",
        "description": "SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_NOT_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE"
      }, {
        "enum": "Y",
        "description": "PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_AGENCY"
      }, {
        "enum": "Z",
        "description": "SHORT_EXEMPT_TRANSACTION_FOR_NON_MEMBER_COMPETING_MARKET_MAKER"
      }],
      "number": "47",
      "name": "Rule80A",
      "type": "CHAR"
    }, {
      "number": "48",
      "name": "SecurityID",
      "type": "CHAR"
    }, {
      "number": "49",
      "name": "SenderCompID",
      "type": "CHAR"
    }, {
      "number": "50",
      "name": "SenderSubID",
      "type": "CHAR"
    }, {
      "number": "52",
      "name": "SendingTime",
      "type": "TIME"
    }, {
      "number": "53",
      "name": "Shares",
      "type": "INT"
    }, {
      "value": [{
        "enum": "1",
        "description": "BUY"
      }, {
        "enum": "2",
        "description": "SELL"
      }, {
        "enum": "3",
        "description": "BUY_MINUS"
      }, {
        "enum": "4",
        "description": "SELL_PLUS"
      }, {
        "enum": "5",
        "description": "SELL_SHORT"
      }, {
        "enum": "6",
        "description": "SELL_SHORT_EXEMPT"
      }, {
        "enum": "7",
        "description": "UNDISCLOSED"
      }, {
        "enum": "8",
        "description": "CROSS"
      }],
      "number": "54",
      "name": "Side",
      "type": "CHAR"
    }, {
      "number": "55",
      "name": "Symbol",
      "type": "CHAR"
    }, {
      "number": "56",
      "name": "TargetCompID",
      "type": "CHAR"
    }, {
      "number": "57",
      "name": "TargetSubID",
      "type": "CHAR"
    }, {
      "number": "58",
      "name": "Text",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "0",
        "description": "DAY"
      }, {
        "enum": "1",
        "description": "GOOD_TILL_CANCEL"
      }, {
        "enum": "2",
        "description": "AT_THE_OPENING"
      }, {
        "enum": "3",
        "description": "IMMEDIATE_OR_CANCEL"
      }, {
        "enum": "4",
        "description": "FILL_OR_KILL"
      }, {
        "enum": "5",
        "description": "GOOD_TILL_CROSSING"
      }, {
        "enum": "6",
        "description": "GOOD_TILL_DATE"
      }],
      "number": "59",
      "name": "TimeInForce",
      "type": "CHAR"
    }, {
      "number": "60",
      "name": "TransactTime",
      "type": "TIME"
    }, {
      "value": [{
        "enum": "0",
        "description": "NORMAL"
      }, {
        "enum": "1",
        "description": "FLASH"
      }, {
        "enum": "2",
        "description": "BACKGROUND"
      }],
      "number": "61",
      "name": "Urgency",
      "type": "CHAR"
    }, {
      "number": "62",
      "name": "ValidUntilTime",
      "type": "TIME"
    }, {
      "value": [{
        "enum": "0",
        "description": "REGULAR"
      }, {
        "enum": "1",
        "description": "CASH"
      }, {
        "enum": "2",
        "description": "NEXT_DAY"
      }, {
        "enum": "3",
        "description": "T_PLUS_2"
      }, {
        "enum": "4",
        "description": "T_PLUS_3"
      }, {
        "enum": "5",
        "description": "T_PLUS_4"
      }, {
        "enum": "6",
        "description": "FUTURE"
      }, {
        "enum": "7",
        "description": "WHEN_ISSUED"
      }, {
        "enum": "8",
        "description": "SELLERS_OPTION"
      }, {
        "enum": "9",
        "description": "T_PLUS_5"
      }],
      "number": "63",
      "name": "SettlmntTyp",
      "type": "CHAR"
    }, {
      "number": "64",
      "name": "FutSettDate",
      "type": "DATE"
    }, {
      "number": "65",
      "name": "SymbolSfx",
      "type": "CHAR"
    }, {
      "number": "66",
      "name": "ListID",
      "type": "CHAR"
    }, {
      "number": "67",
      "name": "ListSeqNo",
      "type": "INT"
    }, {
      "number": "68",
      "name": "ListNoOrds",
      "type": "INT"
    }, {
      "number": "69",
      "name": "ListExecInst",
      "type": "CHAR"
    }, {
      "number": "70",
      "name": "AllocID",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "0",
        "description": "NEW"
      }, {
        "enum": "1",
        "description": "REPLACE"
      }, {
        "enum": "2",
        "description": "CANCEL"
      }, {
        "enum": "3",
        "description": "PRELIMINARY"
      }, {
        "enum": "4",
        "description": "CALCULATED"
      }],
      "number": "71",
      "name": "AllocTransType",
      "type": "CHAR"
    }, {
      "number": "72",
      "name": "RefAllocID",
      "type": "CHAR"
    }, {
      "number": "73",
      "name": "NoOrders",
      "type": "INT"
    }, {
      "number": "74",
      "name": "AvgPrxPrecision",
      "type": "INT"
    }, {
      "number": "75",
      "name": "TradeDate",
      "type": "DATE"
    }, {
      "number": "76",
      "name": "ExecBroker",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "C",
        "description": "CLOSE"
      }, {
        "enum": "O",
        "description": "OPEN"
      }],
      "number": "77",
      "name": "OpenClose",
      "type": "CHAR"
    }, {
      "number": "78",
      "name": "NoAllocs",
      "type": "INT"
    }, {
      "number": "79",
      "name": "AllocAccount",
      "type": "CHAR"
    }, {
      "number": "80",
      "name": "AllocShares",
      "type": "INT"
    }, {
      "value": [{
        "enum": "0",
        "description": "REGULAR"
      }, {
        "enum": "1",
        "description": "SOFT_DOLLAR"
      }, {
        "enum": "2",
        "description": "STEP_IN"
      }, {
        "enum": "3",
        "description": "STEP_OUT"
      }, {
        "enum": "4",
        "description": "SOFT_DOLLAR_STEP_IN"
      }, {
        "enum": "5",
        "description": "SOFT_DOLLAR_STEP_OUT"
      }, {
        "enum": "6",
        "description": "PLAN_SPONSOR"
      }],
      "number": "81",
      "name": "ProcessCode",
      "type": "CHAR"
    }, {
      "number": "82",
      "name": "NoRpts",
      "type": "INT"
    }, {
      "number": "83",
      "name": "RptSeq",
      "type": "INT"
    }, {
      "number": "84",
      "name": "CxlQty",
      "type": "INT"
    }, {
      "value": [{
        "enum": "0",
        "description": "ACCEPTED"
      }, {
        "enum": "1",
        "description": "REJECTED"
      }, {
        "enum": "2",
        "description": "PARTIAL_ACCEPT"
      }, {
        "enum": "3",
        "description": "RECEIVED"
      }],
      "number": "87",
      "name": "AllocStatus",
      "type": "INT"
    }, {
      "value": [{
        "enum": "0",
        "description": "UNKNOWN_ACCOUNT"
      }, {
        "enum": "1",
        "description": "INCORRECT_QUANTITY"
      }, {
        "enum": "2",
        "description": "INCORRECT_AVERAGE_PRICE"
      }, {
        "enum": "3",
        "description": "UNKNOWN_EXECUTING_BROKER_MNEMONIC"
      }, {
        "enum": "4",
        "description": "COMMISSION_DIFFERENCE"
      }, {
        "enum": "5",
        "description": "UNKNOWN_ORDERID"
      }, {
        "enum": "6",
        "description": "UNKNOWN_LISTID"
      }, {
        "enum": "7",
        "description": "OTHER"
      }],
      "number": "88",
      "name": "AllocRejCode",
      "type": "INT"
    }, {
      "number": "89",
      "name": "Signature",
      "type": "DATA"
    }, {
      "number": "90",
      "name": "SecureDataLen",
      "type": "LENGTH"
    }, {
      "number": "91",
      "name": "SecureData",
      "type": "DATA"
    }, {
      "number": "92",
      "name": "BrokerOfCredit",
      "type": "CHAR"
    }, {
      "number": "93",
      "name": "SignatureLength",
      "type": "LENGTH"
    }, {
      "value": [{
        "enum": "0",
        "description": "NEW"
      }, {
        "enum": "1",
        "description": "REPLY"
      }, {
        "enum": "2",
        "description": "ADMIN_REPLY"
      }],
      "number": "94",
      "name": "EmailType",
      "type": "CHAR"
    }, {
      "number": "95",
      "name": "RawDataLength",
      "type": "LENGTH"
    }, {
      "number": "96",
      "name": "RawData",
      "type": "DATA"
    }, {
      "value": [{
        "enum": "N",
        "description": "NO"
      }, {
        "enum": "Y",
        "description": "YES"
      }],
      "number": "97",
      "name": "PossResend",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "0",
        "description": "NONE"
      }, {
        "enum": "1",
        "description": "PKCS"
      }, {
        "enum": "2",
        "description": "DES"
      }, {
        "enum": "3",
        "description": "PKCS_DES"
      }, {
        "enum": "4",
        "description": "PGP_DES"
      }, {
        "enum": "5",
        "description": "PGP_DES_MD5"
      }, {
        "enum": "6",
        "description": "PEM_DES_MD5"
      }],
      "number": "98",
      "name": "EncryptMethod",
      "type": "INT"
    }, {
      "number": "99",
      "name": "StopPx",
      "type": "FLOAT"
    }, {
      "number": "100",
      "name": "ExDestination",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "0",
        "description": "TOO_LATE_TO_CANCEL"
      }, {
        "enum": "1",
        "description": "UNKNOWN_ORDER"
      }],
      "number": "102",
      "name": "CxlRejReason",
      "type": "INT"
    }, {
      "value": [{
        "enum": "0",
        "description": "BROKER_OPTION"
      }, {
        "enum": "1",
        "description": "UNKNOWN_SYMBOL"
      }, {
        "enum": "2",
        "description": "EXCHANGE_CLOSED"
      }, {
        "enum": "3",
        "description": "ORDER_EXCEEDS_LIMIT"
      }, {
        "enum": "4",
        "description": "TOO_LATE_TO_ENTER"
      }, {
        "enum": "5",
        "description": "UNKNOWN_ORDER"
      }, {
        "enum": "6",
        "description": "DUPLICATE_ORDER"
      }],
      "number": "103",
      "name": "OrdRejReason",
      "type": "INT"
    }, {
      "value": [{
        "enum": "A",
        "description": "ALL_OR_NONE"
      }, {
        "enum": "C",
        "description": "AT_THE_CLOSE"
      }, {
        "enum": "I",
        "description": "IN_TOUCH_WITH"
      }, {
        "enum": "L",
        "description": "LIMIT"
      }, {
        "enum": "M",
        "description": "MORE_BEHIND"
      }, {
        "enum": "O",
        "description": "AT_THE_OPEN"
      }, {
        "enum": "P",
        "description": "TAKING_A_POSITION"
      }, {
        "enum": "Q",
        "description": "AT_THE_MARKET"
      }, {
        "enum": "S",
        "description": "PORTFOLIO_SHOW_N"
      }, {
        "enum": "T",
        "description": "THROUGH_THE_DAY"
      }, {
        "enum": "V",
        "description": "VERSUS"
      }, {
        "enum": "W",
        "description": "INDICATION"
      }, {
        "enum": "X",
        "description": "CROSSING_OPPORTUNITY"
      }, {
        "enum": "Y",
        "description": "AT_THE_MIDPOINT"
      }, {
        "enum": "Z",
        "description": "PRE_OPEN"
      }],
      "number": "104",
      "name": "IOIQualifier",
      "type": "CHAR"
    }, {
      "number": "105",
      "name": "WaveNo",
      "type": "CHAR"
    }, {
      "number": "106",
      "name": "Issuer",
      "type": "CHAR"
    }, {
      "number": "107",
      "name": "SecurityDesc",
      "type": "CHAR"
    }, {
      "number": "108",
      "name": "HeartBtInt",
      "type": "INT"
    }, {
      "number": "109",
      "name": "ClientID",
      "type": "CHAR"
    }, {
      "number": "110",
      "name": "MinQty",
      "type": "INT"
    }, {
      "number": "111",
      "name": "MaxFloor",
      "type": "INT"
    }, {
      "number": "112",
      "name": "TestReqID",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "N",
        "description": "NO"
      }, {
        "enum": "Y",
        "description": "YES"
      }],
      "number": "113",
      "name": "ReportToExch",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "N",
        "description": "NO"
      }, {
        "enum": "Y",
        "description": "YES"
      }],
      "number": "114",
      "name": "LocateReqd",
      "type": "CHAR"
    }, {
      "number": "115",
      "name": "OnBehalfOfCompID",
      "type": "CHAR"
    }, {
      "number": "116",
      "name": "OnBehalfOfSubID",
      "type": "CHAR"
    }, {
      "number": "117",
      "name": "QuoteID",
      "type": "CHAR"
    }, {
      "number": "118",
      "name": "NetMoney",
      "type": "FLOAT"
    }, {
      "number": "119",
      "name": "SettlCurrAmt",
      "type": "FLOAT"
    }, {
      "number": "120",
      "name": "SettlCurrency",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "N",
        "description": "NO"
      }, {
        "enum": "Y",
        "description": "YES"
      }],
      "number": "121",
      "name": "ForexReq",
      "type": "CHAR"
    }, {
      "number": "122",
      "name": "OrigSendingTime",
      "type": "TIME"
    }, {
      "value": [{
        "enum": "N",
        "description": "NO"
      }, {
        "enum": "Y",
        "description": "YES"
      }],
      "number": "123",
      "name": "GapFillFlag",
      "type": "CHAR"
    }, {
      "number": "124",
      "name": "NoExecs",
      "type": "INT"
    }, {
      "number": "126",
      "name": "ExpireTime",
      "type": "TIME"
    }, {
      "value": [{
        "enum": "A",
        "description": "UNKNOWN_SYMBOL"
      }, {
        "enum": "B",
        "description": "WRONG_SIDE"
      }, {
        "enum": "C",
        "description": "QUANTITY_EXCEEDS_ORDER"
      }, {
        "enum": "D",
        "description": "NO_MATCHING_ORDER"
      }, {
        "enum": "E",
        "description": "PRICE_EXCEEDS_LIMIT"
      }, {
        "enum": "Z",
        "description": "OTHER"
      }],
      "number": "127",
      "name": "DKReason",
      "type": "CHAR"
    }, {
      "number": "128",
      "name": "DeliverToCompID",
      "type": "CHAR"
    }, {
      "number": "129",
      "name": "DeliverToSubID",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "N",
        "description": "NO"
      }, {
        "enum": "Y",
        "description": "YES"
      }],
      "number": "130",
      "name": "IOINaturalFlag",
      "type": "CHAR"
    }, {
      "number": "131",
      "name": "QuoteReqID",
      "type": "CHAR"
    }, {
      "number": "132",
      "name": "BidPx",
      "type": "FLOAT"
    }, {
      "number": "133",
      "name": "OfferPx",
      "type": "FLOAT"
    }, {
      "number": "134",
      "name": "BidSize",
      "type": "INT"
    }, {
      "number": "135",
      "name": "OfferSize",
      "type": "INT"
    }, {
      "number": "136",
      "name": "NoMiscFees",
      "type": "INT"
    }, {
      "number": "137",
      "name": "MiscFeeAmt",
      "type": "FLOAT"
    }, {
      "number": "138",
      "name": "MiscFeeCurr",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "1",
        "description": "REGULATORY"
      }, {
        "enum": "2",
        "description": "TAX"
      }, {
        "enum": "3",
        "description": "LOCAL_COMMISSION"
      }, {
        "enum": "4",
        "description": "EXCHANGE_FEES"
      }, {
        "enum": "5",
        "description": "STAMP"
      }, {
        "enum": "6",
        "description": "LEVY"
      }, {
        "enum": "7",
        "description": "OTHER"
      }, {
        "enum": "8",
        "description": "MARKUP"
      }],
      "number": "139",
      "name": "MiscFeeType",
      "type": "CHAR"
    }, {
      "number": "140",
      "name": "PrevClosePx",
      "type": "FLOAT"
    }, {
      "value": [{
        "enum": "N",
        "description": "NO"
      }, {
        "enum": "Y",
        "description": "YES"
      }],
      "number": "141",
      "name": "ResetSeqNumFlag",
      "type": "CHAR"
    }, {
      "number": "142",
      "name": "SenderLocationID",
      "type": "CHAR"
    }, {
      "number": "143",
      "name": "TargetLocationID",
      "type": "CHAR"
    }, {
      "number": "144",
      "name": "OnBehalfOfLocationID",
      "type": "CHAR"
    }, {
      "number": "145",
      "name": "DeliverToLocationID",
      "type": "CHAR"
    }, {
      "number": "146",
      "name": "NoRelatedSym",
      "type": "INT"
    }, {
      "number": "147",
      "name": "Subject",
      "type": "CHAR"
    }, {
      "number": "148",
      "name": "Headline",
      "type": "CHAR"
    }, {
      "number": "149",
      "name": "URLLink",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "0",
        "description": "NEW"
      }, {
        "enum": "1",
        "description": "PARTIAL_FILL"
      }, {
        "enum": "2",
        "description": "FILL"
      }, {
        "enum": "3",
        "description": "DONE_FOR_DAY"
      }, {
        "enum": "4",
        "description": "CANCELLED"
      }, {
        "enum": "5",
        "description": "REPLACE"
      }, {
        "enum": "6",
        "description": "PENDING_CANCEL_REPLACE"
      }, {
        "enum": "7",
        "description": "STOPPED"
      }, {
        "enum": "8",
        "description": "REJECTED"
      }, {
        "enum": "9",
        "description": "SUSPENDED"
      }, {
        "enum": "A",
        "description": "PENDING_NEW"
      }, {
        "enum": "B",
        "description": "CALCULATED"
      }, {
        "enum": "C",
        "description": "EXPIRED"
      }],
      "number": "150",
      "name": "ExecType",
      "type": "CHAR"
    }, {
      "number": "151",
      "name": "LeavesQty",
      "type": "INT"
    }, {
      "number": "152",
      "name": "CashOrderQty",
      "type": "FLOAT"
    }, {
      "number": "153",
      "name": "AllocAvgPx",
      "type": "FLOAT"
    }, {
      "number": "154",
      "name": "AllocNetMoney",
      "type": "FLOAT"
    }, {
      "number": "155",
      "name": "SettlCurrFxRate",
      "type": "FLOAT"
    }, {
      "value": [{
        "enum": "M",
        "description": "MULTIPLY"
      }, {
        "enum": "D",
        "description": "DIVIDE"
      }],
      "number": "156",
      "name": "SettlCurrFxRateCalc",
      "type": "CHAR"
    }, {
      "number": "157",
      "name": "NumDaysInterest",
      "type": "INT"
    }, {
      "number": "158",
      "name": "AccruedInterestRate",
      "type": "FLOAT"
    }, {
      "number": "159",
      "name": "AccruedInterestAmt",
      "type": "FLOAT"
    }, {
      "value": [{
        "enum": "0",
        "description": "DEFAULT"
      }, {
        "enum": "1",
        "description": "STANDING_INSTRUCTIONS_PROVIDED"
      }, {
        "enum": "2",
        "description": "SPECIFIC_ALLOCATION_ACCOUNT_OVERRIDING"
      }, {
        "enum": "3",
        "description": "SPECIFIC_ALLOCATION_ACCOUNT_STANDING"
      }],
      "number": "160",
      "name": "SettlInstMode",
      "type": "CHAR"
    }, {
      "number": "161",
      "name": "AllocText",
      "type": "CHAR"
    }, {
      "number": "162",
      "name": "SettlInstID",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "C",
        "description": "CANCEL"
      }, {
        "enum": "N",
        "description": "NEW"
      }, {
        "enum": "R",
        "description": "REPLACE"
      }],
      "number": "163",
      "name": "SettlInstTransType",
      "type": "CHAR"
    }, {
      "number": "164",
      "name": "EmailThreadID",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "1",
        "description": "BROKERS_INSTRUCTIONS"
      }, {
        "enum": "2",
        "description": "INSTITUTIONS_INSTRUCTIONS"
      }],
      "number": "165",
      "name": "SettlInstSource",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "CED",
        "description": "CEDEL"
      }, {
        "enum": "DTC",
        "description": "DEPOSITORY_TRUST_COMPANY"
      }, {
        "enum": "EUR",
        "description": "EUROCLEAR"
      }, {
        "enum": "FED",
        "description": "FEDERAL_BOOK_ENTRY"
      }, {
        "enum": "ISO Country Code",
        "description": "LOCAL_MARKET_SETTLE_LOCATION"
      }, {
        "enum": "PNY",
        "description": "PHYSICAL"
      }, {
        "enum": "PTC",
        "description": "PARTICIPANT_TRUST_COMPANY"
      }],
      "number": "166",
      "name": "SettlLocation",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "BA",
        "description": "BANKERS_ACCEPTANCE"
      }, {
        "enum": "CD",
        "description": "CERTIFICATE_OF_DEPOSIT"
      }, {
        "enum": "CMO",
        "description": "COLLATERALIZE_MORTGAGE_OBLIGATION"
      }, {
        "enum": "CORP",
        "description": "CORPORATE_BOND"
      }, {
        "enum": "CP",
        "description": "COMMERCIAL_PAPER"
      }, {
        "enum": "CPP",
        "description": "CORPORATE_PRIVATE_PLACEMENT"
      }, {
        "enum": "CS",
        "description": "COMMON_STOCK"
      }, {
        "enum": "FHA",
        "description": "FEDERAL_HOUSING_AUTHORITY"
      }, {
        "enum": "FHL",
        "description": "FEDERAL_HOME_LOAN"
      }, {
        "enum": "FN",
        "description": "FEDERAL_NATIONAL_MORTGAGE_ASSOCIATION"
      }, {
        "enum": "FOR",
        "description": "FOREIGN_EXCHANGE_CONTRACT"
      }, {
        "enum": "FUT",
        "description": "FUTURE"
      }, {
        "enum": "GN",
        "description": "GOVERNMENT_NATIONAL_MORTGAGE_ASSOCIATION"
      }, {
        "enum": "GOVT",
        "description": "TREASURIES_PLUS_AGENCY_DEBENTURE"
      }, {
        "enum": "MF",
        "description": "MUTUAL_FUND"
      }, {
        "enum": "MIO",
        "description": "MORTGAGE_INTEREST_ONLY"
      }, {
        "enum": "MPO",
        "description": "MORTGAGE_PRINCIPLE_ONLY"
      }, {
        "enum": "MPP",
        "description": "MORTGAGE_PRIVATE_PLACEMENT"
      }, {
        "enum": "MPT",
        "description": "MISCELLANEOUS_PASS_THRU"
      }, {
        "enum": "MUNI",
        "description": "MUNICIPAL_BOND"
      }, {
        "enum": "NONE",
        "description": "NO_ISITC_SECURITY_TYPE"
      }, {
        "enum": "OPT",
        "description": "OPTION"
      }, {
        "enum": "PS",
        "description": "PREFERRED_STOCK"
      }, {
        "enum": "RP",
        "description": "REPURCHASE_AGREEMENT"
      }, {
        "enum": "RVRP",
        "description": "REVERSE_REPURCHASE_AGREEMENT"
      }, {
        "enum": "SL",
        "description": "STUDENT_LOAN_MARKETING_ASSOCIATION"
      }, {
        "enum": "TD",
        "description": "TIME_DEPOSIT"
      }, {
        "enum": "USTB",
        "description": "US_TREASURY_BILL"
      }, {
        "enum": "WAR",
        "description": "WARRANT"
      }, {
        "enum": "ZOO",
        "description": "CATS_TIGERS_LIONS"
      }],
      "number": "167",
      "name": "SecurityType",
      "type": "CHAR"
    }, {
      "number": "168",
      "name": "EffectiveTime",
      "type": "TIME"
    }, {
      "value": [{
        "enum": "0",
        "description": "OTHER"
      }, {
        "enum": "1",
        "description": "DTC_SID"
      }, {
        "enum": "2",
        "description": "THOMSON_ALERT"
      }, {
        "enum": "3",
        "description": "A_GLOBAL_CUSTODIAN"
      }],
      "number": "169",
      "name": "StandInstDbType",
      "type": "INT"
    }, {
      "number": "170",
      "name": "StandInstDbName",
      "type": "CHAR"
    }, {
      "number": "171",
      "name": "StandInstDbID",
      "type": "CHAR"
    }, {
      "number": "172",
      "name": "SettlDeliveryType",
      "type": "INT"
    }, {
      "number": "173",
      "name": "SettlDepositoryCode",
      "type": "CHAR"
    }, {
      "number": "174",
      "name": "SettlBrkrCode",
      "type": "CHAR"
    }, {
      "number": "175",
      "name": "SettlInstCode",
      "type": "CHAR"
    }, {
      "number": "176",
      "name": "SecuritySettlAgentName",
      "type": "CHAR"
    }, {
      "number": "177",
      "name": "SecuritySettlAgentCode",
      "type": "CHAR"
    }, {
      "number": "178",
      "name": "SecuritySettlAgentAcctNum",
      "type": "CHAR"
    }, {
      "number": "179",
      "name": "SecuritySettlAgentAcctName",
      "type": "CHAR"
    }, {
      "number": "180",
      "name": "SecuritySettlAgentContactName",
      "type": "CHAR"
    }, {
      "number": "181",
      "name": "SecuritySettlAgentContactPhone",
      "type": "CHAR"
    }, {
      "number": "182",
      "name": "CashSettlAgentName",
      "type": "CHAR"
    }, {
      "number": "183",
      "name": "CashSettlAgentCode",
      "type": "CHAR"
    }, {
      "number": "184",
      "name": "CashSettlAgentAcctNum",
      "type": "CHAR"
    }, {
      "number": "185",
      "name": "CashSettlAgentAcctName",
      "type": "CHAR"
    }, {
      "number": "186",
      "name": "CashSettlAgentContactName",
      "type": "CHAR"
    }, {
      "number": "187",
      "name": "CashSettlAgentContactPhone",
      "type": "CHAR"
    }, {
      "number": "188",
      "name": "BidSpotRate",
      "type": "FLOAT"
    }, {
      "number": "189",
      "name": "BidForwardPoints",
      "type": "FLOAT"
    }, {
      "number": "190",
      "name": "OfferSpotRate",
      "type": "FLOAT"
    }, {
      "number": "191",
      "name": "OfferForwardPoints",
      "type": "FLOAT"
    }, {
      "number": "192",
      "name": "OrderQty2",
      "type": "FLOAT"
    }, {
      "number": "193",
      "name": "FutSettDate2",
      "type": "DATE"
    }, {
      "number": "194",
      "name": "LastSpotRate",
      "type": "FLOAT"
    }, {
      "number": "195",
      "name": "LastForwardPoints",
      "type": "FLOAT"
    }, {
      "number": "196",
      "name": "AllocLinkID",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "0",
        "description": "F_X_NETTING"
      }, {
        "enum": "1",
        "description": "F_X_SWAP"
      }],
      "number": "197",
      "name": "AllocLinkType",
      "type": "INT"
    }, {
      "number": "198",
      "name": "SecondaryOrderID",
      "type": "CHAR"
    }, {
      "number": "199",
      "name": "NoIOIQualifiers",
      "type": "INT"
    }, {
      "number": "200",
      "name": "MaturityMonthYear",
      "type": "MONTHYEAR"
    }, {
      "value": [{
        "enum": "0",
        "description": "PUT"
      }, {
        "enum": "1",
        "description": "CALL"
      }],
      "number": "201",
      "name": "PutOrCall",
      "type": "INT"
    }, {
      "number": "202",
      "name": "StrikePrice",
      "type": "FLOAT"
    }, {
      "value": [{
        "enum": "0",
        "description": "COVERED"
      }, {
        "enum": "1",
        "description": "UNCOVERED"
      }],
      "number": "203",
      "name": "CoveredOrUncovered",
      "type": "INT"
    }, {
      "value": [{
        "enum": "0",
        "description": "CUSTOMER"
      }, {
        "enum": "1",
        "description": "FIRM"
      }],
      "number": "204",
      "name": "CustomerOrFirm",
      "type": "INT"
    }, {
      "number": "205",
      "name": "MaturityDay",
      "type": "DAYOFMONTH"
    }, {
      "number": "206",
      "name": "OptAttribute",
      "type": "CHAR"
    }, {
      "number": "207",
      "name": "SecurityExchange",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "N",
        "description": "NO"
      }, {
        "enum": "Y",
        "description": "YES"
      }],
      "number": "208",
      "name": "NotifyBrokerOfCredit",
      "type": "CHAR"
    }, {
      "value": [{
        "enum": "1",
        "description": "MATCH"
      }, {
        "enum": "2",
        "description": "FORWARD"
      }, {
        "enum": "3",
        "description": "FORWARD_AND_MATCH"
      }],
      "number": "209",
      "name": "AllocHandlInst",
      "type": "INT"
    }, {
      "number": "210",
      "name": "MaxShow",
      "type": "INT"
    }, {
      "number": "211",
      "name": "PegDifference",
      "type": "FLOAT"
    }]
  }
};
